package nirvana.hall.orm.config

// default package
// Generated Jan 6, 2016 5:46:16 PM by hall orm generator 4.3.1.Final


import javax.persistence.{Column, Entity, Id, Table}

import nirvana.hall.orm.services.{ActiveRecord, ActiveRecordInstance};

/**
 * nirvana.hall.orm.config.ModelA generated by hbm2scala
 */
object ModelA extends ActiveRecordInstance[ModelA]

@Entity
@Table(name = "MODEL_A"
  , schema = "PUBLIC"
  , catalog = "XX"
)
class ModelA() extends ActiveRecord {

  @Id
  @Column(name = "ID", unique = true, nullable = false)
  var id: Int = _


  @Column(name = "NAME")
  var name: java.lang.String = _

  def this(id:Int) {
    this()
    this.id = id;
  }
  def this(id:Int, name:java.lang.String) {
    this()
    this.id = id;
    this.name = name;
  }


}


