package nirvana.hall.webservice.jpa.survey

// Generated 2018-7-24 14:53:35 by Stark Activerecord generator 4.3.1.Final


import javax.persistence.{Column, Entity, Id, Table}

import stark.activerecord.services.{ActiveRecord, ActiveRecordInstance};

/**
 * LogGetmodfingerdetail generated by stark activerecord generator
 */
object LogGetmodfingerdetail extends ActiveRecordInstance[LogGetmodfingerdetail]

@Entity
@Table(name="LOG_GETMODFINGERDETAIL"
)
class LogGetmodfingerdetail extends ActiveRecord {


    @Id
    @Column(name = "PK_ID", unique = true, nullable = false, length = 32)
    var pkId: java.lang.String = _
    @Column(name = "USERNAME", length = 20)
    var username: java.lang.String = _
    @Column(name = "YSXT_ASJBH", length = 23)
    var ysxtAsjbh: java.lang.String = _
    @Column(name = "XCKYBH", length = 23)
    var xckybh: java.lang.String = _
    @Column(name = "ASJFSDD_XZQHDM", precision = 12, scale = 0)
    var asjfsddXzqhdm: java.lang.Long = _
    @Column(name = "CALLTIME")
    var calltime: java.util.Date = _
    @Column(name = "RETURNTIME")
    var returntime: java.util.Date = _
    @Column(name = "SAVETIME")
    var savetime: java.util.Date = _
    @Column(name = "SAVESTATUS", length = 1)
    var savestatus: java.lang.String = _
    @Column(name = "FPTPATH", length = 500)
    var fptpath: java.lang.String = _
    @Column(name = "RETURNSTATUS", length = 1)
    var returnstatus: java.lang.String = _
    @Column(name = "ERRORMSG")
    var errormsg: java.lang.String = _


	
    def this(pkId:java.lang.String) {
        this()
        this.pkId = pkId
    }
    def this(pkId:java.lang.String, username:java.lang.String, ysxtAsjbh:java.lang.String, xckybh:java.lang.String, asjfsddXzqhdm:java.lang.Long, calltime:java.util.Date, returntime:java.util.Date, savetime:java.util.Date, savestatus:java.lang.String, fptpath:java.lang.String, returnstatus:java.lang.String, errormsg:java.lang.String) {
       this()
       this.pkId = pkId
       this.username = username
       this.ysxtAsjbh = ysxtAsjbh
       this.xckybh = xckybh
       this.asjfsddXzqhdm = asjfsddXzqhdm
       this.calltime = calltime
       this.returntime = returntime
       this.savetime = savetime
       this.savestatus = savestatus
       this.fptpath = fptpath
       this.returnstatus = returnstatus
       this.errormsg = errormsg
    }
   




}


