package nirvana.hall.webservice.jpa.survey

// Generated 2018-7-24 14:53:35 by Stark Activerecord generator 4.3.1.Final


import javax.persistence.{Column, Entity, Id, Table}

import stark.activerecord.services.{ActiveRecord, ActiveRecordInstance};

/**
 * LogPutfingerstatus generated by stark activerecord generator
 */
object LogInterfacestatus extends ActiveRecordInstance[LogInterfacestatus]

@Entity
@Table(name="LOG_INTERFACESTATUS"
)
class LogInterfacestatus extends ActiveRecord {

    @Id
    @Column(name = "PK_ID", unique = true, nullable = false, length = 32)
    var pkId: java.lang.String = _
    @Column(name = "INTERFACENAME", length = 30)
    var interfacename: java.lang.String = _
    @Column(name = "SCHEDULE", length = 40)
    var schedule: java.lang.String = _
    @Column(name = "ASJFSDD_XZQHDM", length = 12)
    var asjfsddXzqhdm: java.lang.Integer = _
    @Column(name = "CALLTIME")
    var calltime: java.util.Date = _
	
    def this(pkId:java.lang.String) {
        this()
        this.pkId = pkId
    }
    def this(pkId:java.lang.String, interfacename:java.lang.String, schedule:java.lang.String, asjfsddXzqhdm:java.lang.Integer, calltime:java.util.Date) {
       this()
       this.pkId = pkId
       this.interfacename = interfacename
       this.schedule = schedule
       this.asjfsddXzqhdm = asjfsddXzqhdm
       this.calltime = calltime
    }

}


