package nirvana.hall.webservice.jpa.survey

// Generated 2018-7-24 14:53:35 by Stark Activerecord generator 4.3.1.Final


import javax.persistence.{Column, Entity, Id, Table}

import stark.activerecord.services.{ActiveRecord, ActiveRecordInstance};

/**
 * LogPutfingerstatus generated by stark activerecord generator
 */
object LogPutfingerstatus extends ActiveRecordInstance[LogPutfingerstatus]

@Entity
@Table(name="LOG_PUTFINGERSTATUS"
)
class LogPutfingerstatus extends ActiveRecord {


    @Id
    @Column(name = "PK_ID", unique = true, nullable = false, length = 32)
    var pkId: java.lang.String = _
    @Column(name = "USERNAME", length = 20)
    var username: java.lang.String = _
    @Column(name = "XCWZBH", length = 30)
    var xcwzbh: java.lang.String = _
    @Column(name = "RESULTTYPE", length = 1)
    var resulttype: java.lang.String = _
    @Column(name = "CALLTIME")
    var calltime: java.util.Date = _
    @Column(name = "RETURNSTATUS", length = 2)
    var returnstatus: java.lang.String = _
    @Column(name = "RETURNTIME")
    var returntime: java.util.Date = _
    @Column(name = "ERRORMSG")
    var errormsg: java.lang.String = _


	
    def this(pkId:java.lang.String) {
        this()
        this.pkId = pkId
    }
    def this(pkId:java.lang.String, username:java.lang.String, xcwzbh:java.lang.String, resulttype:java.lang.String, calltime:java.util.Date, returnstatus:java.lang.String, returntime:java.util.Date, errormsg:java.lang.String) {
       this()
       this.pkId = pkId
       this.username = username
       this.xcwzbh = xcwzbh
       this.resulttype = resulttype
       this.calltime = calltime
       this.returnstatus = returnstatus
       this.returntime = returntime
       this.errormsg = errormsg
    }
   




}


