
package nirvana.hall.webservice.survey.gz.client;

import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FPT50HandprintService", targetNamespace = "http://xckyservice.hisign.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FPT50HandprintService {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendLLHitResult", targetNamespace = "http://xckyservice.hisign.com/", className = "nirvana.hall.webservice.survey.gz.client.SendLLHitResult")
    @ResponseWrapper(localName = "sendLLHitResultResponse", targetNamespace = "http://xckyservice.hisign.com/", className = "nirvana.hall.webservice.survey.gz.client.SendLLHitResultResponse")
    public String sendLLHitResult(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    byte[] arg3);

    /**
     * 
     * @param xckybh
     * @param userID
     * @param ks
     * @param jssj
     * @param kssj
     * @param js
     * @param asjfsddXzqhdm
     * @param password
     * @param zzhwlx
     * @return
     *     returns javax.activation.DataHandler
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFingerPrintList", targetNamespace = "http://xckyservice.hisign.com/", className = "nirvana.hall.webservice.survey.gz.client.GetFingerPrintList")
    @ResponseWrapper(localName = "getFingerPrintListResponse", targetNamespace = "http://xckyservice.hisign.com/", className = "nirvana.hall.webservice.survey.gz.client.GetFingerPrintListResponse")
    public DataHandler getFingerPrintList(
            @WebParam(name = "userID", targetNamespace = "")
                    String userID,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "asjfsdd_xzqhdm", targetNamespace = "")
                    String asjfsddXzqhdm,
            @WebParam(name = "zzhwlx", targetNamespace = "")
                    String zzhwlx,
            @WebParam(name = "xckybh", targetNamespace = "")
                    String xckybh,
            @WebParam(name = "kssj", targetNamespace = "")
                    String kssj,
            @WebParam(name = "jssj", targetNamespace = "")
                    String jssj,
            @WebParam(name = "ks", targetNamespace = "")
                    int ks,
            @WebParam(name = "js", targetNamespace = "")
                    int js);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendLTHitResult", targetNamespace = "http://xckyservice.hisign.com/", className = "nirvana.hall.webservice.survey.gz.client.SendLTHitResult")
    @ResponseWrapper(localName = "sendLTHitResultResponse", targetNamespace = "http://xckyservice.hisign.com/", className = "nirvana.hall.webservice.survey.gz.client.SendLTHitResultResponse")
    public String sendLTHitResult(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    byte[] arg3);

    /**
     * 
     * @param xckybh
     * @param userID
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReceptionNo", targetNamespace = "http://xckyservice.hisign.com/", className = "nirvana.hall.webservice.survey.gz.client.GetReceptionNo")
    @ResponseWrapper(localName = "getReceptionNoResponse", targetNamespace = "http://xckyservice.hisign.com/", className = "nirvana.hall.webservice.survey.gz.client.GetReceptionNoResponse")
    public String getReceptionNo(
            @WebParam(name = "userID", targetNamespace = "")
                    String userID,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "xckybh", targetNamespace = "")
                    String xckybh);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendModiFingerPrint", targetNamespace = "http://xckyservice.hisign.com/", className = "nirvana.hall.webservice.survey.gz.client.SendModiFingerPrint")
    @ResponseWrapper(localName = "sendModiFingerPrintResponse", targetNamespace = "http://xckyservice.hisign.com/", className = "nirvana.hall.webservice.survey.gz.client.SendModiFingerPrintResponse")
    public String sendModiFingerPrint(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    byte[] arg3);

    /**
     * 
     * @param xckybh
     * @param userID
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCaseNo", targetNamespace = "http://xckyservice.hisign.com/", className = "nirvana.hall.webservice.survey.gz.client.GetCaseNo")
    @ResponseWrapper(localName = "getCaseNoResponse", targetNamespace = "http://xckyservice.hisign.com/", className = "nirvana.hall.webservice.survey.gz.client.GetCaseNoResponse")
    public String getCaseNo(
            @WebParam(name = "userID", targetNamespace = "")
                    String userID,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "xckybh", targetNamespace = "")
                    String xckybh);

    /**
     * 
     * @param userID
     * @param password
     * @param xcwzbh
     * @return
     *     returns javax.activation.DataHandler
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFingerPrint", targetNamespace = "http://xckyservice.hisign.com/", className = "nirvana.hall.webservice.survey.gz.client.GetFingerPrint")
    @ResponseWrapper(localName = "getFingerPrintResponse", targetNamespace = "http://xckyservice.hisign.com/", className = "nirvana.hall.webservice.survey.gz.client.GetFingerPrintResponse")
    public DataHandler getFingerPrint(
            @WebParam(name = "userID", targetNamespace = "")
                    String userID,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "xcwzbh", targetNamespace = "")
                    String xcwzbh);

    /**
     * 
     * @param userID
     * @param resultType
     * @param password
     * @param xcwzbh
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendFBUseCondition", targetNamespace = "http://xckyservice.hisign.com/", className = "nirvana.hall.webservice.survey.gz.client.SendFBUseCondition")
    @ResponseWrapper(localName = "sendFBUseConditionResponse", targetNamespace = "http://xckyservice.hisign.com/", className = "nirvana.hall.webservice.survey.gz.client.SendFBUseConditionResponse")
    public String sendFBUseCondition(
            @WebParam(name = "userID", targetNamespace = "")
                    String userID,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "xcwzbh", targetNamespace = "")
                    String xcwzbh,
            @WebParam(name = "resultType", targetNamespace = "")
                    String resultType);

    /**
     * 
     * @param xckybh
     * @param userID
     * @param jssj
     * @param kssj
     * @param asjfsddXzqhdm
     * @param password
     * @param zzhwlx
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFingerPrintCount", targetNamespace = "http://xckyservice.hisign.com/", className = "nirvana.hall.webservice.survey.gz.client.GetFingerPrintCount")
    @ResponseWrapper(localName = "getFingerPrintCountResponse", targetNamespace = "http://xckyservice.hisign.com/", className = "nirvana.hall.webservice.survey.gz.client.GetFingerPrintCountResponse")
    public String getFingerPrintCount(
            @WebParam(name = "userID", targetNamespace = "")
                    String userID,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "asjfsdd_xzqhdm", targetNamespace = "")
                    String asjfsddXzqhdm,
            @WebParam(name = "zzhwlx", targetNamespace = "")
                    String zzhwlx,
            @WebParam(name = "xckybh", targetNamespace = "")
                    String xckybh,
            @WebParam(name = "kssj", targetNamespace = "")
                    String kssj,
            @WebParam(name = "jssj", targetNamespace = "")
                    String jssj);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSystemDateTime", targetNamespace = "http://xckyservice.hisign.com/", className = "nirvana.hall.webservice.survey.gz.client.GetSystemDateTime")
    @ResponseWrapper(localName = "getSystemDateTimeResponse", targetNamespace = "http://xckyservice.hisign.com/", className = "nirvana.hall.webservice.survey.gz.client.GetSystemDateTimeResponse")
    public String getSystemDateTime();

}
