
package nirvana.hall.webservice.survey.gz.client;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FPT50HandprintServiceService", targetNamespace = "http://xckyservice.hisign.com/", wsdlLocation = "http://10.160.121.188:8090/xckyservice_cxf/ws/FPT50HandprintService?wsdl")
public class FPT50HandprintServiceService
    extends Service
{

    private final static URL FPT50HANDPRINTSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException FPT50HANDPRINTSERVICESERVICE_EXCEPTION;
    private final static QName FPT50HANDPRINTSERVICESERVICE_QNAME = new QName("http://xckyservice.hisign.com/", "FPT50HandprintServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.160.121.188:8090/xckyservice_cxf/ws/FPT50HandprintService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FPT50HANDPRINTSERVICESERVICE_WSDL_LOCATION = url;
        FPT50HANDPRINTSERVICESERVICE_EXCEPTION = e;
    }

    public FPT50HandprintServiceService() {
        super(__getWsdlLocation(), FPT50HANDPRINTSERVICESERVICE_QNAME);
    }

    public FPT50HandprintServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FPT50HANDPRINTSERVICESERVICE_QNAME, features);
    }

    public FPT50HandprintServiceService(URL wsdlLocation) {
        super(wsdlLocation, FPT50HANDPRINTSERVICESERVICE_QNAME);
    }

    public FPT50HandprintServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FPT50HANDPRINTSERVICESERVICE_QNAME, features);
    }

    public FPT50HandprintServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FPT50HandprintServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FPT50HandprintService
     */
    @WebEndpoint(name = "FPT50HandprintServicePort")
    public FPT50HandprintService getFPT50HandprintServicePort() {
        return super.getPort(new QName("http://xckyservice.hisign.com/", "FPT50HandprintServicePort"), FPT50HandprintService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FPT50HandprintService
     */
    @WebEndpoint(name = "FPT50HandprintServicePort")
    public FPT50HandprintService getFPT50HandprintServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xckyservice.hisign.com/", "FPT50HandprintServicePort"), FPT50HandprintService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FPT50HANDPRINTSERVICESERVICE_EXCEPTION!= null) {
            throw FPT50HANDPRINTSERVICESERVICE_EXCEPTION;
        }
        return FPT50HANDPRINTSERVICESERVICE_WSDL_LOCATION;
    }

}
