
package nirvana.hall.webservice.survey.gz.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HandprintService", targetNamespace = "http://service", wsdlLocation = "http://10.160.121.186:9080/xckyservice/service/HandprintService?wsdl")
public class HandprintService
    extends Service
{

    private final static URL HANDPRINTSERVICE_WSDL_LOCATION;
    private final static WebServiceException HANDPRINTSERVICE_EXCEPTION;
    private final static QName HANDPRINTSERVICE_QNAME = new QName("http://service", "HandprintService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.160.121.186:9080/xckyservice/service/HandprintService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HANDPRINTSERVICE_WSDL_LOCATION = url;
        HANDPRINTSERVICE_EXCEPTION = e;
    }

    public HandprintService() {
        super(__getWsdlLocation(), HANDPRINTSERVICE_QNAME);
    }

    public HandprintService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HANDPRINTSERVICE_QNAME, features);
    }

    public HandprintService(URL wsdlLocation) {
        super(wsdlLocation, HANDPRINTSERVICE_QNAME);
    }

    public HandprintService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HANDPRINTSERVICE_QNAME, features);
    }

    public HandprintService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HandprintService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HandprintServicePortType
     */
    @WebEndpoint(name = "HandprintServiceHttpPort")
    public HandprintServicePortType getHandprintServiceHttpPort() {
        return super.getPort(new QName("http://service", "HandprintServiceHttpPort"), HandprintServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HandprintServicePortType
     */
    @WebEndpoint(name = "HandprintServiceHttpPort")
    public HandprintServicePortType getHandprintServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service", "HandprintServiceHttpPort"), HandprintServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HANDPRINTSERVICE_EXCEPTION!= null) {
            throw HANDPRINTSERVICE_EXCEPTION;
        }
        return HANDPRINTSERVICE_WSDL_LOCATION;
    }

}
