/**
${pojo.getClassJavaDoc(pojo.getDeclarationName() + " generated by hall orm ", 0)}
 */
object ${pojo.getDeclarationName()} extends ${pojo.importType("nirvana.hall.orm.services.ActiveRecordInstance")}[${pojo.getDeclarationName()}]

<#include "Ejb3TypeDeclaration.ftl"/>
${pojo.getDeclarationType()} ${pojo.getDeclarationName()} extends ${pojo.importType("nirvana.hall.orm.services.ActiveRecord")}