package nirvana.hall.api.migration

import monad.migration._
/**
 *
 * @author <a href="mailto:jcai@ganshane.com">Jun Tsai</a>
 * @since 2015-10-08
 */
class Migrate_20151007124532_CopyTable
  extends Migration {

  def up(): Unit = {
    createTable("CODE_AJLB",Comment("案件类别字典")){ t=>
      t.column("CODE",VarcharType,Limit(6),NotNull,Comment("字典编码"))
      t.column("NAME",VarcharType,Limit(200),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
      t.column("FIRST_LETTER",VarcharType,Limit(30),Nullable,Comment("首字母"))
    }
    createTable("CODE_AJLX",Comment("案件类型字典")){ t=>
      t.column("CODE",VarcharType,Limit(1),NotNull,Comment("字典编码"))
      t.column("NAME",VarcharType,Limit(60),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("CODE_AJLY",Comment("案件来源字典")){ t=>
      t.column("CODE",VarcharType,Limit(1),NotNull,Comment("字典编码"))
      t.column("NAME",VarcharType,Limit(60),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("CODE_AJXZ",Comment("案件性质字典")){ t=>
      t.column("CODE",VarcharType,Limit(3),NotNull,Comment("字典编码"))
      t.column("NAME",VarcharType,Limit(60),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
      t.column("FIRST_LETTER",VarcharType,Limit(30),Nullable,Comment("首字母"))
    }
    createTable("CODE_AJZT",Comment("案件状态")){ t=>
      t.column("CODE",VarcharType,Limit(2),NotNull,Comment("字典编码"))
      t.column("NAME",VarcharType,Limit(200),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("CODE_AY",Comment("案由字典")){ t=>
      t.column("CODE",VarcharType,Limit(6),NotNull,Comment("字典编码"))
      t.column("NAME",VarcharType,Limit(200),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
      t.column("FIRST_LETTER",VarcharType,Limit(30),Nullable,Comment("首字母"))
    }
    createTable("CODE_BDZT",Comment("比对状态")){ t=>
      t.column("CODE",VarcharType,Limit(2),NotNull,Comment("字典编码"))
      t.column("NAME",VarcharType,Limit(200),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("CODE_CJLB",Comment("采集类别字典")){ t=>
      t.column("CODE",VarcharType,Limit(6),NotNull,Comment("字典编码"))
      t.column("NAME",VarcharType,Limit(200),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("CODE_DHLX",Comment("电话类型字典")){ t=>
      t.column("CODE",VarcharType,Limit(3),NotNull,Comment("字典编码"))
      t.column("NAME",VarcharType,Limit(60),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("CODE_GJ",Comment("国籍字典")){ t=>
      t.column("CODE",VarcharType,Limit(6),NotNull,Comment("字典编码"))
      t.column("NAME",VarcharType,Limit(60),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("CODE_IF",Comment("是否字典")){ t=>
      t.column("CODE",VarcharType,Limit(1),NotNull,Comment("字典编码"))
      t.column("NAME",VarcharType,Limit(60),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("CODE_JJLY",Comment("经济来源")){ t=>
      t.column("CODE",VarcharType,Limit(1),NotNull,Comment("字典编码"))
      t.column("NAME",VarcharType,Limit(60),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("CODE_LX",Comment("脸型字典")){ t=>
      t.column("CODE",VarcharType,Limit(4),NotNull,Comment("字典编码"))
      t.column("NAME",VarcharType,Limit(60),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
      t.column("PATH",VarcharType,Limit(90),Nullable,Comment("路径"))
    }
    createTable("CODE_LY",Comment("捺印数据来源")){ t=>
      t.column("CODE",VarcharType,Limit(1),NotNull)
      t.column("NAME",VarcharType,Limit(60),Nullable)
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable)
      t.column("ORD",BigintType,Limit(22),Nullable)
      t.column("REMARK",VarcharType,Limit(90),Nullable)
    }
    createTable("CODE_MARRY",Comment("婚否字典")){ t=>
      t.column("CODE",VarcharType,Limit(2),NotNull,Comment("字典编码"))
      t.column("NAME",VarcharType,Limit(60),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("CODE_MZ",Comment("民族字典")){ t=>
      t.column("CODE",VarcharType,Limit(2),NotNull,Comment("字典编码"))
      t.column("NAME",VarcharType,Limit(60),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("CODE_RTXYS",Comment("乳突线颜色")){ t=>
      t.column("CODE",VarcharType,Limit(1),NotNull,Comment("字典编码"))
      t.column("NAME",VarcharType,Limit(200),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("CODE_RYLX",Comment("人员类型字典")){ t=>
      t.column("CODE",VarcharType,Limit(2),NotNull,Comment("字典编码"))
      t.column("NAME",VarcharType,Limit(200),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
      t.column("STRTYPE",VarcharType,Limit(2),Nullable,Comment("类型"))
    }
    createTable("CODE_SHYY",Comment("审核原因")){ t=>
      t.column("CODE",VarcharType,Limit(6),NotNull,Comment("字典编码"))
      t.column("NAME",VarcharType,Limit(200),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("CODE_TSRQ",Comment("特殊人群字典")){ t=>
      t.column("CODE",VarcharType,Limit(1),NotNull,Comment("字典编码"))
      t.column("NAME",VarcharType,Limit(60),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("CODE_TSSF",Comment("特殊身份字典")){ t=>
      t.column("CODE",VarcharType,Limit(4),NotNull,Comment("字典编码"))
      t.column("NAME",VarcharType,Limit(60),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("CODE_TX",Comment("体型字典")){ t=>
      t.column("CODE",VarcharType,Limit(4),NotNull,Comment("字典编码"))
      t.column("NAME",VarcharType,Limit(60),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("CODE_TXLX",Comment("图像类型")){ t=>
      t.column("CODE",VarcharType,Limit(10),NotNull,Comment("字典编码"))
      t.column("NAME",VarcharType,Limit(60),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("CODE_WHCD",Comment("文化程度字典")){ t=>
      t.column("CODE",VarcharType,Limit(2),NotNull,Comment("字典编码"))
      t.column("NAME",VarcharType,Limit(60),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("CODE_XB",Comment("性别字典")){ t=>
      t.column("CODE",VarcharType,Limit(1),NotNull,Comment("字典编码"))
      t.column("NAME",VarcharType,Limit(60),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("CODE_XCJB",Comment("协查级别")){ t=>
      t.column("CODE",VarcharType,Limit(1),NotNull,Comment("字典编码"))
      t.column("NAME",VarcharType,Limit(200),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("CODE_XCTQFS",Comment("现场提取方式")){ t=>
      t.column("CODE",VarcharType,Limit(2),NotNull,Comment("字典编码"))
      t.column("NAME",VarcharType,Limit(200),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("CODE_XNSFLX",Comment("虚拟身份类型字典")){ t=>
      t.column("CODE",VarcharType,Limit(2),NotNull,Comment("字典编码"))
      t.column("NAME",VarcharType,Limit(60),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("CODE_XX",Comment("血型字典")){ t=>
      t.column("CODE",VarcharType,Limit(20),NotNull,Comment("字典编码"))
      t.column("NAME",VarcharType,Limit(60),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("CODE_YHSF",Comment("用户身份数据字典")){ t=>
      t.column("CODE",VarcharType,Limit(1),NotNull,Comment("字典编码"))
      t.column("NAME",VarcharType,Limit(60),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("CODE_YHZT",Comment("用户状态数据字典")){ t=>
      t.column("CODE",VarcharType,Limit(1),NotNull,Comment("字典编码"))
      t.column("NAME",VarcharType,Limit(60),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("CODE_ZC",Comment("专长字典")){ t=>
      t.column("CODE",VarcharType,Limit(2),NotNull,Comment("字典编码"))
      t.column("NAME",VarcharType,Limit(60),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("CODE_ZJXY",Comment("宗教信仰字典")){ t=>
      t.column("CODE",VarcharType,Limit(2),NotNull,Comment("字典编码"))
      t.column("NAME",VarcharType,Limit(60),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("CODE_ZJZL",Comment("证件类型字典")){ t=>
      t.column("CODE",VarcharType,Limit(2),NotNull,Comment("字典编码"))
      t.column("NAME",VarcharType,Limit(60),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("CODE_ZWZT",Comment("采集记录状态字典")){ t=>
      t.column("CODE",VarcharType,Limit(2),NotNull,Comment("字典编码"))
      t.column("NAME",VarcharType,Limit(60),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("CODE_ZY",Comment("职业字典")){ t=>
      t.column("CODE",VarcharType,Limit(4),NotNull,Comment("字典编码"))
      t.column("NAME",VarcharType,Limit(60),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("CODE_ZZMM",Comment("政治面貌字典")){ t=>
      t.column("CODE",VarcharType,Limit(2),NotNull,Comment("字典编码"))
      t.column("NAME",VarcharType,Limit(60),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("GAFIS_AUTO_COMPARE_CONF",Comment("自动比对配置")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull)
      t.column("ITEM",VarcharType,Limit(2),Nullable,Comment("配置项"))
      t.column("DESCRIPTION",VarcharType,Limit(90),Nullable,Comment("配置项描述"))
      t.column("VALUE",IntegerType,Limit(10),Nullable,Comment("值"))
    }
    createTable("GAFIS_AUTO_CONFIGURE",Comment("自动比对配置")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull)
      t.column("AUTO_TT",BigintType,Limit(22),Nullable,Comment("重查"))
      t.column("AUTO_TL",BigintType,Limit(22),Nullable,Comment("倒查"))
      t.column("AUTO_LT",BigintType,Limit(22),Nullable,Comment("正查"))
      t.column("AUTO_LL",BigintType,Limit(22),Nullable,Comment("串查"))
      t.column("MARK",CharType,Limit(1),Nullable,Comment("系统标志：1：标采"))
    }
    createTable("GAFIS_CASE",Comment("案件信息")){ t=>
      t.column("CASE_ID",VarcharType,Limit(23),NotNull,Comment("案件编号共23字节，第1位为大写英文字母A，第2至13位为立案单位代码，第14至17位为年份，第18至19位为月份，第20至23位为顺序号"),PrimaryKey)
      t.column("CARD_ID",VarcharType,Limit(23),Nullable,Comment("卡号"))
      t.column("CASE_CLASS_CODE",VarcharType,Limit(6),Nullable,Comment("案件类别(字典与案事件系统相同)"))
      t.column("CASE_OCCUR_DATE",TimestampType,Limit(7),Nullable,Comment("发案日期"))
      t.column("CASE_OCCUR_PLACE_CODE",VarcharType,Limit(6),Nullable,Comment("发案地点代码"))
      t.column("CASE_OCCUR_PLACE_DETAIL",VarcharType,Limit(70),Nullable,Comment("发案地点"))
      t.column("CASE_BRIEF_DETAIL",VarcharType,Limit(1000),Nullable,Comment("简要案情"))
      t.column("IS_MURDER",VarcharType,Limit(1),Nullable,Comment("命案标识1:是/0:否"))
      t.column("AMOUNT",VarcharType,Limit(16),Nullable,Comment("涉案金额(单位：元)"))
      t.column("EXTRACT_UNIT_CODE",VarcharType,Limit(12),Nullable,Comment("提取单位代码"))
      t.column("EXTRACT_UNIT_NAME",VarcharType,Limit(90),Nullable,Comment("提取单位名称"))
      t.column("EXTRACT_DATE",TimestampType,Limit(7),Nullable,Comment("提取日期"))
      t.column("EXTRACTOR",VarcharType,Limit(30),Nullable,Comment("提取人"))
      t.column("SUSPICIOUS_AREA_CODE",VarcharType,Limit(6),Nullable,Comment("可疑地区线索"))
      t.column("CASE_STATE",VarcharType,Limit(2),Nullable,Comment("案件状态(采用案事件系统的案件状态)"))
      t.column("CASE_NATURE",VarcharType,Limit(3),Nullable,Comment("案件性质(按照案事件系统标准)"))
      t.column("REMARK",VarcharType,Limit(1000),Nullable,Comment("备注"))
      t.column("INPUTPSN",VarcharType,Limit(32),Nullable,Comment("记录创建人ID SYS_USER"))
      t.column("INPUTTIME",TimestampType,Limit(7),Nullable,Comment("记录创建时间"))
      t.column("MODIFIEDPSN",VarcharType,Limit(32),Nullable,Comment("记录更新人ID SYS_USER"))
      t.column("MODIFIEDTIME",TimestampType,Limit(7),Nullable,Comment("记录更新时间"))
      t.column("DELETAG",VarcharType,Limit(1),Nullable,Comment("删除标志"))
      t.column("BROKEN_STATUS",SmallintType,Limit(3),Nullable,Comment("是否破案"))
      t.column("CASE_SOURCE",VarcharType,Limit(1),Nullable,Comment("案件来源"))
      t.column("CREATE_UNIT_CODE",VarcharType,Limit(12),Nullable)
      t.column("ASSIST_LEVEL",VarcharType,Limit(1),Nullable,Comment("协查级别"))
      t.column("CASE_NATURE_OLD",VarcharType,Limit(60),Nullable,Comment("原案件性质(名称描述)"))
      t.column("IS_CHECKED",CharType,Limit(1),Nullable,Comment("是否比中1:是/否"))
      t.column("FPT_EXTRACT_UNIT_CODE",VarcharType,Limit(12),Nullable,Comment("FPT提取单位代码"))
      t.column("FPT_EXTRACT_UNIT_NAME",VarcharType,Limit(90),Nullable,Comment("FPT提取单位名称"))
      t.column("SID",BigintType,Limit(22),Nullable,Comment("SID比对唯一标识"))
      t.column("ASSIST_BONUS",VarcharType,Limit(6),Nullable,Comment("协查标识"))
      t.column("ASSIST_DEPT_CODE",VarcharType,Limit(12),Nullable,Comment("协查单位代码"))
      t.column("ASSIST_DEPT_NAME",VarcharType,Limit(70),Nullable,Comment("协查单位名称"))
      t.column("ASSIST_DATE",VarcharType,Limit(8),Nullable,Comment("协查日期(格式:YYYYMMDD)"))
      t.column("ASSIST_SIGN",VarcharType,Limit(1),Nullable,Comment("案件协查标识(1:协查;0:不协查)"))
      t.column("ASSIST_REVOKE_SIGN",VarcharType,Limit(1),Nullable,Comment("部撤销标识(1:已破;2:外省;3:多报;4:其他)"))
    }
    createTable("GAFIS_CASE_FINGER",Comment("现场指纹")){ t=>
      t.column("SEQ_NO",VarcharType,Limit(2),Nullable,Comment("指纹序号"))
      t.column("FINGER_ID",VarcharType,Limit(25),NotNull,Comment("指纹编号"))
      t.column("CASE_ID",VarcharType,Limit(23),Nullable,Comment("案件编号"))
      t.column("IS_CORPSE",VarcharType,Limit(1),Nullable,Comment("未知名尸体标识(1:是/0:否)"))
      t.column("CORPSE_NO",VarcharType,Limit(23),Nullable,Comment("未知名尸体编号"))
      t.column("REMAIN_PLACE",VarcharType,Limit(60),Nullable,Comment("遗留部位"))
      t.column("FGP_GROUP",SmallintType,Limit(3),Nullable,Comment("指位组"))
      t.column("FGP",VarcharType,Limit(10),Nullable,Comment("分析指位:用10个字节表示，从左至右每字节依次对应指位代码01到指位代码10，每字节有效值为1或0，1表示可能为该指位，0表示不可能为该指位"))
      t.column("RIDGE_COLOR",VarcharType,Limit(1),Nullable,Comment("乳突线颜色"))
      t.column("PATTERN",VarcharType,Limit(20),Nullable,Comment("纹型"))
      t.column("MITTENS_BEG_NO",VarcharType,Limit(2),Nullable,Comment("连指开始序号(“00”表示没有连指)"))
      t.column("MITTENS_END_NO",VarcharType,Limit(2),Nullable,Comment("连指结束序号(“00”表示没有连指)"))
      t.column("THAN_STATUS",VarcharType,Limit(2),Nullable,Comment("指纹比对状态"))
      t.column("IS_ASSIST",VarcharType,Limit(1),Nullable,Comment("指纹协查标识"))
      t.column("FINGER_IMG",BlobType,Limit(4000),Nullable,Comment("指纹原图"))
      t.column("FINGER_CPR",BlobType,Limit(4000),Nullable,Comment("指纹压缩图"))
      t.column("LT_COUNT",BigintType,Limit(22),Nullable,Comment("累计查案（LT）次数"))
      t.column("LL_COUNT",BigintType,Limit(22),Nullable,Comment("累计串查（LL）次数"))
      t.column("LT_COUNT_MOD_MNT",BigintType,Limit(22),Nullable,Comment("特征修改后查案（LT）次数"))
      t.column("LL_COUNT_MOD_MNT",BigintType,Limit(22),Nullable,Comment("特征修改后查案（LL）次数"))
      t.column("EDIT_COUNT",BigintType,Limit(22),Nullable,Comment("特征修改后查案（LL）次数"))
      t.column("LT_DATE",TimestampType,Limit(7),Nullable,Comment("最近查案（LT）时间"))
      t.column("LL_DATE",TimestampType,Limit(7),Nullable,Comment("最近串查（LL）时间"))
      t.column("LT_OPERATOR",VarcharType,Limit(32),Nullable,Comment("最近查案（LT）操作者"))
      t.column("LL_OPERATOR",VarcharType,Limit(32),Nullable,Comment("最近串查（LL）操作者"))
      t.column("LT_STATUS",VarcharType,Limit(1),Nullable,Comment("查案比中状态：1：比中；0：未比中"))
      t.column("LL_STATUS",VarcharType,Limit(1),Nullable,Comment("串案比中状态：1：比中；0：未比中"))
      t.column("CREATOR_UNIT_CODE",VarcharType,Limit(12),Nullable,Comment("创建单位代码"))
      t.column("UPDATOR_UNIT_CODE",VarcharType,Limit(12),Nullable,Comment("更新单位代码"))
      t.column("MODIFIEDTIME",TimestampType,Limit(7),Nullable,Comment("记录更新时间"))
      t.column("MODIFIEDPSN",VarcharType,Limit(32),Nullable,Comment("记录更新人ID SYS_USER"))
      t.column("INPUTTIME",TimestampType,Limit(7),Nullable,Comment("记录创建时间"))
      t.column("INPUTPSN",VarcharType,Limit(32),Nullable,Comment("记录创建人ID SYS_USER"))
      t.column("DELETAG",VarcharType,Limit(1),Nullable,Comment("删除标志"))
      t.column("REMARK",VarcharType,Limit(1000),Nullable,Comment("备注"))
      t.column("SID",BigintType,Limit(22),Nullable,Comment("SID比对唯一标识"))
      t.column("MATCH_STATUS",VarcharType,Limit(1),Nullable,Comment("比对状态:1待查 2撤销 3比中 9其他"))
      t.column("DEVELOP_METHOD",VarcharType,Limit(2),Nullable,Comment("现场提取方式code_xctqfs"))
      t.column("FINGER_CPR_NOSQL_ID",VarcharType,Limit(10),Nullable,Comment("指纹压缩图nosql存储id"))
      t.column("FINGER_IMG_NOSQL_ID",VarcharType,Limit(10),Nullable,Comment("指纹原图nosql存储id"))
      t.column("SEQ",BigintType,Limit(22),Nullable,Comment("8.0数据同步用"))
    }
    createTable("GAFIS_CASE_FINGER_MNT",Comment("现场指纹特征表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull,Comment("PK_ID主键"))
      t.column("FINGER_ID",VarcharType,Limit(25),Nullable,Comment("指纹编号"))
      t.column("CAPTURE_METHOD",VarcharType,Limit(1),Nullable,Comment("现场指纹特征提取方式：A自动提取 U需要人工编辑 E自动提取经过人工编辑 M人工提取"))
      t.column("FINGER_MNT",BlobType,Limit(4000),Nullable,Comment("指纹特征"))
      t.column("FINGER_RIDGE",BlobType,Limit(4000),Nullable,Comment("指纹纹线"))
      t.column("IS_MAIN_MNT",VarcharType,Limit(1),Nullable,Comment("是否主特征(0：非主特征 1：是主特征)"))
      t.column("MODIFIEDTIME",TimestampType,Limit(7),Nullable,Comment("记录更新时间"))
      t.column("MODIFIEDPSN",VarcharType,Limit(32),Nullable,Comment("记录更新人ID SYS_USER"))
      t.column("INPUTTIME",TimestampType,Limit(7),Nullable,Comment("记录创建时间"))
      t.column("INPUTPSN",VarcharType,Limit(32),Nullable,Comment("记录创建人ID SYS_USER"))
      t.column("DELETAG",VarcharType,Limit(1),Nullable,Comment("删除标志"))
      t.column("FINGER_MNT_NOSQL_ID",VarcharType,Limit(10),Nullable,Comment("指纹特征nosql存储id"))
      t.column("FINGER_RIDGE_NOSQL_ID",VarcharType,Limit(10),Nullable,Comment("指纹纹线nosql存储id"))
    }
    createTable("GAFIS_CASE_PALM",Comment("现场掌纹")){ t=>
      t.column("SEQ_NO",VarcharType,Limit(2),Nullable,Comment("掌纹序号"))
      t.column("PALM_ID",VarcharType,Limit(25),NotNull,Comment("掌纹编号"))
      t.column("CASE_ID",VarcharType,Limit(23),Nullable,Comment("案件编号"))
      t.column("IS_CORPSE",VarcharType,Limit(1),Nullable,Comment("未知名尸体标识(1:是/0:否)"))
      t.column("CORPSE_NO",VarcharType,Limit(23),Nullable,Comment("未知名尸体编号"))
      t.column("REMAIN_PLACE",VarcharType,Limit(30),Nullable,Comment("遗留部位"))
      t.column("FGP",VarcharType,Limit(10),Nullable,Comment("分析指位:用10个字节表示，从左至右每字节依次对应指位代码01到指位代码10，每字节有效值为1或0，1表示可能为该指位，0表示不可能为该指位"))
      t.column("PATTERN",VarcharType,Limit(20),Nullable,Comment("纹型"))
      t.column("RIDGE_COLOR",VarcharType,Limit(1),Nullable,Comment("乳突线颜色"))
      t.column("THAN_STATUS",VarcharType,Limit(2),Nullable,Comment("掌纹比对状态"))
      t.column("IS_ASSIST",VarcharType,Limit(1),Nullable,Comment("掌纹协查标识"))
      t.column("PALM_IMG",BlobType,Limit(4000),Nullable,Comment("掌纹原图"))
      t.column("PALM_CPR",BlobType,Limit(4000),Nullable,Comment("掌纹压缩图"))
      t.column("LT_COUNT",BigintType,Limit(22),Nullable,Comment("累计查案（LT）次数"))
      t.column("LL_COUNT",BigintType,Limit(22),Nullable,Comment("累计串查（LL）次数"))
      t.column("LT_COUNT_MOD_MNT",BigintType,Limit(22),Nullable,Comment("特征修改后查案（LT）次数"))
      t.column("LL_COUNT_MOD_MNT",BigintType,Limit(22),Nullable,Comment("特征修改后查案（LL）次数"))
      t.column("EDIT_COUNT",BigintType,Limit(22),Nullable,Comment("特征修改后查案（LL）次数"))
      t.column("LT_DATE",TimestampType,Limit(7),Nullable,Comment("最近查案（LT）时间"))
      t.column("LL_DATE",TimestampType,Limit(7),Nullable,Comment("最近串查（LL）时间"))
      t.column("LT_OPERATOR",VarcharType,Limit(32),Nullable,Comment("最近查案（LT）操作者"))
      t.column("LL_OPERATOR",VarcharType,Limit(32),Nullable,Comment("最近串查（LL）操作者"))
      t.column("CREATOR_UNIT_CODE",VarcharType,Limit(12),Nullable,Comment("创建单位代码"))
      t.column("UPDATOR_UNIT_CODE",VarcharType,Limit(12),Nullable,Comment("更新单位代码"))
      t.column("MODIFIEDTIME",TimestampType,Limit(7),Nullable,Comment("记录更新时间"))
      t.column("MODIFIEDPSN",VarcharType,Limit(32),Nullable,Comment("记录更新人ID SYS_USER"))
      t.column("INPUTTIME",TimestampType,Limit(7),Nullable,Comment("记录创建时间"))
      t.column("INPUTPSN",VarcharType,Limit(32),Nullable,Comment("记录创建人ID SYS_USER"))
      t.column("DELETAG",VarcharType,Limit(1),Nullable,Comment("删除标志"))
      t.column("REMARK",VarcharType,Limit(1000),Nullable,Comment("备注"))
      t.column("LT_STATUS",VarcharType,Limit(1),Nullable,Comment("查案比中状态：1：比中；0：未比中"))
      t.column("LL_STATUS",VarcharType,Limit(1),Nullable,Comment("串案比中状态：1：比中；0：未比中"))
      t.column("SID",BigintType,Limit(22),Nullable,Comment("SID比对唯一标识"))
      t.column("MATCH_STATUS",VarcharType,Limit(1),Nullable,Comment("比对状态:1待查 2撤销 3比中 9其他"))
      t.column("DEVELOP_METHOD",VarcharType,Limit(2),Nullable,Comment("现场提取方式code_xctqfs"))
      t.column("PALM_IMG_NOSQL_ID",VarcharType,Limit(10),Nullable,Comment("掌纹原图nosql存储id"))
      t.column("PALM_CPR_NOSQL_ID",VarcharType,Limit(10),Nullable,Comment("掌纹压缩图nosql存储id"))
      t.column("SEQ",BigintType,Limit(22),Nullable,Comment("8.0数据同步用"))
    }
    createTable("GAFIS_CASE_PALM_MNT",Comment("现场掌纹特征表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull,Comment("PK_ID主键"))
      t.column("PALM_ID",VarcharType,Limit(25),Nullable,Comment("掌纹编号"))
      t.column("CAPTURE_METHOD",VarcharType,Limit(1),Nullable,Comment("特征提取方法(1：手工 2：自动)"))
      t.column("PALM_MNT",BlobType,Limit(4000),Nullable,Comment("掌纹特征"))
      t.column("PALM_RIDGE",BlobType,Limit(4000),Nullable,Comment("掌纹纹线"))
      t.column("IS_MAIN_MNT",VarcharType,Limit(1),Nullable,Comment("是否主特征(0：非主特征 1：是主特征)"))
      t.column("MODIFIEDTIME",TimestampType,Limit(7),Nullable,Comment("记录更新时间"))
      t.column("MODIFIEDPSN",VarcharType,Limit(32),Nullable,Comment("记录更新人ID SYS_USER"))
      t.column("INPUTTIME",TimestampType,Limit(7),Nullable,Comment("记录创建时间"))
      t.column("INPUTPSN",VarcharType,Limit(32),Nullable,Comment("记录创建人ID SYS_USER"))
      t.column("PALM_MNT_NOSQL_ID",VarcharType,Limit(10),Nullable,Comment("掌纹特征nosql存储Id"))
      t.column("PALM_RIDGE_NOSQL_ID",VarcharType,Limit(10),Nullable,Comment("掌纹纹线nosql存储Id"))
    }
    createTable("GAFIS_CHECKIN_APPEAL",Comment("查重-申诉表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull)
      t.column("CHECKIN_ID",VarcharType,Limit(32),NotNull,Comment("查中表编号"))
      t.column("APPEAL_USER",VarcharType,Limit(32),Nullable,Comment("申诉人"))
      t.column("APPEAL_ORG",VarcharType,Limit(32),Nullable,Comment("申诉单位"))
      t.column("APPEAL_TIME",TimestampType,Limit(7),Nullable,Comment("申诉时间"))
      t.column("REASON",VarcharType,Limit(300),Nullable,Comment("申诉理由"))
      t.column("STATUS",SmallintType,Limit(1),Nullable,Comment("申诉状态(待受理，认定，驳回)"))
      t.column("ACCEPT_USER",VarcharType,Limit(32),Nullable,Comment("受理人"))
      t.column("ACCEPT_ORG",VarcharType,Limit(32),Nullable,Comment("受理单位"))
      t.column("ACCEPT_TIME",TimestampType,Limit(7),Nullable,Comment("受理时间"))
      t.column("ACCEPT_REASON",VarcharType,Limit(300),Nullable,Comment("受理理由"))
    }
    createTable("GAFIS_CHECKIN_INFO",Comment("查中登记表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull)
      t.column("CODE",VarcharType,Limit(25),Nullable,Comment("编号1"))
      t.column("TCODE",VarcharType,Limit(25),Nullable,Comment("编号2"))
      t.column("QUERYTYPE",SmallintType,Limit(1),Nullable,Comment("比中类型(捺印查重(TT):0;  捺印倒查(TL):1;  现场查案(LT):2;  现场串查(LL):3)"))
      t.column("REGISTER_TIME",TimestampType,Limit(7),Nullable,Comment("登记时间"))
      t.column("REGISTER_USER",VarcharType,Limit(32),Nullable,Comment("登记人"))
      t.column("REGISTER_ORG",VarcharType,Limit(32),Nullable,Comment("登记单位"))
      t.column("HITPOSSIBILITY",SmallintType,Limit(3),Nullable,Comment("查中概率"))
      t.column("PRIORITY",SmallintType,Limit(3),Nullable,Comment("比对优先级(最低  0；低1；正常  2；稍高3；高  4；最高  5；实时  9；)"))
      t.column("REVIEW_STATUS",SmallintType,Limit(2),Nullable,Comment("复核状态(0: 待复核；1：复核成功；2：复核失败；3：确认复核失败)"))
      t.column("REVIEW_BOUT",SmallintType,Limit(1),Nullable,Comment("复核次数"))
      t.column("APPEAL_STATUS",SmallintType,Limit(1),Nullable,Comment("申诉状态(0：申诉待受理；1：申诉成功；2：申诉驳回；3：接受驳回)"))
      t.column("CONFIRM_STATUS",SmallintType,Limit(3),Nullable,Comment("认定状态"))
      t.column("CONFIRM_USER",VarcharType,Limit(32),Nullable,Comment("认定人"))
      t.column("CONFIRM_TIME",TimestampType,Limit(7),Nullable,Comment("认定时间"))
      t.column("QUERY_UUID",VarcharType,Limit(32),Nullable,Comment("查询任务ID"))
      t.column("REVIEW_ORG",VarcharType,Limit(32),Nullable,Comment("复核单位"))
      t.column("RANK",IntegerType,Limit(6),Nullable,Comment("比中排名"))
      t.column("FRACTION",IntegerType,Limit(6),Nullable,Comment("比中分数"))
      t.column("FGP",VarcharType,Limit(20),Nullable,Comment("比中指位"))
      t.column("CONFIRM_OPINION",VarcharType,Limit(200),Nullable,Comment("认定意见"))
      t.column("CARD_TYPE1",BigintType,Limit(22),Nullable,Comment("编号1指掌纹标识 1：指纹；2：掌纹"))
      t.column("CARD_TYPE2",BigintType,Limit(22),Nullable,Comment("编号2指掌纹标识 1：指纹；2：掌纹"))
      t.column("LAST_HANDLE_DATE",TimestampType,Limit(7),Nullable,Comment("最后处理时间"))
      t.column("OPERATETYPE",BigintType,Limit(22),Nullable,Comment("操作类型 0：自动比对；1：人工比对"))
      t.column("CK_SOURCE",VarcharType,Limit(1),Nullable,Comment("比中关系来源(1:指纹系统登记,2:FPT导入)"))
    }
    createTable("GAFIS_CHECKIN_REVIEW",Comment("复核表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull)
      t.column("CHECKIN_ID",VarcharType,Limit(32),NotNull,Comment("查中表编号"))
      t.column("RESULT",SmallintType,Limit(3),Nullable,Comment("复核结果（认定、否定、不确定）"))
      t.column("REVIEW_ORG",VarcharType,Limit(32),Nullable,Comment("复核单位"))
      t.column("REVIEW_USER",VarcharType,Limit(32),Nullable,Comment("复核人"))
      t.column("REASON",VarcharType,Limit(300),Nullable,Comment("复核理由"))
      t.column("REVIEW_TIME",TimestampType,Limit(7),Nullable,Comment("复核时间"))
    }
    createTable("GAFIS_COMPARE_CONFIGURE",Comment("比对参数优先级配置")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull)
      t.column("CONFIGURE_TT",BigintType,Limit(22),Nullable,Comment("重查"))
      t.column("CONFIGURE_TL",BigintType,Limit(22),Nullable,Comment("倒查"))
      t.column("CONFIGURE_LT",BigintType,Limit(22),Nullable,Comment("正查"))
      t.column("CONFIGURE_LL",BigintType,Limit(22),Nullable,Comment("串查"))
      t.column("ROLE_ID",VarcharType,Limit(32),Nullable,Comment("配置类型 1:发送比对任务 2:修改比对任务"))
      t.column("MARK",CharType,Limit(1),Nullable)
    }
    createTable("GAFIS_COMPARE_PARAM_MAXQUERY",Comment("比对参数最大可发查询数")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull)
      t.column("ROLE_ID",VarcharType,Limit(32),Nullable,Comment("角色id"))
      t.column("ROLE_NAME",VarcharType,Limit(60),Nullable,Comment("角色名称"))
      t.column("QUERY_TYPE",VarcharType,Limit(10),Nullable,Comment("查询类别(0正查1倒查2串查)"))
      t.column("QUERY_LEVEL",VarcharType,Limit(1),Nullable,Comment("查询级别"))
      t.column("MAX_QUERY",IntegerType,Limit(10),Nullable,Comment("最大查询数"))
    }
    createTable("GAFIS_COMPARE_PARAM_PRIORITY",Comment("比对参数优先级")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull)
      t.column("PRIORITY_ST",VarcharType,Limit(20),Nullable,Comment("省厅比对优先级"))
      t.column("PRIORITY_SZ",VarcharType,Limit(20),Nullable,Comment("市州比对优先级"))
      t.column("PRIORITY_XJ",VarcharType,Limit(20),Nullable,Comment("县级比对优先级"))
      t.column("DEFAULT_PRIORITY_ST",VarcharType,Limit(10),Nullable,Comment("省厅比对默认优先级"))
      t.column("DEFAULT_PRIORITY_SZ",VarcharType,Limit(10),Nullable,Comment("市州比对默认优先级"))
      t.column("DEFAULT_PRIORITY_XJ",VarcharType,Limit(10),Nullable,Comment("县级比对默认优先级"))
      t.column("TT_DEFAULT_LEVEL",VarcharType,Limit(10),Nullable,Comment("标采系统自动查重默认级别"))
      t.column("TL_DEFAULT_LEVEL",VarcharType,Limit(10),Nullable,Comment("标采系统自动倒查默认级别"))
    }
    createTable("GAFIS_CONFIGURE_MAXQUERY",Comment("最大可发查询数配置")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull)
      t.column("MAX_TT",BigintType,Limit(22),Nullable,Comment("重查"))
      t.column("MAX_TL",BigintType,Limit(22),Nullable,Comment("倒查"))
      t.column("MAX_LT",BigintType,Limit(22),Nullable,Comment("正查"))
      t.column("MAX_LL",BigintType,Limit(22),Nullable,Comment("串查"))
      t.column("ROLE_ID",VarcharType,Limit(32),Nullable,Comment("角色ID"))
      t.column("PRIORITY",BigintType,Default("0"),Limit(22),Nullable,Comment("级别数"))
    }
    createTable("GAFIS_CONTRORCAPTURE_PERSON",Comment("辑控抓获待审核人表")){ t=>
      t.column("PKID",VarcharType,Limit(32),NotNull,Comment("主键"))
      t.column("PERSONID",VarcharType,Limit(32),Nullable,Comment("人员编号"))
      t.column("APPROVAL_TYPE",VarcharType,Limit(1),Nullable,Comment("审核类型：0：辑控 1：抓获"))
      t.column("APPROVAL_PERSON",VarcharType,Limit(32),Nullable,Comment("审核人"))
      t.column("APPROVAL_DATE",TimestampType,Limit(7),Nullable,Comment("审核时间"))
      t.column("APPROVAL_REMARK",VarcharType,Limit(512),Nullable,Comment("审核意见:（理由）"))
      t.column("APPROVAL_RESULT",VarcharType,Limit(1),Nullable,Comment("审核结果:1:确认 0:否认"))
    }
    createTable("GAFIS_EXTRACT_MNT_TASK",Comment("提取特征任务")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull,PrimaryKey)
      t.column("DATA_ID",VarcharType,Limit(25),Nullable,Comment("数据ID"))
      t.column("TL_FLAG",VarcharType,Limit(1),Nullable,Comment("捺印现场标记(1:现场 0:捺印)"))
      t.column("FP_FLAG",VarcharType,Limit(1),Nullable,Comment("指掌纹标记(1:掌纹 0:指纹)"))
      t.column("IS_EXTRACT_RIDGE",VarcharType,Limit(1),Nullable,Comment("是否提取纹线(1:提取 0:不提取)"))
      t.column("STATUS",VarcharType,Limit(1),Nullable,Comment("任务状态(0:等待 1:完成 2:失败)"))
      t.column("FAIL_MESSAGE",VarcharType,Limit(100),Nullable,Comment("失败原因"))
      t.column("INPUTTIME",TimestampType,Limit(7),Nullable,Comment("创建时间"))
      t.column("FINISHTIME",TimestampType,Limit(7),Nullable,Comment("完成时间"))
    }
    createTable("GAFIS_FINGER_AUDIT",Comment("指纹审核")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull)
      t.column("PERSON_ID",VarcharType,Limit(32),NotNull,Comment("人员编号"))
      t.column("FGP",VarcharType,Limit(2),Nullable,Comment("指位"))
      t.column("FGP_CASE",VarcharType,Limit(1),Nullable,Comment("平面/滚动(0:滚指;1:平指)"))
      t.column("NUM",BigintType,Limit(22),Nullable,Comment("次数"))
      t.column("STATUS",VarcharType,Limit(1),Nullable,Comment("审核状态(code_shyy)"))
      t.column("DESCRIPTION",VarcharType,Limit(300),Nullable,Comment("审核描述"))
      t.column("AUDITOR",VarcharType,Limit(90),Nullable,Comment("审核人"))
      t.column("AUDIT_TIME",TimestampType,Limit(7),Nullable,Comment("审核时间"))
    }
    createTable("GAFIS_FINGER_BBS",Comment("公告")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull,Comment("主键"))
      t.column("TITLE",VarcharType,Limit(90),Nullable,Comment("公告标题"))
      t.column("CONTENTSS",VarcharType,Limit(3000),Nullable,Comment("公告内容"))
      t.column("INPUTPSN",VarcharType,Limit(32),Nullable,Comment("公告创建人"))
      t.column("INPUTTIME",TimestampType,Limit(7),Nullable,Comment("公告创建时间"))
      t.column("MODIFIEDTIME",TimestampType,Limit(7),Nullable,Comment("公告修改时间"))
      t.column("STATUS",VarcharType,Limit(1),Nullable,Comment("公告状态（草稿、已发布）"))
      t.column("DELETAG",VarcharType,Limit(1),Nullable,Comment("删除标志"))
      t.column("DEPART",VarcharType,Limit(32),Nullable,Comment("发布单位"))
    }
    createTable("GAFIS_FINGER_BBS_ATTACHMENT",Comment("公告附件表")){ t=>
      t.column("PK_ID",VarcharType,Limit(36),NotNull,Comment("主键"))
      t.column("BBSID",VarcharType,Limit(32),Nullable,Comment("公告主键"))
      t.column("FILENAME",VarcharType,Limit(90),Nullable,Comment("附件文件名"))
      t.column("FILEURL",VarcharType,Limit(90),Nullable,Comment("附件存放url"))
      t.column("FILESIZE",VarcharType,Limit(10),Nullable,Comment("附件大小"))
      t.column("FILETYPE",VarcharType,Limit(10),Nullable,Comment("附件类型"))
      t.column("DELETAG",VarcharType,Limit(1),Nullable,Comment("删除标志"))
    }
    createTable("GAFIS_FINGER_TEXT_LOG",Comment("指纹系统文本信息日志记录")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull)
      t.column("USER_ID",VarcharType,Limit(32),Nullable,Comment("用户id"))
      t.column("USER_NAME",VarcharType,Limit(90),Nullable,Comment("用户名"))
      t.column("UNIT_CODE",VarcharType,Limit(12),Nullable,Comment("单位编号"))
      t.column("UNIT_NAME",VarcharType,Limit(90),Nullable,Comment("单位名称"))
      t.column("IP",VarcharType,Limit(15),Nullable,Comment("终端标识IP"))
      t.column("OBJECT_ID",VarcharType,Limit(32),Nullable,Comment("数据id(人员 编号，现场编号)"))
      t.column("TABLE_NAME",VarcharType,Limit(30),Nullable,Comment("数据表名"))
      t.column("OLD_INFO",VarcharType,Limit(3000),Nullable,Comment("修改前信息"))
      t.column("NEW_INFO",VarcharType,Limit(3000),Nullable,Comment("修改后信息"))
      t.column("CREATE_DATETIME",TimestampType,Limit(7),Nullable,Comment("修改时间"))
    }
    createTable("GAFIS_GATHER_CERTIFICATE",Comment("采集人员证件表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull)
      t.column("PERSONID",VarcharType,Limit(23),Nullable,Comment("人员编号"))
      t.column("CERTIFICATETYPE",VarcharType,Limit(2),Nullable,Comment("证件类型CODE_ZJZL"))
      t.column("CERTIFICATEID",VarcharType,Limit(90),Nullable,Comment("证件号码"))
      t.column("ISSUEUNIT",VarcharType,Limit(60),Nullable,Comment("制发单位"))
      t.column("SIGNDATE",TimestampType,Limit(7),Nullable,Comment("签发日期"))
      t.column("VALIDITYBEGIN",TimestampType,Limit(7),Nullable,Comment("有效期起"))
      t.column("VALIDITYEND",TimestampType,Limit(7),Nullable,Comment("有效期止"))
      t.column("IFTRUE",VarcharType,Limit(1),Nullable,Comment("真伪"))
      t.column("HOLDER",VarcharType,Limit(60),Nullable,Comment("持证人"))
      t.column("INPUTPSN",VarcharType,Limit(32),Nullable,Comment("记录创建人ID"))
      t.column("INPUTTIME",TimestampType,Limit(7),Nullable,Comment("记录创建时间"))
      t.column("MODIFIEDPSN",VarcharType,Limit(32),Nullable,Comment("记录更新人ID"))
      t.column("MODIFIEDTIME",TimestampType,Limit(7),Nullable,Comment("记录更新时间"))
      t.column("DELETAG",VarcharType,Limit(1),Nullable,Comment("删除标志"))
    }
    createTable("GAFIS_GATHER_DATA_LOG",Comment("采集图像信息日志记录")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull)
      t.column("USER_ID",VarcharType,Limit(32),Nullable,Comment("用户id"))
      t.column("USER_NAME",VarcharType,Limit(90),Nullable,Comment("用户名"))
      t.column("UNIT_CODE",VarcharType,Limit(12),Nullable,Comment("单位编号"))
      t.column("UNIT_NAME",VarcharType,Limit(90),Nullable,Comment("单位名称"))
      t.column("IP",VarcharType,Limit(15),Nullable,Comment("终端标识IP"))
      t.column("OBJECT_ID",VarcharType,Limit(32),Nullable,Comment("数据id(人员 编号，现场编号)"))
      t.column("TABLE_NAME",VarcharType,Limit(30),Nullable,Comment("数据表名"))
      t.column("FGP",VarcharType,Limit(2),Nullable,Comment("1-10滚指，11-20平指，11,12,17,18掌纹"))
      t.column("OLD_DATA",BlobType,Limit(4000),Nullable,Comment("修改前数据"))
      t.column("NEW_DATA",BlobType,Limit(4000),Nullable,Comment("修改后数据"))
      t.column("LOBTYPE",SmallintType,Limit(1),Nullable,Comment("0数据;1特征;2纹线"))
      t.column("CREATE_DATETIME",TimestampType,Limit(7),Nullable,Comment("修改时间"))
    }
    createTable("GAFIS_GATHER_FIELDSET",Comment("采集必填项")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull)
      t.column("NODE_ID",VarcharType,Limit(32),Nullable,Comment("节点"))
      t.column("FIELD_NAME",VarcharType,Limit(100),Nullable,Comment("字段名称"))
      t.column("FIELD",VarcharType,Limit(32),Nullable,Comment("字段属性"))
      t.column("RULE",VarcharType,Limit(3000),Nullable,Comment("规则限制(JSON)"))
    }
    createTable("GAFIS_GATHER_FINGER",Comment("捺印指纹数据")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull,Comment("主键"),PrimaryKey)
      t.column("PERSON_ID",VarcharType,Limit(32),Nullable,Comment("人员ID"))
      t.column("FGP",SmallintType,Limit(2),NotNull,Comment("采集部位(字典)"))
      t.column("GROUP_ID",SmallintType,Limit(1),Nullable,Comment("0:默认;1:许公望压缩;3:JPG"))
      t.column("LOBTYPE",SmallintType,Limit(1),NotNull,Comment("1:数据;2特征"))
      t.column("INPUTPSN",VarcharType,Limit(32),Nullable,Comment("记录创建人ID"))
      t.column("INPUTTIME",TimestampType,Limit(7),NotNull,Comment("记录创建时间"))
      t.column("MODIFIEDPSN",VarcharType,Limit(32),Nullable,Comment("记录更新人ID"))
      t.column("MODIFIEDTIME",TimestampType,Limit(7),Nullable,Comment("记录更新时间"))
      t.column("FGP_CASE",VarcharType,Limit(1),Nullable,Comment("0:滚指;1:平指"))
      t.column("AUDIT_STATUS",SmallintType,Limit(1),Nullable,Comment("评判状态0：质量不合格   1：质量合格"))
      t.column("DESCRIPTION",VarcharType,Limit(100),Nullable,Comment("评判结果描述"))
      t.column("MAIN_PATTERN",SmallintType,Limit(1),Nullable,Comment("主纹型（0:不确定;1:弓型;2:左箕;3:右箕;4:斗）"))
      t.column("VICE_PATTERN",SmallintType,Limit(1),Nullable,Comment("副纹型（0:不确定;1:弓型;2:左箕;3:右箕;4:斗）"))
      t.column("GATHER_DATA",BlobType,Limit(4000),NotNull,Comment("图像数据"))
      t.column("SEQ",BigintType,Limit(22),Nullable,Comment("8.0数据同步用"))
      t.column("FINGER_DATA_NOSQL_ID",VarcharType,Limit(10),Nullable,Comment("指纹数据nosql存储id"))
      t.column("PARTITION_CITYCODE",VarcharType,Limit(8),Nullable,Comment("区域分区"))
    }
    addIndex("GAFIS_GATHER_FINGER",Array[String]("SEQ"),Name("GAFIS_GATHER_FINGER_IDX_01"))
    addIndex("GAFIS_GATHER_FINGER",Array[String]("PERSON_ID"),Name("GAFIS_GATHER_FINGER_IDX_02"))
    createTable("GAFIS_GATHER_FLOW",Comment("采集流程记录")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull)
      t.column("PERSON_ID",VarcharType,Limit(32),Nullable,Comment("人员ID"))
      t.column("GATHER_STATUS",BigintType,Limit(22),Nullable,Comment("采集状态（0：未采集，1：已采集）"))
      t.column("GATHER_DATE",TimestampType,Limit(7),Nullable,Comment("采集时间（精确到秒）"))
      t.column("GATHERER_ID",VarcharType,Limit(32),Nullable,Comment("采集人ID"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("采集次序"))
      t.column("GATHER_NODE_ID",VarcharType,Limit(32),Nullable,Comment("采集节点ID"))
      t.column("IS_SKIP",BigintType,Limit(22),Nullable,Comment("是否可跳过"))
      t.column("SKIP_REASON",VarcharType,Limit(1000),Nullable,Comment("跳过原因"))
      t.column("SKIP_OPERATOR",VarcharType,Limit(32),Nullable,Comment("跳过人"))
      t.column("SKIP_TIME",TimestampType,Limit(7),Nullable,Comment("跳过时间"))
    }
    createTable("GAFIS_GATHER_IDCARD",Comment("人员身份证信息表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull)
      t.column("PERSONID",VarcharType,Limit(23),Nullable,Comment("人员编号"))
      t.column("FGP_CODE",VarcharType,Limit(20),Nullable,Comment("数据类型(字典)"))
      t.column("GATHER_DATA",BlobType,Limit(4000),Nullable,Comment("身份证数据"))
      t.column("INPUTPSN",VarcharType,Limit(32),Nullable,Comment("记录创建人ID"))
      t.column("INPUTTIME",TimestampType,Limit(7),Nullable,Comment("记录创建时间"))
      t.column("MODIFIEDPSN",VarcharType,Limit(32),Nullable,Comment("记录更新人ID"))
      t.column("MODIFIEDTIME",TimestampType,Limit(7),Nullable,Comment("记录更新时间"))
      t.column("DELETAG",VarcharType,Limit(1),Nullable,Comment("删除标志"))
      t.column("GATHERDATANOSQLID",VarcharType,Limit(10),Nullable,Comment("身份证NOSQLID"))
    }
    createTable("GAFIS_GATHER_NODE",Comment("采集节点配置表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull,Comment("序号"))
      t.column("NODE_CODE",VarcharType,Limit(20),Nullable,Comment("节点编号"))
      t.column("NODE_NAME",VarcharType,Limit(50),Nullable,Comment("节点名称"))
      t.column("NODE_REQUEST",VarcharType,Limit(200),NotNull,Comment("节点请求"))
      t.column("DELETE_FLAG",BigintType,Limit(22),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("CREATE_USER_ID",VarcharType,Limit(50),NotNull,Comment("记录创建人ID"))
      t.column("CREATE_DATETIME",TimestampType,Limit(7),NotNull,Comment("记录创建时间"))
      t.column("UPDATE_USER_ID",VarcharType,Limit(50),Nullable,Comment("记录更新人ID"))
      t.column("UPDATE_DATETIME",TimestampType,Limit(7),Nullable,Comment("记录更新时间"))
      t.column("NODE_IMG",VarcharType,Limit(20),Nullable,Comment("节点图片"))
    }
    createTable("GAFIS_GATHER_OCX_VERSION",Comment("控件版本信息")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull,Comment("主键"))
      t.column("NAME",VarcharType,Limit(30),Nullable,Comment("控件名称"))
      t.column("TYPE",VarcharType,Limit(2),Nullable,Comment("控件类型：1：活体采集指纹，2：扫描捺印"))
      t.column("VERSION",VarcharType,Limit(10),Nullable,Comment("版本号"))
      t.column("REMARK",VarcharType,Limit(300),Nullable,Comment("备注"))
      t.column("CREATE_DATETIME",TimestampType,Limit(7),Nullable,Comment("创建时间"))
      t.column("DELETAG",VarcharType,Limit(1),Nullable,Comment("删除标志"))
    }
    createTable("GAFIS_GATHER_PALM",Comment("采集掌纹表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull)
      t.column("PERSON_ID",VarcharType,Limit(32),Nullable,Comment("人员ID"))
      t.column("FGP",SmallintType,Limit(2),NotNull,Comment("采集部位(字典)"))
      t.column("GROUP_ID",SmallintType,Limit(1),Nullable,Comment("0:特征;1:许公望压缩;3:JPG;4:纹线"))
      t.column("LOBTYPE",SmallintType,Limit(1),NotNull,Comment("1:数据;2特征n"))
      t.column("GATHER_DATA",BlobType,Limit(4000),NotNull,Comment("图像数据"))
      t.column("INPUTPSN",VarcharType,Limit(32),Nullable,Comment("记录创建人ID"))
      t.column("INPUTTIME",TimestampType,Limit(7),NotNull,Comment("记录创建时间"))
      t.column("MODIFIEDPSN",VarcharType,Limit(32),Nullable,Comment("记录更新人ID"))
      t.column("MODIFIEDTIME",TimestampType,Limit(7),Nullable,Comment("记录更新时间"))
      t.column("SEQ",BigintType,Limit(22),Nullable,Comment("8.0数据同步用"))
      t.column("PALM_DATA_NOSQL_ID",VarcharType,Limit(10),Nullable,Comment("掌纹数据nosql存储id"))
    }
    createTable("GAFIS_GATHER_PERSON_PHOTO"){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull)
      t.column("PERSONID",VarcharType,Limit(32),Nullable,Comment("人员ID"))
      t.column("PHOTO_CODE",VarcharType,Limit(10),NotNull,Comment("图片ID"))
      t.column("PHOTO_DATA",BlobType,Limit(4000),NotNull,Comment("图片数据"))
      t.column("PHOTO_ORG",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("INPUTPSN",VarcharType,Limit(32),Nullable,Comment("记录创建人"))
      t.column("INPUTTIME",TimestampType,Limit(7),NotNull,Comment("记录创建时间"))
      t.column("MODIFIEDPSN",VarcharType,Limit(32),Nullable,Comment("记录更新人"))
      t.column("MODIFIEDTIME",TimestampType,Limit(7),Nullable,Comment("记录更新时间"))
      t.column("COMMENTS",VarcharType,Limit(1000),Nullable,Comment("备注"))
    }
    createTable("GAFIS_GATHER_PHONE",Comment("人员电话表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull)
      t.column("PERSONID",VarcharType,Limit(23),Nullable,Comment("指纹编号"))
      t.column("PHONE_TYPE_CODE",VarcharType,Limit(1),Nullable,Comment("电话类型(字典)"))
      t.column("PHONE_NUMBER",VarcharType,Limit(60),Nullable,Comment("电话号码"))
      t.column("INPUTPSN",VarcharType,Limit(32),Nullable,Comment("记录创建人ID"))
      t.column("INPUTTIME",TimestampType,Limit(7),Nullable,Comment("记录创建时间"))
      t.column("MODIFIEDPSN",VarcharType,Limit(32),Nullable,Comment("记录更新人ID"))
      t.column("MODIFIEDTIME",TimestampType,Limit(7),Nullable,Comment("记录更新时间"))
      t.column("DELETAG",VarcharType,Limit(1),Nullable,Comment("删除标志"))
      t.column("AREANUMBER",VarcharType,Limit(10),Nullable,Comment("区域编号"))
      t.column("USEME",VarcharType,Limit(2),Nullable,Comment("用途"))
    }
    createTable("GAFIS_GATHER_PORTRAIT",Comment("采集人像表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull)
      t.column("PERSONID",VarcharType,Limit(32),Nullable,Comment("人员ID"))
      t.column("FGP",VarcharType,Limit(1),NotNull,Comment("采集部位(字典)正面、左侧、右侧"))
      t.column("GATHER_DATA",BlobType,Limit(4000),NotNull,Comment("图像数据"))
      t.column("INPUTPSN",VarcharType,Limit(32),Nullable,Comment("记录创建人ID"))
      t.column("INPUTTIME",TimestampType,Limit(7),NotNull,Comment("记录创建时间"))
      t.column("MODIFIEDPSN",VarcharType,Limit(32),Nullable,Comment("记录更新人ID"))
      t.column("MODIFIEDTIME",TimestampType,Limit(7),Nullable,Comment("记录更新时间"))
      t.column("DELETAG",VarcharType,Limit(1),Nullable,Comment("删除标志"))
      t.column("GATHERDATANOSQLID",VarcharType,Limit(10),Nullable,Comment("人像NOSQLID"))
    }
    createTable("GAFIS_GATHER_RESUME",Comment("人员简历表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull)
      t.column("PERSONID",VarcharType,Limit(23),Nullable,Comment("指纹编号"))
      t.column("BEGINDATE",TimestampType,Limit(7),Nullable,Comment("开始日期"))
      t.column("ENDDATE",TimestampType,Limit(7),Nullable,Comment("终止日期"))
      t.column("DESCRIBE",VarcharType,Limit(1500),Nullable,Comment("具体描述"))
      t.column("INPUTPSN",VarcharType,Limit(32),Nullable,Comment("记录创建人ID"))
      t.column("INPUTTIME",TimestampType,Limit(7),Nullable,Comment("记录创建时间"))
      t.column("MODIFIEDPSN",VarcharType,Limit(32),Nullable,Comment("记录更新人ID"))
      t.column("MODIFIEDTIME",TimestampType,Limit(7),Nullable,Comment("记录更新时间"))
      t.column("DELETAG",VarcharType,Limit(1),Nullable,Comment("删除标志"))
    }
    createTable("GAFIS_GATHER_SPECIALTY",Comment("人员专长表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull)
      t.column("PERSONID",VarcharType,Limit(23),Nullable,Comment("指纹编号"))
      t.column("SPECIALTY_CODE",VarcharType,Limit(2),Nullable,Comment("专长(字典)"))
      t.column("INPUTPSN",VarcharType,Limit(32),Nullable,Comment("记录创建人ID"))
      t.column("INPUTTIME",TimestampType,Limit(7),Nullable,Comment("记录创建时间"))
      t.column("MODIFIEDPSN",VarcharType,Limit(32),Nullable,Comment("记录更新人ID"))
      t.column("MODIFIEDTIME",TimestampType,Limit(7),Nullable,Comment("记录更新时间"))
      t.column("DELETAG",VarcharType,Limit(1),Nullable,Comment("删除标志"))
    }
    createTable("GAFIS_GATHER_TYPE",Comment("人员类型表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull,Comment("序号"))
      t.column("TYPE_NAME",VarcharType,Limit(60),NotNull,Comment("采集类型名称"))
      t.column("DELETE_FLAG",BigintType,Limit(22),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("CREATE_USER_ID",VarcharType,Limit(50),NotNull,Comment("记录创建人姓名"))
      t.column("CREATE_DATETIME",TimestampType,Limit(7),NotNull,Comment("记录创建时间"))
      t.column("UPDATE_USER_ID",VarcharType,Limit(50),Nullable,Comment("记录更新人姓名"))
      t.column("UPDATE_DATETIME",TimestampType,Limit(7),Nullable,Comment("记录更新时间"))
      t.column("MENU_ID",VarcharType,Limit(10),Nullable,Comment("关联菜单"))
      t.column("PERSON_CATEGORY",VarcharType,Limit(3),Nullable,Comment("人员类型"))
      t.column("GATHER_CATEGORY",VarcharType,Limit(1),Nullable,Comment("采集类别"))
      t.column("PARENT_ID",VarcharType,Limit(32),Nullable,Comment("父类ID"))
      t.column("ISCHILDREN",VarcharType,Limit(1),Nullable,Comment("是否有子节点:1表示有,0表示无"))
      t.column("RULE_ID",VarcharType,Limit(32),Nullable,Comment("人员编号规则ID"))
    }
    createTable("GAFIS_GATHER_TYPE_NODE",Comment("人员类型采集节点表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull,Comment("序号"))
      t.column("TYPE_ID",VarcharType,Limit(32),NotNull,Comment("所属人员类型"))
      t.column("NODE_ID",VarcharType,Limit(32),Nullable,Comment("节点编号"))
      t.column("NODE_ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("IS_SKIP",SmallintType,Limit(1),Nullable,Comment("是否可跳过"))
      t.column("DEPART_ID",VarcharType,Limit(32),Nullable,Comment("所属部门编号"))
    }
    createTable("GAFIS_GATHER_TYPE_NODE_FIELD",Comment("采集类型节点字段表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull)
      t.column("TYPE_ID",VarcharType,Limit(32),Nullable,Comment("采集类型ID"))
      t.column("NODE_ID",VarcharType,Limit(32),Nullable,Comment("节点编号"))
      t.column("FIELD_ID",VarcharType,Limit(32),Nullable,Comment("字段ID"))
      t.column("REQUIRED",SmallintType,Limit(1),Nullable,Comment("是否必填(0:非必填,1:必填)"))
      t.column("DEPART_ID",VarcharType,Limit(32),Nullable,Comment("部门编号"))
    }
    createTable("GAFIS_GATHER_VIRTUAL",Comment("人员虚拟身份表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull)
      t.column("PERSONID",VarcharType,Limit(23),Nullable,Comment("指纹编号"))
      t.column("VIRTUAL_TYPE_CODE",VarcharType,Limit(2),Nullable,Comment("虚拟身份类型(字典)"))
      t.column("VIRTUAL_NUMBER",VarcharType,Limit(30),Nullable,Comment("虚拟身份号码"))
      t.column("NICKNAME",VarcharType,Limit(60),Nullable,Comment("网名"))
      t.column("INPUTPSN",VarcharType,Limit(32),Nullable,Comment("记录创建人ID"))
      t.column("INPUTTIME",TimestampType,Limit(7),Nullable,Comment("记录创建时间"))
      t.column("MODIFIEDPSN",VarcharType,Limit(32),Nullable,Comment("记录更新人ID"))
      t.column("MODIFIEDTIME",TimestampType,Limit(7),Nullable,Comment("记录更新时间"))
      t.column("DELETAG",VarcharType,Limit(1),Nullable,Comment("删除标志"))
    }
    createTable("GAFIS_LOGIC_DB"){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull,Comment("主键ID"))
      t.column("LOGIC_CODE",VarcharType,Limit(32),Nullable,Comment("编号或代码号"))
      t.column("LOGIC_NAME",VarcharType,Limit(32),Nullable,Comment("名称"))
      t.column("LOGIC_CATEGORY",VarcharType,Limit(1),Nullable,Comment("分库类型，0:捺印分库,  1:案件分库"))
      t.column("LOGIC_DELTAG",VarcharType,Limit(1),Nullable,Comment("禁启用标识，0: 禁用，1:启用"))
      t.column("LOGIC_REMARK",VarcharType,Limit(60),Nullable,Comment("备注"))
    }
    createTable("GAFIS_LOGIC_DB_CASE",Comment("案件逻辑分库中间表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull,Comment("主键"))
      t.column("LOGIC_DB_PKID",VarcharType,Limit(32),Nullable,Comment("逻辑分库主键"))
      t.column("CASE_PKID",VarcharType,Limit(32),Nullable,Comment("案件主键"))
    }
    createTable("GAFIS_LOGIC_DB_FINGERPRINT",Comment("排印逻辑分库中间表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull,Comment("主键"))
      t.column("LOGIC_DB_PKID",VarcharType,Limit(32),Nullable,Comment("逻辑分库主键"))
      t.column("FINGERPRINT_PKID",VarcharType,Limit(32),Nullable,Comment("捺印主键"))
    }
    createTable("GAFIS_NORMALQUERY_QUERYQUE",Comment("查询表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull,Comment("序号"))
      t.column("ORA_SID",BigintType,Limit(15),Nullable,Comment("任务号,唯一序列"))
      t.column("KEYID",VarcharType,Limit(25),Nullable,Comment("卡号"))
      t.column("QUERYTYPE",SmallintType,Limit(3),Nullable,Comment("查询类型:捺印查重(TT):0,捺印倒查(TL):1,现场查案(LT):2,现场串查(LL):3"))
      t.column("STATUS",SmallintType,Limit(3),Nullable,Comment("查询状态:-1未知状态,0等待比对,1正在比对,2等待核查(比对完成),3错误数据"))
      t.column("PRIORITY",SmallintType,Limit(3),Nullable,Comment("查询优先级:最低0,低1,正常2,稍高3,高4,最高5"))
      t.column("HITPOSSIBILITY",SmallintType,Limit(3),Nullable,Comment("查中概率"))
      t.column("VERIFYRESULT",SmallintType,Limit(3),Nullable,Comment("比中状态:0没有结果(空白),99没有比中,98比中"))
      t.column("FLAG",SmallintType,Limit(3),Nullable,Comment("查询标记:平面指纹查询 0x80,带文本查询 0x04,掌纹查询 0x02,滚动指纹查询 0x01,平面指纹查询+带文本查询 0x80+0x04=0x84 ...."))
      t.column("FLAGC",SmallintType,Limit(3),Nullable,Comment("紧急状态:紧急(>32),正常(＝32 and null)"))
      t.column("FLAGD",SmallintType,Limit(3),Nullable)
      t.column("FLAGE",SmallintType,Default("0"),Limit(3),Nullable,Comment("快速tt查询标识"))
      t.column("FLAGG",SmallintType,Limit(3),Nullable,Comment("TT自动认定使用的标志"))
      t.column("QRYCONDITION",BlobType,Limit(4000),Nullable,Comment("查询条件(比对参数)"))
      t.column("MIC",BlobType,Limit(4000),Nullable,Comment("特征"))
      t.column("TEXTSQL",ClobType,Limit(4000),Nullable,Comment("文本查询条件(XML格式)"))
      t.column("CANDHEAD",BlobType,Limit(4000),Nullable,Comment("候选列表头"))
      t.column("CANDLIST",BlobType,Limit(4000),Nullable,Comment("候选列表"))
      t.column("TIMEUSED",IntegerType,Limit(10),Nullable,Comment("耗时(秒)"))
      t.column("MAXCANDNUM",IntegerType,Limit(10),Nullable,Comment("最大候选个数"))
      t.column("CURCANDNUM",IntegerType,Limit(10),Nullable,Comment("当前候选个数"))
      t.column("MINSCORE",IntegerType,Limit(10),Nullable,Comment("候选队列最小得分"))
      t.column("STARTKEY1",VarcharType,Limit(32),Nullable,Comment("条码区间1:卡号"))
      t.column("ENDKEY1",VarcharType,Limit(32),Nullable,Comment("条码区间1"))
      t.column("STARTKEY2",VarcharType,Limit(32),Nullable,Comment("条码区间2:卡号"))
      t.column("ENDKEY2",VarcharType,Limit(32),Nullable,Comment("条码区间2"))
      t.column("USERNAME",VarcharType,Limit(32),Nullable,Comment("查询提交者"))
      t.column("USERUNITCODE",VarcharType,Limit(12),Nullable,Comment("查询提交者单位代码"))
      t.column("FINISHTIME",TimestampType,Limit(7),Nullable,Comment("查询完成时间"))
      t.column("COMPUTERIP",VarcharType,Limit(32),Nullable,Comment("提交机器IP"))
      t.column("COMPUTERNAME",VarcharType,Limit(32),Nullable,Comment("提交机器名称"))
      t.column("ORACOMMENT",ClobType,Limit(4000),Nullable,Comment("备注"))
      t.column("MAXSCORE",BigintType,Limit(22),Nullable,Comment("候选队列最大得分"))
      t.column("CREATETIME",TimestampType,Limit(7),Nullable,Comment("创建时间"))
      t.column("BEGINTIME",TimestampType,Limit(7),Nullable,Comment("查询发起时间"))
      t.column("DELETAG",VarcharType,Limit(1),Nullable,Comment("删除标志"))
      t.column("USERID",VarcharType,Limit(32),Nullable,Comment("查询提交者ＩＤ"))
      t.column("SUBMITTSYSTEM",VarcharType,Limit(32),Nullable,Comment("发比对系统"))
      t.column("PRIORITYNEW",SmallintType,Limit(3),Nullable,Comment("8.0的优先级"))
      t.column("HANDLERESULT",SmallintType,Limit(3),Nullable,Comment("处理状态（0：待处理；1：已处理）"))
      t.column("QRYCONDITION_NOSQL_ID",VarcharType,Limit(10),Nullable,Comment("查询条件(比对参数)nosql存储id"))
      t.column("MIC_NOSQL_ID",VarcharType,Limit(10),Nullable,Comment("特征nosql存储id"))
      t.column("CANDHEAD_NOSQL_ID",VarcharType,Limit(10),Nullable,Comment("候选列表头nosql存储id"))
      t.column("CANDLIST_NOSQL_ID",VarcharType,Limit(10),Nullable,Comment("候选列表nosql存储id"))
      t.column("TIME_ELAPSED",BigintType,Limit(22),Nullable,Comment("比对消耗时间(单位：毫秒)"))
      t.column("RECORD_NUM_MATCHED",BigintType,Limit(22),Nullable,Comment("总共参入比对的记录数 (单位为:卡、案件)"))
      t.column("MATCH_PROGRESS",BigintType,Limit(22),Nullable,Comment("比对进度，(0,100)区间的数字"))
    }
    createTable("GAFIS_PERSON",Comment("采集人员信息主表")){ t=>
      t.column("PERSONID",VarcharType,Limit(23),NotNull,Comment("指纹编号"),PrimaryKey)
      t.column("IDCARDNO",VarcharType,Limit(18),Nullable,Comment("身份证号码"))
      t.column("NAME",VarcharType,Limit(60),Nullable,Comment("姓名"))
      t.column("SPELLNAME",VarcharType,Limit(60),Nullable,Comment("姓名拼音"))
      t.column("USEDNAME",VarcharType,Limit(60),Nullable,Comment("曾用名"))
      t.column("USEDSPELL",VarcharType,Limit(60),Nullable,Comment("曾用名拼音"))
      t.column("ALIASNAME",VarcharType,Limit(60),Nullable,Comment("别名绰号"))
      t.column("ALIASSPELL",VarcharType,Limit(60),Nullable,Comment("别名绰号拼音"))
      t.column("SEX_CODE",VarcharType,Limit(1),Nullable,Comment("性别(字典)"))
      t.column("NATIVEPLACE_CODE",VarcharType,Limit(6),Nullable,Comment("籍贯国籍(字典)"))
      t.column("NATION_CODE",VarcharType,Limit(2),Nullable,Comment("民族(字典)"))
      t.column("IFMARRY_CODE",VarcharType,Limit(2),Nullable,Comment("婚否(字典)"))
      t.column("TONE_CODE",VarcharType,Limit(6),Nullable,Comment("口音(行政区划)"))
      t.column("TONE",VarcharType,Limit(60),Nullable,Comment("口音描述"))
      t.column("BIRTHDAYST",TimestampType,Limit(7),Nullable,Comment("出生日期起"))
      t.column("BIRTHDAYED",TimestampType,Limit(7),Nullable,Comment("出生日期止"))
      t.column("BIRTH_CODE",VarcharType,Limit(6),Nullable,Comment("出生地代码(区域)"))
      t.column("BIRTH_STREET",VarcharType,Limit(60),Nullable,Comment("出生地乡镇/街道/社区"))
      t.column("BIRTHDETAIL",VarcharType,Limit(90),Nullable,Comment("出生地详细住址"))
      t.column("DOOR",VarcharType,Limit(6),Nullable,Comment("户籍地代码(区域)"))
      t.column("DOOR_STREET",VarcharType,Limit(60),Nullable,Comment("户籍地-乡镇/街道/社区"))
      t.column("DOORDETAIL",VarcharType,Limit(90),Nullable,Comment("户籍地详细住址"))
      t.column("ADDRESS",VarcharType,Limit(6),Nullable)
      t.column("ADDRESS_STREET",VarcharType,Limit(60),Nullable)
      t.column("ADDRESSDETAIL",VarcharType,Limit(90),Nullable)
      t.column("CULTURE_CODE",VarcharType,Limit(2),Nullable,Comment("文化程度(字典)"))
      t.column("SOURCEINCOME_CODE",VarcharType,Limit(2),Nullable,Comment("经济来源(字典)"))
      t.column("FAITH_CODE",VarcharType,Limit(2),Nullable,Comment("宗教信仰(字典)"))
      t.column("HAVEEMPLOYMENT",VarcharType,Limit(1),Nullable,Comment("是否有固定职业"))
      t.column("JOB_CODE",VarcharType,Limit(4),Nullable,Comment("职业(字典)"))
      t.column("HEADSHIP",VarcharType,Limit(60),Nullable,Comment("职务"))
      t.column("EMPLOYUNIT",VarcharType,Limit(60),Nullable,Comment("工作单位"))
      t.column("EMPLOYADDRESS",VarcharType,Limit(90),Nullable)
      t.column("OTHERSPECIALTY",VarcharType,Limit(300),Nullable,Comment("其它专长"))
      t.column("SPECIALIDENTITY_CODE",VarcharType,Limit(4),Nullable,Comment("特殊身份(字典)"))
      t.column("POLITICS_CODE",VarcharType,Limit(3),Nullable,Comment("政治面貌(字典)"))
      t.column("ISTRANSIENTPOP",VarcharType,Limit(1),Nullable,Comment("是否暂住人口"))
      t.column("ISTEMPREGIST",VarcharType,Limit(1),Nullable,Comment("是否暂住登记"))
      t.column("HAVEPERMIT",VarcharType,Limit(1),Nullable,Comment("是否办理居住证"))
      t.column("HAVERESIDENCE",VarcharType,Limit(1),Nullable,Comment("是否有固定住所"))
      t.column("ISSERVICE",VarcharType,Limit(1),Nullable,Comment("是否服兵役"))
      t.column("SPECIALGROUP_CODE",VarcharType,Limit(1),Nullable,Comment("特殊人群(字典)"))
      t.column("HAVESEPARATION",VarcharType,Limit(1),Nullable,Comment("父母是否有离异经历"))
      t.column("ISMIGRANTWORKER",VarcharType,Limit(1),Nullable,Comment("是否农民工子女"))
      t.column("NAMEOFSCHOOL",VarcharType,Limit(90),Nullable,Comment("就读学校名称"))
      t.column("ISTRAINING",VarcharType,Limit(1),Nullable,Comment("是否参加职业培训"))
      t.column("HAVECERTIFICATE",VarcharType,Limit(1),Nullable,Comment("是否取得职业资格证"))
      t.column("STATUREST",SmallintType,Limit(3),Nullable,Comment("身高(cm)"))
      t.column("AVOIRDUPOIS",SmallintType,Limit(4),Nullable,Comment("体重(kg)"))
      t.column("FOOTSIZE",SmallintType,Limit(3),Nullable,Comment("赤足长(cm)"))
      t.column("SHOELENGTH",SmallintType,Limit(3),Nullable,Comment("鞋长(cm)"))
      t.column("BODILYFORM_CODE",VarcharType,Limit(4),Nullable,Comment("体型(字典)"))
      t.column("FACEFORM_CODE",VarcharType,Limit(4),Nullable,Comment("脸型(字典)"))
      t.column("ISEYEGLASS",VarcharType,Limit(1),Nullable,Comment("是否佩戴眼镜"))
      t.column("SHOESIZE",SmallintType,Limit(3),Nullable,Comment("鞋号（码）"))
      t.column("BLOODTYPE_CODE",VarcharType,Limit(1),Nullable,Comment("血型(字典)"))
      t.column("GATHER_ORG_CODE",VarcharType,Limit(12),Nullable,Comment("创建单位编码"))
      t.column("IPADDRESS",VarcharType,Limit(15),Nullable)
      t.column("GATHERER_ID",VarcharType,Limit(32),Nullable,Comment("采集人ID"))
      t.column("GATHER_DATE",TimestampType,Limit(7),Nullable,Comment("采集时间"))
      t.column("GATHER_TYPE_ID",VarcharType,Limit(32),Nullable,Comment("所属采集类型ID"))
      t.column("STATUS",VarcharType,Limit(2),Nullable,Comment("当前状态"))
      t.column("ISFINGERREPEAT",VarcharType,Limit(1),Nullable,Comment("指纹是否有重复"))
      t.column("FINGERREPEATNO",VarcharType,Limit(32),Nullable,Comment("重卡编号"))
      t.column("TASK_SOURCE",VarcharType,Limit(2),Nullable,Comment("任务来源"))
      t.column("RECEIVE_TIME",TimestampType,Limit(7),Nullable,Comment("任务接收时间"))
      t.column("ISRETURN",VarcharType,Limit(1),Nullable,Comment("是否已回复"))
      t.column("RETURN_TIME",TimestampType,Limit(7),Nullable,Comment("回复时间"))
      t.column("ANNEX",VarcharType,Limit(1500),Nullable,Comment("必填项跳过原因"))
      t.column("INPUTPSN",VarcharType,Limit(32),Nullable,Comment("记录创建人ID"))
      t.column("INPUTTIME",TimestampType,Limit(7),Nullable,Comment("记录创建时间"))
      t.column("MODIFIEDPSN",VarcharType,Limit(32),Nullable,Comment("记录更新人ID"))
      t.column("MODIFIEDTIME",TimestampType,Limit(7),Nullable,Comment("记录更新时间"))
      t.column("DELETAG",VarcharType,Limit(1),Nullable,Comment("删除标志"))
      t.column("SCHEDULE",VarcharType,Limit(10),Nullable,Comment("采集进度"))
      t.column("APPROVAL",VarcharType,Limit(1),Nullable,Comment("审核状态:1、待审核;2、审核通过;3、审核失败;"))
      t.column("DNA_CODE",VarcharType,Limit(30),Nullable,Comment("DNA实验室编号"))
      t.column("GATHER_CATEGORY",VarcharType,Limit(1),Nullable,Comment("采集类别0:应采,1:必采,2:可采"))
      t.column("PERSON_CATEGORY",VarcharType,Limit(3),Nullable,Comment("人员类型"))
      t.column("AUDITOR",VarcharType,Limit(32),Nullable,Comment("审核人"))
      t.column("AUDITEDTIME",TimestampType,Limit(7),Nullable,Comment("接受任务时间"))
      t.column("ISREGATHER",VarcharType,Limit(1),Nullable)
      t.column("GATHER_FINGER_MODE",VarcharType,Limit(1),Nullable,Comment("指纹采集方式，0：活体指纹采集，1：扫描捺印卡片采集"))
      t.column("CASE_NAME",VarcharType,Limit(100),Nullable,Comment("案件名称"))
      t.column("CASE_CLASSES",VarcharType,Limit(6),Nullable,Comment("案件类别"))
      t.column("REASON",VarcharType,Limit(6),Nullable,Comment("案由"))
      t.column("GATHER_FINGER_NUM",BigintType,Limit(22),Nullable,Comment("指纹采集次数"))
      t.column("FINGER_REMARK",VarcharType,Limit(300),Nullable,Comment("指纹信息备注"))
      t.column("DEPRTMAC",VarcharType,Limit(100),Nullable,Comment("记录单位的设备mac"))
      t.column("GATHERDEPARTCODE",VarcharType,Limit(50),Nullable,Comment("采集单位"))
      t.column("GATHERUSERID",VarcharType,Limit(50),Nullable,Comment("采集人"))
      t.column("GATHER_FINGER_TIME",TimestampType,Limit(7),Nullable,Comment("指纹采集时间"))
      t.column("IS_SEND_TL",BigintType,Limit(22),Nullable,Comment("是否发生TL查询"))
      t.column("CASE_BRIEF_CONTENTS",VarcharType,Limit(1500),Nullable,Comment("简要案情"))
      t.column("PUSH_STATUS",VarcharType,Limit(1),Nullable,Comment("案事件推送状态"))
      t.column("PUSH_DATE",TimestampType,Limit(7),Nullable,Comment("案事件推送时间"))
      t.column("REMARK",VarcharType,Limit(2000),Nullable,Comment("备注或抓获情况"))
      t.column("DATA_SOURCES",SmallintType,Limit(1),Nullable)
      t.column("FINGERSHOW_STATUS",SmallintType,Limit(1),Nullable,Comment("指纹系统显示标识(0:不显示1:显示。显示情况：1):来自标采系统且有指纹的;2):来自指纹系统;3):来自协查)"))
      t.column("CITY_CODE",CharType,Limit(4),Nullable,Comment("区域标识(区域的前四位)"))
      t.column("DELAY_DEADLINE",TimestampType,Limit(7),Nullable,Comment("案事件系统数据调取截止时间（默认为采集时间）"))
      t.column("FPT_GATHER_DEPART_CODE",VarcharType,Limit(12),Nullable,Comment("FPT捺印单位代码"))
      t.column("FPT_GATHER_DEPART_NAME",VarcharType,Limit(90),Nullable,Comment("FPT捺印单位名称"))
      t.column("SID",BigintType,Limit(22),Nullable,Comment("SID比对唯一标识"))
      t.column("BLOW_CODE",VarcharType,Limit(6),Nullable,Comment("打击处代码(区域)"))
      t.column("BLOW_STREET",VarcharType,Limit(60),Nullable,Comment("打击处乡镇/街道/社区"))
      t.column("BLOW_DETAIL",VarcharType,Limit(90),Nullable,Comment("打击处详细地址"))
      t.column("BLOW_LONGITUDE",VarcharType,Limit(30),Nullable,Comment("打击处经度"))
      t.column("BLOW_LATITUDE",VarcharType,Limit(30),Nullable,Comment("打击处纬度"))
      t.column("BLOW_EASTWEST",CharType,Limit(1),Nullable,Comment("东西经度"))
      t.column("BLOW_NORTHSOUTH",CharType,Limit(1),Nullable,Comment("南北纬度"))
      t.column("SEQ",BigintType,Limit(22),Nullable,Comment("8.0数据同步用"))
      t.column("CARDID",VarcharType,Limit(23),Nullable,Comment("捺印卡号"))
      t.column("RECORDMARK",CharType,Limit(1),Nullable,Comment("前科库标识 1：有；2：无"))
      t.column("RECORDSITUATION",VarcharType,Limit(3072),Nullable,Comment("前科劣迹情况"))
      t.column("VALID_DATE",TimestampType,Limit(7),Nullable,Comment("有效期限"))
      t.column("ARRIVE_LOCAL_DATE",TimestampType,Limit(7),Nullable,Comment("抵达本地日期"))
      t.column("LEAVE_LOCAL_DATE",TimestampType,Limit(7),Nullable,Comment("离开本地日期"))
      t.column("DB_SOURCE",VarcharType,Limit(30),Nullable,Comment("数据来源"))
      t.column("DB_SOURCE_DIS",VarcharType,Limit(100),Nullable,Comment("数据来源描述"))
      t.column("JOB_DES",VarcharType,Limit(100),Nullable,Comment("职业(本地活动目的)"))
      t.column("IS_XJSSMZ",CharType,Limit(1),Nullable,Comment("是否新疆少数民族"))
      t.column("PASSPORT_NUM",VarcharType,Limit(30),Nullable,Comment("护照号码"))
      t.column("COUNTRY_CODE",VarcharType,Limit(2),Nullable,Comment("国家码"))
      t.column("FOREIGN_NAME",VarcharType,Limit(100),Nullable,Comment("外国姓名"))
      t.column("PASSPORT_VALID_DATE",TimestampType,Limit(7),Nullable,Comment("护照有效日期"))
      t.column("VISA_PLACE",VarcharType,Limit(100),Nullable,Comment("签发地点"))
      t.column("PASSPORT_TYPE",VarcharType,Limit(3),Nullable,Comment("护照类型"))
      t.column("VISA_DATE",TimestampType,Limit(7),Nullable,Comment("签发日期"))
      t.column("ASSIST_LEVEL",VarcharType,Limit(1),Nullable,Comment("协查级别"))
      t.column("ASSIST_BONUS",VarcharType,Limit(6),Nullable,Comment("奖金"))
      t.column("ASSIST_PURPOSE",VarcharType,Limit(5),Nullable,Comment("协查目的"))
      t.column("ASSIST_REF_PERSON",VarcharType,Limit(23),Nullable,Comment("关联人员编号"))
      t.column("ASSIST_REF_CASE",VarcharType,Limit(23),Nullable,Comment("关联案件编号"))
      t.column("ASSIST_VALID_DATE",VarcharType,Limit(1),Nullable,Comment("协查有效时间(1:一个月;2:三个月;3:六个月;4:长期)"))
      t.column("ASSIST_EXPLAIN",VarcharType,Limit(512),Nullable,Comment("协查请求说明"))
      t.column("ASSIST_DEPT_CODE",VarcharType,Limit(12),Nullable,Comment("协查单位代码"))
      t.column("ASSIST_DEPT_NAME",VarcharType,Limit(70),Nullable,Comment("协查单位名称"))
      t.column("ASSIST_DATE",VarcharType,Limit(8),Nullable,Comment("协查日期(格式:YYYYMMDD)"))
      t.column("ASSIST_CONTACTS",VarcharType,Limit(30),Nullable,Comment("联系人"))
      t.column("ASSIST_NUMBER",VarcharType,Limit(40),Nullable,Comment("联系电话"))
      t.column("ASSIST_APPROVAL",VarcharType,Limit(30),Nullable,Comment("审批人"))
      t.column("ASSIST_SIGN",VarcharType,Limit(1),Nullable,Comment("协查标识(1:协查;0:不协查)"))
      t.column("GATHERDEPARTNAME",VarcharType,Limit(100),Nullable,Comment("采集单位名称"))
      t.column("GATHERUSERNAME",VarcharType,Limit(100),Nullable,Comment("采集人name"))
      t.column("CONTRCAPTURE_CODE",VarcharType,Limit(1),Nullable,Comment("辑控抓获标识(字典)"))
    }
    createTable("GAFIS_PERSON_ATT",Comment("人员附件")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull,Comment("图片ID"))
      t.column("IMG",BlobType,Limit(4000),Nullable,Comment("图片"))
      t.column("TYPE",CharType,Limit(2),Nullable,Comment("图片类型(1:指纹采集备注图片类型)"))
      t.column("PERSONID",VarcharType,Limit(23),Nullable,Comment("人员ID"))
      t.column("GATHERDATANOSQLID",VarcharType,Limit(10),Nullable,Comment("图片NOSQLID"))
    }
    createTable("GAFIS_PERSON_NO"){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull)
      t.column("DATETIME",TimestampType,Limit(7),Nullable,Comment("yyyyMM"))
      t.column("COUNT",BigintType,Limit(22),Nullable)
      t.column("DEPT_NO",VarcharType,Limit(32),Nullable,Comment("部门编号"))
      t.column("MISS",VarcharType,Limit(4000),Nullable,Comment("缺失的序号"))
      t.column("RULE_ID",VarcharType,Limit(32),Nullable,Comment("人员编号规则ID"))
    }
    createTable("GAFIS_PERSON_NO_RULE",Comment("人员编号规则")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull)
      t.column("RULE",VarcharType,Limit(30),Nullable)
    }
    createTable("GAFIS_QUERYQUE_COUNT",Comment("发送查询计数表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull,Comment("主键"))
      t.column("USER_ID",VarcharType,Limit(32),Nullable,Comment("用户id"))
      t.column("USED_QUERY_COUNT",SmallintType,Limit(4),Nullable,Comment("已用查询次数"))
      t.column("QUERY_TYPE",SmallintType,Limit(1),Nullable,Comment("查询类别(0查重1倒查2查案3串查)n"))
      t.column("QUERY_DATE",TimestampType,Limit(7),Nullable,Comment("查询时间"))
      t.column("REMARK",VarcharType,Limit(100),Nullable,Comment("备注"))
      t.column("QUERY_PRIORITY",SmallintType,Limit(1),Nullable,Comment("查询优先级"))
    }
    createTable("GAFIS_SCAN_CUT",Comment("切割数据自动批量发送查重记录表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull,Comment("id主键"))
      t.column("KEY_SCAN_CUT",VarcharType,Limit(32),NotNull,Comment("切割的捺印卡号"))
      t.column("REAMK",VarcharType,Limit(120),Nullable,Comment("描述"))
    }
    createTable("LOG_INFO",Comment("系统日志")){ t=>
      t.column("NUM_ID",BigintType,Limit(22),NotNull,Comment("流水号"))
      t.column("USER_ID",VarcharType,Limit(32),Nullable,Comment("用户标识"))
      t.column("ORGANIZATION",VarcharType,Limit(100),Nullable,Comment("单位"))
      t.column("USER_NAME",VarcharType,Limit(100),Nullable,Comment("用户名"))
      t.column("TERMINAL_ID",VarcharType,Limit(100),Nullable,Comment("终端标识"))
      t.column("OPERATE_TYPE",SmallintType,Limit(1),Nullable,Comment("操作类型"))
      t.column("OPERATE_TIME",TimestampType,Limit(7),Nullable,Comment("操作时间"))
      t.column("OPERATE_CONDITION",VarcharType,Limit(1000),Nullable,Comment("操作条件"))
      t.column("OPERATE_RESULT",VarcharType,Limit(1),Nullable,Comment("操作结果"))
      t.column("OPERATE_OBJECT",VarcharType,Limit(100),Nullable,Comment("操作对象"))
      t.column("UPDATE_BEFORE",VarcharType,Limit(100),Nullable,Comment("字段修改前的值"))
      t.column("UPDATE_AFTER",VarcharType,Limit(100),Nullable,Comment("字段修改后的值"))
      t.column("DEPARTNAME",VarcharType,Limit(100),Nullable,Comment("部门名称"))
    }
    createTable("SYS_AREA",Comment("行政区划")){ t=>
      t.column("AREA_CODE",VarcharType,Limit(10),NotNull,Comment("区域编码"))
      t.column("AREA_NAME",VarcharType,Limit(90),Nullable,Comment("区域名称"))
      t.column("AREA_ALIAS",VarcharType,Limit(90),Nullable,Comment("区域简称"))
      t.column("PARENT_ID",VarcharType,Limit(10),Nullable,Comment("父编码"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
      t.column("IS_LEAF",VarcharType,Limit(1),Nullable,Comment("是否是子节点"))
      t.column("AREANUMBER",VarcharType,Limit(10),Nullable,Comment("区域编号"))
      t.column("AREA_FIRST_LETTER",VarcharType,Limit(30),Nullable,Comment("区域名称首字母"))
    }
    createTable("SYS_CONTROL",Comment("控件更新管理")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull)
      t.column("VERSION",VarcharType,Limit(10),Nullable,Comment("版本"))
      t.column("UPLOAD_PERSON",VarcharType,Limit(32),Nullable,Comment("上传人"))
      t.column("UPLOAD_TIME",TimestampType,Limit(7),Nullable,Comment("上传时间"))
      t.column("CLIENT_TYPE",VarcharType,Limit(1),Nullable,Comment("客户端类型(0:控件,1:CS)"))
      t.column("FILE_PATH",VarcharType,Limit(200),Nullable,Comment("文件路径"))
      t.column("ENABLE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标识(0:禁用,1:启用)"))
      t.column("SYS_TYPE",VarcharType,Limit(1),Nullable,Comment("系统类型(0:标采 1:指纹)"))
    }
    createTable("SYS_CONTROL_LOG",Comment("控件更新日志表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull,PrimaryKey)
      t.column("IP",VarcharType,Limit(15),Nullable)
      t.column("MAC",VarcharType,Limit(50),Nullable)
      t.column("VERSION",VarcharType,Limit(10),Nullable,Comment("版本号"))
      t.column("SYS_TYPE",VarcharType,Limit(1),Nullable,Comment("客户端系统(1:指纹,0:标采)"))
      t.column("UPDATE_TIME",TimestampType,Limit(7),Nullable,Comment("更新时间"))
      t.column("STATE",VarcharType,Limit(1),Nullable,Comment("安装状态(2:失败,0:默认,1:成功)"))
    }
    createTable("SYS_DEPART",Comment("部门列表")){ t=>
      t.column("CODE",VarcharType,Limit(12),NotNull,Comment("部门编号"))
      t.column("NAME",VarcharType,Limit(200),Nullable,Comment("部门名称"))
      t.column("LEADER",VarcharType,Limit(60),Nullable,Comment("负责人"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("删除标志(-1: 删除 0:回收站(禁用) 1:在用)"))
      t.column("IS_LEAF",VarcharType,Limit(1),Nullable,Comment("是否为子节点 0:是 1：否"))
      t.column("PARENT_ID",VarcharType,Limit(12),Nullable,Comment("部门父级编码"))
      t.column("DEPT_LEVEL",VarcharType,Limit(1),Nullable,Comment("部门级别"))
      t.column("LONGITUDE",IntegerType,Limit(7),Nullable,Comment("部门单位所在位置经度"))
      t.column("LATITUDE",IntegerType,Limit(7),Nullable,Comment("部门单位所在位置纬度"))
      t.column("PHONE",VarcharType,Limit(30),Nullable,Comment("电话"))
      t.column("LONG_NAME",VarcharType,Limit(200),Nullable,Comment("部门名称全名"))
      t.column("IS_HAVE_CHAMBER",VarcharType,Limit(1),Nullable,Comment("是否有采集室 0：没有；1：有"))
      t.column("CHAMBER_TYPE",SmallintType,Limit(1),Nullable,Comment("采集室类型 0:活体；1：油墨；2：综合"))
      t.column("IS_SPECIAL",SmallintType,Limit(1),Nullable,Comment("特殊警钟（1，森林公安）"))
      t.column("INTEGRATION_TYPE",CharType,Limit(2),Nullable,Comment("一体化类型 01：无一体化设备 02：东方金指一体化设备"))
    }
    createTable("SYS_DEPART_EQUIPMENT",Comment("部门设备表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull,Comment("主键"))
      t.column("DEPART",VarcharType,Limit(12),NotNull,Comment("所属部门"))
      t.column("IP",VarcharType,Limit(15),Nullable,Comment("ip"))
      t.column("MAC",VarcharType,Limit(17),Nullable,Comment("mac"))
      t.column("INPUTPSN",VarcharType,Limit(32),NotNull,Comment("创建人"))
      t.column("INPUTTIME",TimestampType,Limit(7),Nullable,Comment("创建时间"))
      t.column("MODIFIEDPSN",VarcharType,Limit(32),Nullable,Comment("修改人"))
      t.column("MODIFIEDTIME",TimestampType,Limit(7),Nullable,Comment("修改时间"))
      t.column("DELETAG",VarcharType,Limit(1),Nullable,Comment("删除标志"))
    }
    createTable("SYS_DEPLOY",Comment("系统基本配置")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull,Comment("序号"))
      t.column("PROJECT_NAME",VarcharType,Limit(300),NotNull,Comment("系统名称"))
      t.column("CURRENT_FILE_PATH",VarcharType,Limit(100),Nullable,Comment("附件存储路径"))
      t.column("UPLOAD_IP",VarcharType,Limit(64),Nullable,Comment("上级IP"))
      t.column("UPLOAD_PORT",BigintType,Limit(22),Nullable,Comment("上级端口"))
      t.column("UPLOAD_PWD",VarcharType,Limit(64),Nullable,Comment("上报密码"))
      t.column("SYS_VERSION",VarcharType,Limit(32),Nullable,Comment("系统版本"))
      t.column("LOCAL_IP",VarcharType,Limit(64),Nullable)
      t.column("SERVER_NO",VarcharType,Limit(32),Nullable,Comment("服务器编码"))
      t.column("LOCAL_PORT",BigintType,Limit(22),Nullable,Comment("本服务器端口"))
      t.column("AUTO_UPLOAD",BigintType,Limit(22),Nullable,Comment("是否自动上报0:不自动1:自动"))
      t.column("PERSON_NO_PR",VarcharType,Limit(10),Nullable,Comment("人员编号前缀"))
      t.column("WEB_SER_URL",VarcharType,Limit(100),Nullable,Comment("连接WS地址"))
      t.column("WEB_SER_USERNAME",VarcharType,Limit(20),Nullable,Comment("连接WS用户名"))
      t.column("WEB_SER_PASSWORD",VarcharType,Limit(20),Nullable,Comment("连接WS密码"))
      t.column("WEBSERVICE_URL",VarcharType,Limit(100),Nullable,Comment("webService访问地址"))
    }
    createTable("SYS_DICT",Comment("数据字典")){ t=>
      t.column("DICT_CODE",VarcharType,Limit(20),NotNull,Comment("字典编码"))
      t.column("DICT_NAME",VarcharType,Limit(300),Nullable,Comment("字典名称"))
      t.column("TYPE_ID",VarcharType,Limit(10),Nullable,Comment("字典类型ID"))
      t.column("OPEN_FLAG",BigintType,Limit(22),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("LIMITTO",VarcharType,Limit(300),Nullable,Comment("约束"))
      t.column("DICT_VALUE",VarcharType,Limit(20),Nullable,Comment("字典值"))
    }
    createTable("SYS_DICTTYPE",Comment("数据字典类型")){ t=>
      t.column("TYPE_CODE",VarcharType,Limit(10),NotNull,Comment("类型编码"))
      t.column("IS_COMMON",BigintType,Limit(22),Nullable,Comment("是否公用类型(1:公共类型 2: 本地类型)"))
      t.column("TYPE_NAME",VarcharType,Limit(60),Nullable,Comment("字典类型名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
      t.column("TYPE_TABLE_NAME",VarcharType,Limit(30),Nullable,Comment("字典类型表名"))
    }
    createTable("SYS_FUNCTION",Comment("功能权限表")){ t=>
      t.column("FUNCTION_ID",VarcharType,Limit(32),NotNull,Comment("功能标记"))
      t.column("NAME",VarcharType,Limit(90),Nullable,Comment("名称"))
      t.column("REMARK",VarcharType,Limit(300),Nullable,Comment("描述"))
    }
    createTable("SYS_IP",Comment("IP表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull,Comment("序号"))
      t.column("ADDRE_IP",VarcharType,Limit(50),NotNull)
      t.column("DELETE_FLAG",BigintType,Limit(22),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("CREATE_USERNAME",VarcharType,Limit(50),Nullable,Comment("记录创建人姓名"))
      t.column("CREATE_USERID",VarcharType,Limit(50),Nullable)
      t.column("CREATE_DATETIME",TimestampType,Limit(7),Nullable,Comment("记录创建时间"))
      t.column("REMARK",VarcharType,Limit(200),Nullable)
    }
    createTable("SYS_LOG"){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull)
      t.column("ADDRE_IP",VarcharType,Limit(50),Nullable)
      t.column("USER_NAME",VarcharType,Limit(50),Nullable)
      t.column("USER_ID",VarcharType,Limit(50),Nullable)
      t.column("CREATE_DATETIME",TimestampType,Limit(7),NotNull)
      t.column("DELETE_FLAG",BigintType,Limit(22),NotNull)
      t.column("REMARK",VarcharType,Limit(200),Nullable)
      t.column("LOG_TYPE",VarcharType,Limit(50),Nullable)
    }
    createTable("SYS_LOGINTIME_CONTROL",Comment("登陆时间控制表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull)
      t.column("CONTROL_NAME",VarcharType,Limit(20),Nullable,Comment("控制名称"))
      t.column("CONTROL_RULE",VarcharType,Limit(1),Nullable,Comment("控制规则(1:日期段控制,2:每日时间段控制)"))
      t.column("START_TIME",VarcharType,Limit(20),Nullable,Comment("开始时间"))
      t.column("END_TIME",VarcharType,Limit(20),Nullable,Comment("结束时间"))
      t.column("CREATE_USER",VarcharType,Limit(32),Nullable,Comment("创建人"))
      t.column("CREATE_TIME",TimestampType,Limit(7),Nullable,Comment("创建时间"))
    }
    createTable("SYS_MEG",Comment("系统消息提醒表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull)
      t.column("PERSON_ID",VarcharType,Limit(32),NotNull,Comment("人员id"))
      t.column("PERSON_NAME",VarcharType,Limit(60),Nullable,Comment("人员名称"))
      t.column("GATHER_USER_ID",VarcharType,Limit(32),Nullable,Comment("采集人"))
      t.column("MEG_TYPE",BigintType,Limit(22),Nullable,Comment("消息类型"))
      t.column("MESSAGE",VarcharType,Limit(200),Nullable,Comment("消息内容"))
      t.column("LOOK_STATUS",BigintType,Limit(22),Nullable,Comment("查看状态 "))
      t.column("INPUTTIME",TimestampType,Limit(7),Nullable,Comment("创建时间"))
      t.column("GATHER_DEPART_CODE",VarcharType,Limit(12),Nullable,Comment("采集单位编码"))
    }
    createTable("SYS_MENU",Comment("系统菜单表")){ t=>
      t.column("MENU_CODE",VarcharType,Limit(10),NotNull,Comment("菜单编码"),PrimaryKey)
      t.column("SYS_CODE",VarcharType,Limit(2),Nullable,Comment("系统编码"))
      t.column("MENU_NAME",VarcharType,Limit(60),Nullable,Comment("菜单名称"))
      t.column("MENU_ACTION",VarcharType,Limit(100),Nullable,Comment("菜单请求"))
      t.column("DELETE_FLAG",BigintType,Limit(22),Nullable,Comment("删除标志(1: 禁用0: 启用)"))
      t.column("ICON",VarcharType,Limit(100),Nullable,Comment("菜单图标"))
      t.column("PARENT_ID",VarcharType,Limit(10),Nullable,Comment("父ID"))
      t.column("LEVEL_NO",BigintType,Limit(22),Nullable,Comment("层级"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("IS_LEAF",BigintType,Limit(22),Nullable,Comment("是否叶子"))
      t.column("SOFA",VarcharType,Limit(60),Nullable,Comment("一级菜单"))
      t.column("BENCH",VarcharType,Limit(60),Nullable,Comment("二级菜单"))
      t.column("WIN_PANEL",VarcharType,Limit(60),Nullable,Comment("前台panel"))
    }
    createTable("SYS_MENU_ROLE",Comment("角色拥有菜单表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull,Comment("序号"))
      t.column("ROLE_ID",VarcharType,Limit(32),NotNull,Comment("角色ID"))
      t.column("MENU_CODE",VarcharType,Limit(10),Nullable,Comment("菜单编码"))
      t.column("REMARK",VarcharType,Limit(300),Nullable,Comment("备注"))
      t.column("CREATE_USER",VarcharType,Limit(60),NotNull,Comment("记录创建人"))
      t.column("CREATE_DATETIME",TimestampType,Limit(7),Nullable,Comment("记录创建时间"))
      t.column("UPDATE_USER",VarcharType,Limit(60),Nullable,Comment("记录更新人"))
      t.column("UPDATE_DATETIME",TimestampType,Limit(7),Nullable,Comment("记录更新时间"))
      t.column("CREATE_USER_ID",VarcharType,Limit(32),Nullable,Comment("记录创建人ID"))
      t.column("UPDATE_USER_ID",VarcharType,Limit(32),Nullable,Comment("记录更新人ID"))
      t.column("ONLY_READ",BigintType,Limit(22),Nullable,Comment("只读标记0:可写1:只读"))
    }
    createTable("SYS_REPORT_CASE_OPERATION",Comment("现场运维统计报表")){ t=>
      t.column("DCODE",VarcharType,Limit(12),Nullable,Comment("部门编号"))
      t.column("DNAME",VarcharType,Limit(200),Nullable,Comment("部门名称"))
      t.column("PARENTID",VarcharType,Limit(12),Nullable,Comment("父级编号"))
      t.column("ISLEAF",VarcharType,Limit(1),Nullable,Comment("是否子节点"))
      t.column("OCCURDATE",TimestampType,Limit(7),Nullable,Comment("案发日期"))
      t.column("CASECOUNT",BigintType,Limit(22),Nullable,Comment("案件数"))
      t.column("CASECHECKEDCOUNT",BigintType,Limit(22),Nullable,Comment("比中案件数"))
      t.column("CASEUNCHECKEDCOUNT",BigintType,Limit(22),Nullable,Comment("未比中案件数"))
      t.column("ASSISTA",BigintType,Limit(22),Nullable,Comment("协查A级下发数"))
      t.column("ASSISTB2",BigintType,Limit(22),Nullable,Comment("协查B级紧下发数"))
      t.column("ASSISTB",BigintType,Limit(22),Nullable,Comment("协查B级下发数"))
      t.column("ASSISTC",BigintType,Limit(22),Nullable,Comment("协查C级下发数"))
      t.column("ASSISTAQUERY",BigintType,Limit(22),Nullable,Comment("协查A级提交数"))
      t.column("ASSISTB2QUERY",BigintType,Limit(22),Nullable,Comment("协查B级紧提交数"))
      t.column("ASSISTBQUERY",BigintType,Limit(22),Nullable,Comment("协查B级提交数"))
      t.column("ASSISTCQUERY",BigintType,Limit(22),Nullable,Comment("协查C级提交数"))
    }
    createTable("SYS_REPORT_PERSON_CHECKIN",Comment("指纹查重查中报表")){ t=>
      t.column("DCODE",VarcharType,Limit(12),Nullable,Comment("单位编号"))
      t.column("DNAME",VarcharType,Limit(200),Nullable,Comment("单位名称"))
      t.column("PARENTID",VarcharType,Limit(12),Nullable,Comment("父级编号"))
      t.column("CONFIRMTIME",TimestampType,Limit(7),Nullable,Comment("比中时间"))
      t.column("ISLEAF",VarcharType,Limit(1),Nullable,Comment("是否子节点"))
      t.column("GATHERSYSTEMCOUNT",BigintType,Limit(22),Nullable,Comment("省内标采系统比中数"))
      t.column("FINGERSYSTEMCOUNT",BigintType,Limit(22),Nullable,Comment("省内指纹系统比中数"))
      t.column("ASSISTA",BigintType,Limit(22),Nullable,Comment("协查A级"))
      t.column("ASSISTB2",BigintType,Limit(22),Nullable,Comment("协查B级紧"))
      t.column("ASSISTB",BigintType,Limit(22),Nullable,Comment("协查B级"))
      t.column("ASSISTC",BigintType,Limit(22),Nullable,Comment("协查C级"))
      t.column("WSXZCOUNT",BigintType,Limit(22),Nullable,Comment("外省协作十指指纹比中数"))
    }
    createTable("SYS_REPORT_PERSON_OPERATION",Comment("十指指纹信息统计报表")){ t=>
      t.column("DCODE",VarcharType,Limit(12),Nullable,Comment("单位编号"))
      t.column("DNAME",VarcharType,Limit(200),Nullable,Comment("单位名称"))
      t.column("PARENTID",VarcharType,Limit(12),Nullable,Comment("父级编号"))
      t.column("ISLEAF",VarcharType,Limit(1),Nullable,Comment("是否子节点"))
      t.column("INPUTTIME",TimestampType,Limit(7),Nullable,Comment("创建时间"))
      t.column("BCCOUNT",BigintType,Limit(22),Nullable,Comment("标采数"))
      t.column("XCCOUNT",BigintType,Limit(22),Nullable,Comment("协查数"))
      t.column("ZWCOUNT",BigintType,Limit(22),Nullable,Comment("指纹数"))
      t.column("FPTCOUNT",BigintType,Limit(22),Nullable,Comment("FPT数"))
    }
    createTable("SYS_ROLE",Comment("角色表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull,Comment("序号"))
      t.column("ROLE_NAME",VarcharType,Limit(60),NotNull,Comment("角色名"))
      t.column("ROLE_DESCRIPTION",VarcharType,Limit(90),Nullable,Comment("角色描述"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("CREATE_DATETIME",TimestampType,Limit(7),NotNull,Comment("记录创建时间"))
      t.column("UPDATE_DATETIME",TimestampType,Limit(7),Nullable,Comment("记录更新时间"))
      t.column("CREATE_USER_ID",VarcharType,Limit(32),Nullable,Comment("记录创建人ID"))
      t.column("UPDATE_USER_ID",VarcharType,Limit(32),Nullable,Comment("记录更新人ID"))
      t.column("ROLE_LEVEL",VarcharType,Limit(1),Nullable,Comment("级别"))
      t.column("SYS_CODE",VarcharType,Limit(2),Nullable,Comment("系统编号"))
      t.column("ROLE_SIGN",VarcharType,Limit(20),Nullable,Comment("角色标识"))
    }
    createTable("SYS_ROLE_FUNCTION",Comment("角色功能关系表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull)
      t.column("ROLE_ID",VarcharType,Limit(32),Nullable,Comment("角色"))
      t.column("FUNCTION_ID",VarcharType,Limit(32),Nullable,Comment("功能"))
      t.column("CREATE_USER_ID",VarcharType,Limit(32),Nullable,Comment("创建人ID"))
      t.column("CREATE_DATETIME",TimestampType,Limit(7),Nullable,Comment("创建时间"))
    }
    createTable("SYS_ROLE_SIGN",Comment("角色标识字典表")){ t=>
      t.column("CODE",VarcharType,Limit(20),NotNull,Comment("角色标识且唯一"))
      t.column("NAME",VarcharType,Limit(300),Nullable,Comment("标识名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
    }
    createTable("SYS_TRANSFER",Comment("用户调动记录表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull)
      t.column("USERID",VarcharType,Limit(32),Nullable,Comment("用户编号"))
      t.column("LAST_DEPART_ID",VarcharType,Limit(32),Nullable,Comment("原单位编号"))
      t.column("NEW_DEPART_ID",VarcharType,Limit(32),Nullable,Comment("新单位编号"))
      t.column("TRANSFER_DATE",TimestampType,Limit(7),Nullable,Comment("调动日期"))
      t.column("TRANSFER_REASON",VarcharType,Limit(300),Nullable,Comment("调动原因"))
    }
    createTable("SYS_USER",Comment("系统用户表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull,Comment("序号"))
      t.column("LOGIN_NAME",VarcharType,Limit(60),NotNull,Comment("用户登录名"))
      t.column("PASSWORD",VarcharType,Limit(32),Nullable,Comment("密码"))
      t.column("EMAIL",VarcharType,Limit(60),Nullable,Comment("电子邮箱"))
      t.column("TRUE_NAME",VarcharType,Limit(60),Nullable,Comment("真实姓名"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
      t.column("CREATE_DATETIME",TimestampType,Limit(7),Nullable,Comment("记录创建时间"))
      t.column("UPDATE_DATETIME",TimestampType,Limit(7),Nullable,Comment("记录更新时间"))
      t.column("CREATE_USER_ID",VarcharType,Limit(32),Nullable,Comment("记录创建人ID"))
      t.column("UPDATE_USER_ID",VarcharType,Limit(32),Nullable,Comment("记录更新人ID"))
      t.column("DEPART_CODE",VarcharType,Limit(12),Nullable,Comment("用户所属部门ID"))
      t.column("IDCARD",VarcharType,Limit(18),Nullable,Comment("人员身份证"))
      t.column("POLICE_NUMBER",VarcharType,Limit(10),Nullable,Comment("警号"))
      t.column("GENDER_CODE",VarcharType,Limit(1),Nullable,Comment("性别（字典）"))
      t.column("USER_TYPE",VarcharType,Limit(1),Nullable,Comment("用户身份"))
      t.column("PHONE",VarcharType,Limit(20),Nullable,Comment("手机号码"))
      t.column("DEPART_START_DATE",TimestampType,Limit(7),Nullable,Comment("用户当前所在部门开始时间"))
      t.column("USER_STATUS",VarcharType,Limit(1),Nullable,Comment("用户状态"))
      t.column("LAST_LOGIN_DATE",TimestampType,Limit(7),Nullable,Comment("最后一次登录时间"))
      t.column("LOGIN_TIME_CONTROL",VarcharType,Limit(1),Nullable,Comment("登录时间控制(0:长期用户,1:登录受限用户)"))
    }
    createTable("SYS_USER_LOGINTIME_CONTROL",Comment("用户登陆时间控制对应表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull)
      t.column("USER_ID",VarcharType,Limit(32),Nullable,Comment("用户ID"))
      t.column("CONTROL_ID",VarcharType,Limit(32),Nullable,Comment("控制ID"))
      t.column("CREATE_USER",VarcharType,Limit(32),Nullable,Comment("创建人"))
      t.column("CREATE_TIME",TimestampType,Limit(7),Nullable,Comment("创建时间"))
    }
    createTable("SYS_USER_ROLE",Comment("角色用户关联表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull,Comment("序号"))
      t.column("USER_ID",VarcharType,Limit(32),NotNull,Comment("用户序号"))
      t.column("ROLE_ID",VarcharType,Limit(32),NotNull,Comment("角色ID"))
      t.column("REMARK",VarcharType,Limit(300),Nullable,Comment("备注"))
      t.column("CREATE_USER",VarcharType,Limit(60),NotNull,Comment("记录创建人"))
      t.column("CREATE_DATETIME",TimestampType,Limit(7),Nullable,Comment("记录创建时间"))
      t.column("UPDATE_USER",VarcharType,Limit(60),Nullable,Comment("记录更新人"))
      t.column("UPDATE_DATETIME",TimestampType,Limit(7),Nullable,Comment("记录更新时间"))
      t.column("CREATE_USER_ID",VarcharType,Limit(32),Nullable,Comment("记录创建人ID"))
      t.column("UPDATE_USER_ID",VarcharType,Limit(32),Nullable,Comment("记录更新人ID"))
      t.column("DEPART_CODE",VarcharType,Limit(12),Nullable,Comment("部门编号，用于权限控制"))
    }
    sequence("GAFIS_CASE_FINGER_PALM_SEQ")
    sequence("GAFIS_CASE_SID_SEQ")
    sequence("GAFIS_GATHER_FINGER_SEQ")
    sequence("GAFIS_GATHER_PALM_SEQ")
    sequence("GAFIS_PERSON_SEQ")
    sequence("GAFIS_PERSON_SID_SEQ")
    sequence("LOG_INFO_NUM_ID_SEQ")
    sequence("SEQ_ORASID")

  }

  def down() {
    dropTable("SYS_USER_ROLE")
    dropTable("SYS_USER_LOGINTIME_CONTROL")
    dropTable("SYS_USER")
    dropTable("SYS_TRANSFER")
    dropTable("SYS_ROLE_SIGN")
    dropTable("SYS_ROLE_FUNCTION")
    dropTable("SYS_ROLE")
    dropTable("SYS_REPORT_PERSON_OPERATION")
    dropTable("SYS_REPORT_PERSON_CHECKIN")
    dropTable("SYS_REPORT_CASE_OPERATION")
    dropTable("SYS_MENU_ROLE")
    dropTable("SYS_MENU")
    dropTable("SYS_MEG")
    dropTable("SYS_LOGINTIME_CONTROL")
    dropTable("SYS_LOG")
    dropTable("SYS_IP")
    dropTable("SYS_FUNCTION")
    dropTable("SYS_DICTTYPE")
    dropTable("SYS_DICT")
    dropTable("SYS_DEPLOY")
    dropTable("SYS_DEPART_EQUIPMENT")
    dropTable("SYS_DEPART")
    dropTable("SYS_CONTROL_LOG")
    dropTable("SYS_CONTROL")
    dropTable("SYS_AREA")
    dropTable("LOG_INFO")
    dropTable("GAFIS_SCHEDULING")
    dropTable("GAFIS_SCAN_CUT")
    dropTable("GAFIS_QUERYQUE_COUNT")
    dropTable("GAFIS_PERSON_NO_RULE")
    dropTable("GAFIS_PERSON_NO")
    dropTable("GAFIS_PERSON_ATT")
    dropTable("GAFIS_PERSON")
    dropTable("GAFIS_NORMALQUERY_QUERYQUE")
    dropTable("GAFIS_LOGIC_DB_FINGERPRINT")
    dropTable("GAFIS_LOGIC_DB_CASE")
    dropTable("GAFIS_LOGIC_DB")
    dropTable("GAFIS_GATHER_VIRTUAL")
    dropTable("GAFIS_GATHER_TYPE_NODE_FIELD")
    dropTable("GAFIS_GATHER_TYPE_NODE")
    dropTable("GAFIS_GATHER_TYPE")
    dropTable("GAFIS_GATHER_SPECIALTY")
    dropTable("GAFIS_GATHER_RESUME")
    dropTable("GAFIS_GATHER_PORTRAIT")
    dropTable("GAFIS_GATHER_PHONE")
    dropTable("GAFIS_GATHER_PERSON_PHOTO")
    dropTable("GAFIS_GATHER_PALM")
    dropTable("GAFIS_GATHER_OCX_VERSION")
    dropTable("GAFIS_GATHER_NODE")
    dropTable("GAFIS_GATHER_IDCARD")
    dropTable("GAFIS_GATHER_FLOW")
    dropTable("GAFIS_GATHER_FINGER")
    dropTable("GAFIS_GATHER_FIELDSET")
    dropTable("GAFIS_GATHER_DATA_LOG")
    dropTable("GAFIS_GATHER_CERTIFICATE")
    dropTable("GAFIS_FINGER_TEXT_LOG")
    dropTable("GAFIS_FINGER_BBS_ATTACHMENT")
    dropTable("GAFIS_FINGER_BBS")
    dropTable("GAFIS_FINGER_AUDIT")
    dropTable("GAFIS_EXTRACT_MNT_TASK")
    dropTable("GAFIS_CONTRORCAPTURE_PERSON")
    dropTable("GAFIS_CONFIGURE_MAXQUERY")
    dropTable("GAFIS_COMPARE_PARAM_PRIORITY")
    dropTable("GAFIS_COMPARE_PARAM_MAXQUERY")
    dropTable("GAFIS_COMPARE_CONFIGURE")
    dropTable("GAFIS_CHECKIN_REVIEW")
    dropTable("GAFIS_CHECKIN_INFO")
    dropTable("GAFIS_CHECKIN_APPEAL")
    dropTable("GAFIS_CASE_PALM_MNT")
    dropTable("GAFIS_CASE_PALM")
    dropTable("GAFIS_CASE_FINGER_MNT")
    dropTable("GAFIS_CASE_FINGER")
    dropTable("GAFIS_CASE")
    dropTable("GAFIS_AUTO_CONFIGURE")
    dropTable("GAFIS_AUTO_COMPARE_CONF")
    dropTable("CODE_ZZMM")
    dropTable("CODE_ZY")
    dropTable("CODE_ZWZT")
    dropTable("CODE_ZJZL")
    dropTable("CODE_ZJXY")
    dropTable("CODE_ZC")
    dropTable("CODE_ZAYY")
    dropTable("CODE_YHZT")
    dropTable("CODE_YHSF")
    dropTable("CODE_XX")
    dropTable("CODE_XNSFLX")
    dropTable("CODE_XCTQFS")
    dropTable("CODE_XCJB")
    dropTable("CODE_XB")
    dropTable("CODE_WHCD")
    dropTable("CODE_TXLX")
    dropTable("CODE_TX")
    dropTable("CODE_TSSF")
    dropTable("CODE_TSRQ")
    dropTable("CODE_SHYY")
    dropTable("CODE_RYLX")
    dropTable("CODE_RTXYS")
    dropTable("CODE_MZ")
    dropTable("CODE_MARRY")
    dropTable("CODE_LY")
    dropTable("CODE_LX")
    dropTable("CODE_JJLY")
    dropTable("CODE_IF")
    dropTable("CODE_GJ")
    dropTable("CODE_DHLX")
    dropTable("CODE_CJLB")
    dropTable("CODE_BDZT")
    dropTable("CODE_AY")
    dropTable("CODE_AJZT")
    dropTable("CODE_AJXZ")
    dropTable("CODE_AJLY")
    dropTable("CODE_AJLX")
    dropTable("CODE_AJLB")
    dropSequence("SEQ_ORASID")
    dropSequence("LOG_INFO_NUM_ID_SEQ")
    dropSequence("GAFIS_PERSON_SID_SEQ")
    dropSequence("GAFIS_PERSON_SEQ")
    dropSequence("GAFIS_GATHER_PALM_SEQ")
    dropSequence("GAFIS_GATHER_FINGER_SEQ")
    dropSequence("GAFIS_CASE_SID_SEQ")
    dropSequence("GAFIS_CASE_FINGER_PALM_SEQ")

  }
}

