/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nirvana_hall_image_jni_NativeImageConverter */

#ifndef _Included_nirvana_hall_image_jni_NativeImageConverter
#define _Included_nirvana_hall_image_jni_NativeImageConverter
#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *jvm, void *reserved);

/*
 * Class:     nirvana_hall_image_jni_NativeImageConverter
 * Method:    loadLibrary
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_nirvana_hall_image_jni_NativeImageConverter_loadLibrary
  (JNIEnv *, jclass, jstring fileName,jstring funName,jint firmCode,jint nOption);

/*
 * Class:     nirvana_hall_image_jni_NativeImageConverter
 * Method:    freeLibrary
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_nirvana_hall_image_jni_NativeImageConverter_freeLibrary
  (JNIEnv *, jclass, jlong);

/*
 * Class:     nirvana_hall_image_jni_NativeImageConverter
 * Method:    decodeByManufactory
 * Signature: (JLjava/lang/String;Ljava/lang/String;[BI)[B
 */
JNIEXPORT jobject JNICALL Java_nirvana_hall_image_jni_NativeImageConverter_decodeByManufactory
  (JNIEnv *, jclass, jlong, jstring, jint, jbyteArray, jint);
JNIEXPORT void JNICALL Java_nirvana_hall_image_jni_NativeImageConverter_decodeByGFS
   (JNIEnv *, jclass, jbyteArray, jbyteArray,jboolean);

/*
 * Class:     nirvana_hall_image_jni_NativeImageConverter
 * Method:    decodeByWSQ
 * Signature: ([B)Lnirvana/hall/image/jni/OriginalImage;
 */
JNIEXPORT jobject JNICALL Java_nirvana_hall_image_jni_NativeImageConverter_decodeByWSQ
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     nirvana_hall_image_jni_NativeImageConverter
 * Method:    encodeByWSQ
 * Signature: ([BIIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_nirvana_hall_image_jni_NativeImageConverter_encodeByWSQ
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
