package nirvana.hall.v70.migration

import monad.migration._

/**
 * 添加现场案件相关的表
 * Created by songpeng on 15/12/2.
 */
class Migrate_20151202092825_CopyCaseTable extends Migration{
  def up(): Unit = {
    createTable("CODE_AJLX",Comment("案件类型字典")){ t=>
      t.column("CODE",VarcharType,Limit(1),NotNull,Comment("字典编码"),PrimaryKey)
      t.column("NAME",VarcharType,Limit(60),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("CODE_AJLY",Comment("案件来源字典")){ t=>
      t.column("CODE",VarcharType,Limit(1),NotNull,Comment("字典编码"),PrimaryKey)
      t.column("NAME",VarcharType,Limit(60),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("CODE_AJXZ",Comment("案件性质字典")){ t=>
      t.column("CODE",VarcharType,Limit(3),NotNull,Comment("字典编码"),PrimaryKey)
      t.column("NAME",VarcharType,Limit(60),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
      t.column("FIRST_LETTER",VarcharType,Limit(30),Nullable,Comment("首字母"))
    }
    createTable("CODE_AJZT",Comment("案件状态")){ t=>
      t.column("CODE",VarcharType,Limit(2),NotNull,Comment("字典编码"),PrimaryKey)
      t.column("NAME",VarcharType,Limit(200),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("CODE_AY",Comment("案由字典")){ t=>
      t.column("CODE",VarcharType,Limit(6),NotNull,Comment("字典编码"),PrimaryKey)
      t.column("NAME",VarcharType,Limit(200),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
      t.column("FIRST_LETTER",VarcharType,Limit(30),Nullable,Comment("首字母"))
    }
    createTable("CODE_RTXYS",Comment("乳突线颜色")){ t=>
      t.column("CODE",VarcharType,Limit(1),NotNull,Comment("字典编码"),PrimaryKey)
      t.column("NAME",VarcharType,Limit(200),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("CODE_XCJB",Comment("协查级别")){ t=>
      t.column("CODE",VarcharType,Limit(1),NotNull,Comment("字典编码"),PrimaryKey)
      t.column("NAME",VarcharType,Limit(200),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("CODE_XCTQFS",Comment("现场提取方式")){ t=>
      t.column("CODE",VarcharType,Limit(2),NotNull,Comment("字典编码"),PrimaryKey)
      t.column("NAME",VarcharType,Limit(200),Nullable,Comment("字典名称"))
      t.column("DELETE_FLAG",VarcharType,Limit(1),Nullable,Comment("启用标志(0: 禁用1: 启用)"))
      t.column("ORD",BigintType,Limit(22),Nullable,Comment("排序"))
      t.column("REMARK",VarcharType,Limit(90),Nullable,Comment("备注"))
    }
    createTable("GAFIS_CASE",Comment("案件信息")){ t=>
      t.column("CASE_ID",VarcharType,Limit(23),NotNull,Comment("案件编号共23字节，第1位为大写英文字母A，第2至13位为立案单位代码，第14至17位为年份，第18至19位为月份，第20至23位为顺序号"),PrimaryKey)
      t.column("CARD_ID",VarcharType,Limit(23),Nullable,Comment("案件编号"))
      t.column("CASE_CLASS_CODE",VarcharType,Limit(6),Nullable,Comment("案件类别(字典与案事件系统相同)"))
      t.column("CASE_OCCUR_DATE",TimestampType,Limit(7),Nullable,Comment("发案日期"))
      t.column("CASE_OCCUR_PLACE_CODE",VarcharType,Limit(6),Nullable,Comment("发案地点代码"))
      t.column("CASE_OCCUR_PLACE_DETAIL",VarcharType,Limit(70),Nullable,Comment("发案地点"))
      t.column("CASE_BRIEF_DETAIL",VarcharType,Limit(1000),Nullable,Comment("简要案情"))
      t.column("IS_MURDER",VarcharType,Limit(1),Nullable,Comment("命案标识1:是/0:否"))
      t.column("AMOUNT",VarcharType,Limit(16),Nullable,Comment("涉案金额(单位：元)"))
      t.column("EXTRACT_UNIT_CODE",VarcharType,Limit(12),Nullable,Comment("提取单位代码"))
      t.column("EXTRACT_UNIT_NAME",VarcharType,Limit(90),Nullable,Comment("提取单位名称"))
      t.column("EXTRACT_DATE",TimestampType,Limit(7),Nullable,Comment("提取日期"))
      t.column("EXTRACTOR",VarcharType,Limit(30),Nullable,Comment("提取人"))
      t.column("SUSPICIOUS_AREA_CODE",VarcharType,Limit(6),Nullable,Comment("可疑地区线索"))
      t.column("CASE_STATE",VarcharType,Limit(2),Nullable,Comment("案件状态(采用案事件系统的案件状态)"))
      t.column("CASE_NATURE",VarcharType,Limit(3),Nullable,Comment("案件性质(按照案事件系统标准)"))
      t.column("REMARK",VarcharType,Limit(1000),Nullable,Comment("备注"))
      t.column("INPUTPSN",VarcharType,Limit(32),Nullable,Comment("记录创建人ID SYS_USER"))
      t.column("INPUTTIME",TimestampType,Limit(7),Nullable,Comment("记录创建时间"))
      t.column("MODIFIEDPSN",VarcharType,Limit(32),Nullable,Comment("记录更新人ID SYS_USER"))
      t.column("MODIFIEDTIME",TimestampType,Limit(7),Nullable,Comment("记录更新时间"))
      t.column("DELETAG",VarcharType,Limit(1),Nullable,Comment("删除标志"))
      t.column("BROKEN_STATUS",SmallintType,Limit(3),Nullable,Comment("是否破案"))
      t.column("CASE_SOURCE",VarcharType,Limit(1),Nullable,Comment("案件来源"))
      t.column("CREATE_UNIT_CODE",VarcharType,Limit(12),Nullable)
      t.column("ASSIST_LEVEL",VarcharType,Limit(1),Nullable,Comment("协查级别"))
      t.column("CASE_NATURE_OLD",VarcharType,Limit(60),Nullable,Comment("原案件性质(名称描述)"))
      t.column("IS_CHECKED",CharType,Limit(1),Nullable,Comment("是否比中1:是/否"))
      t.column("FPT_EXTRACT_UNIT_CODE",VarcharType,Limit(12),Nullable,Comment("FPT提取单位代码"))
      t.column("FPT_EXTRACT_UNIT_NAME",VarcharType,Limit(90),Nullable,Comment("FPT提取单位名称"))
      t.column("SID",BigintType,Limit(22),Nullable,Comment("SID比对唯一标识"))
      t.column("ASSIST_BONUS",VarcharType,Limit(6),Nullable,Comment("协查标识"))
      t.column("ASSIST_DEPT_CODE",VarcharType,Limit(12),Nullable,Comment("协查单位代码"))
      t.column("ASSIST_DEPT_NAME",VarcharType,Limit(70),Nullable,Comment("协查单位名称"))
      t.column("ASSIST_DATE",VarcharType,Limit(8),Nullable,Comment("协查日期(格式:YYYYMMDD)"))
      t.column("ASSIST_SIGN",VarcharType,Limit(1),Nullable,Comment("案件协查标识(1:协查;0:不协查)"))
      t.column("ASSIST_REVOKE_SIGN",VarcharType,Limit(1),Nullable,Comment("部撤销标识(1:已破;2:外省;3:多报;4:其他)"))
      t.column("CS_NO",VarcharType,Limit(23),Nullable,Comment("现勘编号"))
      t.column("PSIS_NO",VarcharType,Limit(23),Nullable,Comment("警综编号"))
    }
    addIndex("GAFIS_CASE",Array[String]("SID"),Name("GAFIS_CASE_IDX_01"))
    createTable("GAFIS_CASE_FINGER",Comment("现场指纹")){ t=>
      t.column("SEQ_NO",VarcharType,Limit(2),Nullable,Comment("指纹序号"))
      t.column("FINGER_ID",VarcharType,Limit(25),NotNull,Comment("指纹编号"),PrimaryKey)
      t.column("CASE_ID",VarcharType,Limit(23),Nullable,Comment("案件编号"))
      t.column("IS_CORPSE",VarcharType,Limit(1),Nullable,Comment("未知名尸体标识(1:是/0:否)"))
      t.column("CORPSE_NO",VarcharType,Limit(23),Nullable,Comment("未知名尸体编号"))
      t.column("REMAIN_PLACE",VarcharType,Limit(60),Nullable,Comment("遗留部位"))
      t.column("FGP_GROUP",SmallintType,Limit(3),Nullable,Comment("指位组"))
      t.column("FGP",VarcharType,Limit(10),Nullable,Comment("分析指位:用10个字节表示，从左至右每字节依次对应指位代码01到指位代码10，每字节有效值为1或0，1表示可能为该指位，0表示不可能为该指位"))
      t.column("RIDGE_COLOR",VarcharType,Limit(1),Nullable,Comment("乳突线颜色"))
      t.column("PATTERN",VarcharType,Limit(20),Nullable,Comment("纹型"))
      t.column("MITTENS_BEG_NO",VarcharType,Limit(2),Nullable,Comment("连指开始序号(“00”表示没有连指)"))
      t.column("MITTENS_END_NO",VarcharType,Limit(2),Nullable,Comment("连指结束序号(“00”表示没有连指)"))
      t.column("THAN_STATUS",VarcharType,Limit(2),Nullable,Comment("指纹比对状态"))
      t.column("IS_ASSIST",VarcharType,Limit(1),Nullable,Comment("指纹协查标识"))
      t.column("FINGER_IMG",BlobType,Limit(4000),Nullable,Comment("指纹原图"))
      t.column("FINGER_CPR",BlobType,Limit(4000),Nullable,Comment("指纹压缩图"))
      t.column("LT_COUNT",BigintType,Limit(22),Nullable,Comment("累计查案（LT）次数"))
      t.column("LL_COUNT",BigintType,Limit(22),Nullable,Comment("累计串查（LL）次数"))
      t.column("LT_COUNT_MOD_MNT",BigintType,Limit(22),Nullable,Comment("特征修改后查案（LT）次数"))
      t.column("LL_COUNT_MOD_MNT",BigintType,Limit(22),Nullable,Comment("特征修改后查案（LL）次数"))
      t.column("EDIT_COUNT",BigintType,Limit(22),Nullable,Comment("特征修改后查案（LL）次数"))
      t.column("LT_DATE",TimestampType,Limit(7),Nullable,Comment("最近查案（LT）时间"))
      t.column("LL_DATE",TimestampType,Limit(7),Nullable,Comment("最近串查（LL）时间"))
      t.column("LT_OPERATOR",VarcharType,Limit(32),Nullable,Comment("最近查案（LT）操作者"))
      t.column("LL_OPERATOR",VarcharType,Limit(32),Nullable,Comment("最近串查（LL）操作者"))
      t.column("LT_STATUS",VarcharType,Limit(1),Nullable,Comment("查案比中状态：1：比中；0：未比中"))
      t.column("LL_STATUS",VarcharType,Limit(1),Nullable,Comment("串案比中状态：1：比中；0：未比中"))
      t.column("CREATOR_UNIT_CODE",VarcharType,Limit(12),Nullable,Comment("创建单位代码"))
      t.column("UPDATOR_UNIT_CODE",VarcharType,Limit(12),Nullable,Comment("更新单位代码"))
      t.column("MODIFIEDTIME",TimestampType,Limit(7),Nullable,Comment("记录更新时间"))
      t.column("MODIFIEDPSN",VarcharType,Limit(32),Nullable,Comment("记录更新人ID SYS_USER"))
      t.column("INPUTTIME",TimestampType,Limit(7),Nullable,Comment("记录创建时间"))
      t.column("INPUTPSN",VarcharType,Limit(32),Nullable,Comment("记录创建人ID SYS_USER"))
      t.column("DELETAG",VarcharType,Limit(1),Nullable,Comment("删除标志"))
      t.column("REMARK",VarcharType,Limit(1000),Nullable,Comment("备注"))
      t.column("SID",BigintType,Limit(22),Nullable,Comment("SID比对唯一标识"))
      t.column("MATCH_STATUS",VarcharType,Limit(1),Nullable,Comment("比对状态:1待查 2撤销 3比中 9其他"))
      t.column("DEVELOP_METHOD",VarcharType,Limit(2),Nullable,Comment("现场提取方式code_xctqfs"))
      t.column("FINGER_CPR_NOSQL_ID",VarcharType,Limit(10),Nullable,Comment("指纹压缩图nosql存储id"))
      t.column("FINGER_IMG_NOSQL_ID",VarcharType,Limit(10),Nullable,Comment("指纹原图nosql存储id"))
      t.column("SEQ",BigintType,Limit(22),Nullable,Comment("8.0数据同步用"))
    }
    addIndex("GAFIS_CASE_FINGER",Array[String]("SID"),Name("GAFIS_CASE_FINGER_IDX_01"))
    addIndex("GAFIS_CASE_FINGER",Array[String]("SEQ"),Name("GAFIS_CASE_FINGER_IDX_02"))
    addIndex("GAFIS_CASE_FINGER",Array[String]("CASE_ID"),Name("GAFIS_CASE_FINGER_IDX_03"))
    createTable("GAFIS_CASE_FINGER_MNT",Comment("现场指纹特征表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull,Comment("PK_ID主键"),PrimaryKey)
      t.column("FINGER_ID",VarcharType,Limit(25),Nullable,Comment("指纹编号"))
      t.column("CAPTURE_METHOD",VarcharType,Limit(1),Nullable,Comment("现场指纹特征提取方式：A自动提取 U需要人工编辑 E自动提取经过人工编辑 M人工提取"))
      t.column("FINGER_MNT",BlobType,Limit(4000),Nullable,Comment("指纹特征"))
      t.column("FINGER_RIDGE",BlobType,Limit(4000),Nullable,Comment("指纹纹线"))
      t.column("IS_MAIN_MNT",VarcharType,Limit(1),Nullable,Comment("是否主特征(0：非主特征 1：是主特征)"))
      t.column("MODIFIEDTIME",TimestampType,Limit(7),Nullable,Comment("记录更新时间"))
      t.column("MODIFIEDPSN",VarcharType,Limit(32),Nullable,Comment("记录更新人ID SYS_USER"))
      t.column("INPUTTIME",TimestampType,Limit(7),Nullable,Comment("记录创建时间"))
      t.column("INPUTPSN",VarcharType,Limit(32),Nullable,Comment("记录创建人ID SYS_USER"))
      t.column("DELETAG",VarcharType,Limit(1),Nullable,Comment("删除标志"))
      t.column("FINGER_MNT_NOSQL_ID",VarcharType,Limit(10),Nullable,Comment("指纹特征nosql存储id"))
      t.column("FINGER_RIDGE_NOSQL_ID",VarcharType,Limit(10),Nullable,Comment("指纹纹线nosql存储id"))
    }
    addIndex("GAFIS_CASE_FINGER_MNT",Array[String]("FINGER_ID"),Name("GAFIS_CASE_FINGER_MNT_IDX_01"))
    addIndex("GAFIS_CASE_FINGER_MNT",Array[String]("FINGER_ID","IS_MAIN_MNT"),Name("GAFIS_CASE_FINGER_MNT_IDX_02"))
    createTable("GAFIS_CASE_PALM",Comment("现场掌纹")){ t=>
      t.column("SEQ_NO",VarcharType,Limit(2),Nullable,Comment("掌纹序号"))
      t.column("PALM_ID",VarcharType,Limit(25),NotNull,Comment("掌纹编号"),PrimaryKey)
      t.column("CASE_ID",VarcharType,Limit(23),Nullable,Comment("案件编号"))
      t.column("IS_CORPSE",VarcharType,Limit(1),Nullable,Comment("未知名尸体标识(1:是/0:否)"))
      t.column("CORPSE_NO",VarcharType,Limit(23),Nullable,Comment("未知名尸体编号"))
      t.column("REMAIN_PLACE",VarcharType,Limit(30),Nullable,Comment("遗留部位"))
      t.column("FGP",VarcharType,Limit(10),Nullable,Comment("分析指位:用10个字节表示，从左至右每字节依次对应指位代码01到指位代码10，每字节有效值为1或0，1表示可能为该指位，0表示不可能为该指位"))
      t.column("PATTERN",VarcharType,Limit(20),Nullable,Comment("纹型"))
      t.column("RIDGE_COLOR",VarcharType,Limit(1),Nullable,Comment("乳突线颜色"))
      t.column("THAN_STATUS",VarcharType,Limit(2),Nullable,Comment("掌纹比对状态"))
      t.column("IS_ASSIST",VarcharType,Limit(1),Nullable,Comment("掌纹协查标识"))
      t.column("PALM_IMG",BlobType,Limit(4000),Nullable,Comment("掌纹原图"))
      t.column("PALM_CPR",BlobType,Limit(4000),Nullable,Comment("掌纹压缩图"))
      t.column("LT_COUNT",BigintType,Limit(22),Nullable,Comment("累计查案（LT）次数"))
      t.column("LL_COUNT",BigintType,Limit(22),Nullable,Comment("累计串查（LL）次数"))
      t.column("LT_COUNT_MOD_MNT",BigintType,Limit(22),Nullable,Comment("特征修改后查案（LT）次数"))
      t.column("LL_COUNT_MOD_MNT",BigintType,Limit(22),Nullable,Comment("特征修改后查案（LL）次数"))
      t.column("EDIT_COUNT",BigintType,Limit(22),Nullable,Comment("特征修改后查案（LL）次数"))
      t.column("LT_DATE",TimestampType,Limit(7),Nullable,Comment("最近查案（LT）时间"))
      t.column("LL_DATE",TimestampType,Limit(7),Nullable,Comment("最近串查（LL）时间"))
      t.column("LT_OPERATOR",VarcharType,Limit(32),Nullable,Comment("最近查案（LT）操作者"))
      t.column("LL_OPERATOR",VarcharType,Limit(32),Nullable,Comment("最近串查（LL）操作者"))
      t.column("CREATOR_UNIT_CODE",VarcharType,Limit(12),Nullable,Comment("创建单位代码"))
      t.column("UPDATOR_UNIT_CODE",VarcharType,Limit(12),Nullable,Comment("更新单位代码"))
      t.column("MODIFIEDTIME",TimestampType,Limit(7),Nullable,Comment("记录更新时间"))
      t.column("MODIFIEDPSN",VarcharType,Limit(32),Nullable,Comment("记录更新人ID SYS_USER"))
      t.column("INPUTTIME",TimestampType,Limit(7),Nullable,Comment("记录创建时间"))
      t.column("INPUTPSN",VarcharType,Limit(32),Nullable,Comment("记录创建人ID SYS_USER"))
      t.column("DELETAG",VarcharType,Limit(1),Nullable,Comment("删除标志"))
      t.column("REMARK",VarcharType,Limit(1000),Nullable,Comment("备注"))
      t.column("LT_STATUS",VarcharType,Limit(1),Nullable,Comment("查案比中状态：1：比中；0：未比中"))
      t.column("LL_STATUS",VarcharType,Limit(1),Nullable,Comment("串案比中状态：1：比中；0：未比中"))
      t.column("SID",BigintType,Limit(22),Nullable,Comment("SID比对唯一标识"))
      t.column("MATCH_STATUS",VarcharType,Limit(1),Nullable,Comment("比对状态:1待查 2撤销 3比中 9其他"))
      t.column("DEVELOP_METHOD",VarcharType,Limit(2),Nullable,Comment("现场提取方式code_xctqfs"))
      t.column("PALM_IMG_NOSQL_ID",VarcharType,Limit(10),Nullable,Comment("掌纹原图nosql存储id"))
      t.column("PALM_CPR_NOSQL_ID",VarcharType,Limit(10),Nullable,Comment("掌纹压缩图nosql存储id"))
      t.column("SEQ",BigintType,Limit(22),Nullable,Comment("8.0数据同步用"))
    }
    addIndex("GAFIS_CASE_PALM",Array[String]("CASE_ID"),Name("GAFIS_CASE_PALM_IDX01"))
    addIndex("GAFIS_CASE_PALM",Array[String]("SEQ"),Name("GAFIS_CASE_PALM_IDX02"))
    createTable("GAFIS_CASE_PALM_MNT",Comment("现场掌纹特征表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull,Comment("PK_ID主键"),PrimaryKey)
      t.column("PALM_ID",VarcharType,Limit(25),Nullable,Comment("掌纹编号"))
      t.column("CAPTURE_METHOD",VarcharType,Limit(1),Nullable,Comment("特征提取方法(1：手工 2：自动)"))
      t.column("PALM_MNT",BlobType,Limit(4000),Nullable,Comment("掌纹特征"))
      t.column("PALM_RIDGE",BlobType,Limit(4000),Nullable,Comment("掌纹纹线"))
      t.column("IS_MAIN_MNT",VarcharType,Limit(1),Nullable,Comment("是否主特征(0：非主特征 1：是主特征)"))
      t.column("MODIFIEDTIME",TimestampType,Limit(7),Nullable,Comment("记录更新时间"))
      t.column("MODIFIEDPSN",VarcharType,Limit(32),Nullable,Comment("记录更新人ID SYS_USER"))
      t.column("INPUTTIME",TimestampType,Limit(7),Nullable,Comment("记录创建时间"))
      t.column("INPUTPSN",VarcharType,Limit(32),Nullable,Comment("记录创建人ID SYS_USER"))
      t.column("PALM_MNT_NOSQL_ID",VarcharType,Limit(10),Nullable,Comment("掌纹特征nosql存储Id"))
      t.column("PALM_RIDGE_NOSQL_ID",VarcharType,Limit(10),Nullable,Comment("掌纹纹线nosql存储Id"))
    }
    createTable("GAFIS_NORMALQUERY_QUERYQUE",Comment("查询表")){ t=>
      t.column("PK_ID",VarcharType,Limit(32),NotNull,Comment("序号"),PrimaryKey)
      t.column("ORA_SID",BigintType,Limit(15),Nullable,Comment("任务号,唯一序列"))
      t.column("KEYID",VarcharType,Limit(25),Nullable,Comment("卡号"))
      t.column("QUERYTYPE",SmallintType,Limit(3),Nullable,Comment("查询类型:捺印查重(TT):0,捺印倒查(TL):1,现场查案(LT):2,现场串查(LL):3"))
      t.column("STATUS",SmallintType,Limit(3),Nullable,Comment("查询状态:-1未知状态,0等待比对,1正在比对,2等待核查(比对完成),3错误数据"))
      t.column("PRIORITY",SmallintType,Limit(3),Nullable,Comment("查询优先级:最低0,低1,正常2,稍高3,高4,最高5"))
      t.column("HITPOSSIBILITY",SmallintType,Limit(3),Nullable,Comment("查中概率"))
      t.column("VERIFYRESULT",SmallintType,Limit(3),Nullable,Comment("比中状态:0没有结果(空白),99没有比中,98比中"))
      t.column("FLAG",SmallintType,Limit(3),Nullable,Comment("查询标记:平面指纹查询 0x80,带文本查询 0x04,掌纹查询 0x02,滚动指纹查询 0x01,平面指纹查询+带文本查询 0x80+0x04=0x84 ...."))
      t.column("FLAGC",SmallintType,Limit(3),Nullable,Comment("紧急状态:紧急(>32),正常(＝32 and null)"))
      t.column("FLAGD",SmallintType,Limit(3),Nullable)
      t.column("FLAGE",SmallintType,Default("0"),Limit(3),Nullable,Comment("快速tt查询标识"))
      t.column("FLAGG",SmallintType,Limit(3),Nullable,Comment("TT自动认定使用的标志"))
      t.column("QRYCONDITION",BlobType,Limit(4000),Nullable,Comment("查询条件(比对参数)"))
      t.column("MIC",BlobType,Limit(4000),Nullable,Comment("特征"))
      t.column("TEXTSQL",ClobType,Limit(4000),Nullable,Comment("文本查询条件(XML格式)"))
      t.column("CANDHEAD",BlobType,Limit(4000),Nullable,Comment("候选列表头"))
      t.column("CANDLIST",BlobType,Limit(4000),Nullable,Comment("候选列表"))
      t.column("TIMEUSED",IntegerType,Limit(10),Nullable,Comment("耗时(秒)"))
      t.column("MAXCANDNUM",IntegerType,Limit(10),Nullable,Comment("最大候选个数"))
      t.column("CURCANDNUM",IntegerType,Limit(10),Nullable,Comment("当前候选个数"))
      t.column("MINSCORE",IntegerType,Limit(10),Nullable,Comment("候选队列最小得分"))
      t.column("STARTKEY1",VarcharType,Limit(32),Nullable,Comment("条码区间1:卡号"))
      t.column("ENDKEY1",VarcharType,Limit(32),Nullable,Comment("条码区间1"))
      t.column("STARTKEY2",VarcharType,Limit(32),Nullable,Comment("条码区间2:卡号"))
      t.column("ENDKEY2",VarcharType,Limit(32),Nullable,Comment("条码区间2"))
      t.column("USERNAME",VarcharType,Limit(32),Nullable,Comment("查询提交者"))
      t.column("USERUNITCODE",VarcharType,Limit(12),Nullable,Comment("查询提交者单位代码"))
      t.column("FINISHTIME",TimestampType,Limit(7),Nullable,Comment("查询完成时间"))
      t.column("COMPUTERIP",VarcharType,Limit(32),Nullable,Comment("提交机器IP"))
      t.column("COMPUTERNAME",VarcharType,Limit(32),Nullable,Comment("提交机器名称"))
      t.column("ORACOMMENT",ClobType,Limit(4000),Nullable,Comment("备注"))
      t.column("MAXSCORE",BigintType,Limit(22),Nullable,Comment("候选队列最大得分"))
      t.column("CREATETIME",TimestampType,Limit(7),Nullable,Comment("创建时间"))
      t.column("BEGINTIME",TimestampType,Limit(7),Nullable,Comment("查询发起时间"))
      t.column("DELETAG",VarcharType,Limit(1),Nullable,Comment("删除标志"))
      t.column("USERID",VarcharType,Limit(32),Nullable,Comment("查询提交者ＩＤ"))
      t.column("SUBMITTSYSTEM",VarcharType,Limit(32),Nullable,Comment("发比对系统"))
      t.column("PRIORITYNEW",SmallintType,Limit(3),Nullable,Comment("8.0的优先级"))
      t.column("HANDLERESULT",SmallintType,Limit(3),Nullable,Comment("处理状态（0：待处理；1：已处理）"))
      t.column("QRYCONDITION_NOSQL_ID",VarcharType,Limit(10),Nullable,Comment("查询条件(比对参数)nosql存储id"))
      t.column("MIC_NOSQL_ID",VarcharType,Limit(10),Nullable,Comment("特征nosql存储id"))
      t.column("CANDHEAD_NOSQL_ID",VarcharType,Limit(10),Nullable,Comment("候选列表头nosql存储id"))
      t.column("CANDLIST_NOSQL_ID",VarcharType,Limit(10),Nullable,Comment("候选列表nosql存储id"))
      t.column("TIME_ELAPSED",BigintType,Limit(22),Nullable,Comment("比对消耗时间(单位：毫秒)"))
      t.column("RECORD_NUM_MATCHED",BigintType,Limit(22),Nullable,Comment("总共参入比对的记录数 (单位为:卡、案件)"))
      t.column("MATCH_PROGRESS",SmallintType,Limit(3),Nullable,Comment("比对进度"))
      t.column("MESSAGETAG",SmallintType,Limit(1),Nullable,Comment("消息标识1:已登记 (null)空值:未登记"))
      t.column("OVERTIMETAG",SmallintType,Limit(1),Nullable,Comment("比对超时标识:(null)空值:未超时;1:已超时"))
    }
    sequence("GAFIS_CASE_FINGER_PALM_SEQ")
    sequence("GAFIS_CASE_SID_SEQ")

  }

  def down() {
    dropTable("GAFIS_NORMALQUERY_QUERYQUE")
    dropTable("GAFIS_CASE_PALM_MNT")
    dropTable("GAFIS_CASE_PALM")
    dropTable("GAFIS_CASE_FINGER_MNT")
    dropTable("GAFIS_CASE_FINGER")
    dropTable("GAFIS_CASE")
    dropTable("CODE_XCTQFS")
    dropTable("CODE_XCJB")
    dropTable("CODE_RTXYS")
    dropTable("CODE_AY")
    dropTable("CODE_AJZT")
    dropTable("CODE_AJXZ")
    dropTable("CODE_AJLY")
    dropTable("CODE_AJLX")
    dropSequence("GAFIS_CASE_SID_SEQ")
    dropSequence("GAFIS_CASE_FINGER_PALM_SEQ")

  }
}
