package nirvana.hall.webservice.jpa

// Generated 2018-7-24 14:53:35 by Stark Activerecord generator 4.3.1.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import stark.activerecord.services.ActiveRecord;
import stark.activerecord.services.ActiveRecordInstance;

/**
 * LogPuthitresult generated by stark activerecord generator
 */
object LogPuthitresult extends ActiveRecordInstance[LogPuthitresult]

@Entity
@Table(name="LOG_PUTHITRESULT"
)
class LogPuthitresult extends ActiveRecord {


    @Id
    @Column(name = "PK_ID", unique = true, nullable = false, length = 32)
    var pkId: java.lang.String = _
    @Column(name = "USERNAME", length = 20)
    var username: java.lang.String = _
    @Column(name = "HITRESULT_TYPE", length = 2)
    var hitresultType: java.lang.String = _
    @Column(name = "XCZW_XCKYBH", length = 23)
    var xczwXckybh: java.lang.String = _
    @Column(name = "XCZW_XCWZBH", length = 30)
    var xczwXcwzbh: java.lang.String = _
    @Column(name = "NYZW_YSXT_ASJXGRYBH", length = 23)
    var nyzwYsxtAsjxgrybh: java.lang.String = _
    @Column(name = "NYZW_ZZHWDM", length = 2)
    var nyzwZzhwdm: java.lang.String = _
    @Column(name = "ASJFSDD_XZQHDM", precision = 12, scale = 0)
    var asjfsddXzqhdm: java.lang.Long = _
    @Temporal(TemporalType.DATE)
    @Column(name = "CREATETIME", length = 10)
    var createtime: java.util.Date = _
    @Temporal(TemporalType.DATE)
    @Column(name = "UPDATETIME", length = 10)
    var updatetime: java.util.Date = _
    @Column(name = "SENDHITRESULTCOUNT SENDHITRESULTCOUNT")
    var sendHitResultCount: java.lang.Integer = _


	
    def this(pkId:java.lang.String) {
        this()
        this.pkId = pkId
    }
    def this(pkId:java.lang.String, username:java.lang.String, hitresultType:java.lang.String, xczwAsjbh:java.lang.String, xczwYsxtAsjbh:java.lang.String, xczwXckybh:java.lang.String, xczwYsxtXczzhwbh:java.lang.String, xczwXcwzbh:java.lang.String, xczwXczzhwkbh:java.lang.String, nyzwYsxtAsjxgrybh:java.lang.String, nyzwJzrybh:java.lang.String, nyzwAsjxgrybh:java.lang.String, nyzwZzhwkbh:java.lang.String, nyzwZzhwdm:java.lang.String, asjfsddXzqhdm:java.lang.Long, createtime:java.util.Date, updatetime:java.util.Date, fptpath:java.lang.String, returnstatus:java.lang.String, sendHitResultCount:java.lang.Integer) {
       this()
       this.pkId = pkId
       this.username = username
       this.hitresultType = hitresultType
       this.xczwXckybh = xczwXckybh
       this.xczwXcwzbh = xczwXcwzbh
       this.nyzwYsxtAsjxgrybh = nyzwYsxtAsjxgrybh
       this.nyzwZzhwdm = nyzwZzhwdm
       this.asjfsddXzqhdm = asjfsddXzqhdm
       this.createtime = createtime
       this.updatetime = updatetime
       this.sendHitResultCount = sendHitResultCount
    }
   




}


