package nirvana.hall.v70.internal.adapter.nj.jpa

// Generated 2018-3-6 10:50:31 by Stark Activerecord generator 4.3.1.Final


import javax.persistence.{Column, Entity, Id, Table}
import stark.activerecord.services.ActiveRecord
import stark.activerecord.services.ActiveRecordInstance;

/**
 * GafisPersonOtherId generated by stark activerecord generator
 */
object GafisPersonOther extends ActiveRecordInstance[GafisPersonOther]

@Entity
@Table(name = "GAFIS_PERSON_OTHER"
)
class GafisPersonOther extends ActiveRecord {

      @Id
      @Column(name = "UUID", unique = true, nullable = false, length = 32)
      var uuid:java.lang.String =  _
      @Column(name = "PERSON_ID", length = 32)
      var personId:java.lang.String =  _
      @Column(name="GATHER_TYPE", length=2)
      var gatherType:java.lang.String =  _
      @Column(name="FGP", length=2)
      var fgp:java.lang.String =  _
      @Column(name="WIDTH", length=6)
      var width:java.lang.String =  _
      @Column(name="HEIGHT", length=6)
      var height:java.lang.String =  _
      @Column(name="DPI", length=6)
      var dpi:java.lang.String =  _
      @Column(name="COMPRESS_METHOD", length=4)
      var compressMethod:java.lang.String =  _
      @Column(name="NFIQ_QUALITY", length=3)
      var nfiqQuality:java.lang.String =  _
      @Column(name="GATHER_DATA")
      var gatherData: Array[Byte] =  _
      @Column(name="IMAGE_TYPE", length=2)
      var imageType:java.lang.Short =  _


	
    def this(uuid:java.lang.String) {
        this()
        this.uuid = uuid
    }
    def this(uuid:java.lang.String, personId:java.lang.String, gatherType:java.lang.String, fgp:java.lang.String, width:java.lang.String, height:java.lang.String, dpi:java.lang.String, compressMethod:java.lang.String, nfiqQuality:java.lang.String, gatherData: Array[Byte], imageType:java.lang.Short) {
      this()
      this.uuid = uuid
      this.personId = personId
      this.gatherType = gatherType
      this.fgp = fgp
      this.width = width
      this.height = height
      this.dpi = dpi
      this.compressMethod = compressMethod
      this.nfiqQuality = nfiqQuality
      this.gatherData = gatherData
      this.imageType = imageType
    }
}


