package nirvana.hall.v70.internal.adapter.nj.jpa

;
// Generated Jan 6, 2016 6:08:10 PM by hall orm generator 4.3.1.Final


import javax.persistence.{Column, Entity, Id, Table}

import stark.activerecord.services.{ActiveRecord, ActiveRecordInstance}

/**
 * GafisQuery7to6 generated by hall orm 
 */
object GafisQuery7to6 extends ActiveRecordInstance[GafisQuery7to6]

@Entity
@Table(name = "GAFIS_QUERY_7TO6"
)
class GafisQuery7to6 extends ActiveRecord {


  @Id
  @Column(name = "ORA_SID", unique = true, nullable = false)
  var oraSid: Long = _
  @Column(name = "QUERY_ID", nullable = false)
  var queryId: Long = _


  def this(oraSid: Long, queryId: Long) {
    this()
    this.oraSid = oraSid
    this.queryId = queryId
  }


}


