package nirvana.hall.v70.internal.adapter.nj.jpa

// Generated 2017-10-23 11:12:54 by Stark Activerecord generator 4.3.1.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import stark.activerecord.services.ActiveRecord;
import stark.activerecord.services.ActiveRecordInstance;

/**
  * GafisCase generated by stark activerecord generator
  */
object GafisCase extends ActiveRecordInstance[GafisCase]

@Entity
@Table(name = "GAFIS_CASE"
)
class GafisCase extends ActiveRecord {


  @Id
  @Column(name = "CASE_ID", unique = true, nullable = false, length = 23)
  var caseId: java.lang.String = _
  @Column(name = "CARD_ID", length = 23)
  var cardId: java.lang.String = _
  @Column(name = "CASE_CLASS_CODE", length = 6)
  var caseClassCode: java.lang.String = _
  @Temporal(TemporalType.DATE)
  @Column(name = "CASE_OCCUR_DATE", length = 8)
  var caseOccurDate: java.util.Date = _
  @Column(name = "CASE_OCCUR_PLACE_CODE", length = 6)
  var caseOccurPlaceCode: java.lang.String = _
  @Column(name = "CASE_OCCUR_PLACE_DETAIL", length = 256)
  var caseOccurPlaceDetail: java.lang.String = _
  @Column(name = "CASE_BRIEF_DETAIL", length = 1000)
  var caseBriefDetail: java.lang.String = _
  @Column(name = "IS_MURDER", length = 1)
  var isMurder: java.lang.String = _
  @Column(name = "AMOUNT", length = 16)
  var amount: java.lang.String = _
  @Column(name = "EXTRACT_UNIT_CODE", length = 12)
  var extractUnitCode: java.lang.String = _
  @Column(name = "EXTRACT_UNIT_NAME", length = 90)
  var extractUnitName: java.lang.String = _
  @Temporal(TemporalType.DATE)
  @Column(name = "EXTRACT_DATE", length = 8)
  var extractDate: java.util.Date = _
  @Column(name = "EXTRACTOR", length = 30)
  var extractor: java.lang.String = _
  @Column(name = "SUSPICIOUS_AREA_CODE", length = 6)
  var suspiciousAreaCode: java.lang.String = _
  @Column(name = "CASE_STATE", length = 2)
  var caseState: java.lang.String = _
  @Column(name = "INPUTPSN", length = 32)
  var inputpsn: java.lang.String = _
  @Temporal(TemporalType.DATE)
  @Column(name = "INPUTTIME", length = 8)
  var inputtime: java.util.Date = _
  @Column(name = "MODIFIEDPSN", length = 32)
  var modifiedpsn: java.lang.String = _
  @Temporal(TemporalType.DATE)
  @Column(name = "MODIFIEDTIME", length = 8)
  var modifiedtime: java.util.Date = _
  @Column(name = "DELETAG", length = 1)
  var deletag: java.lang.String = _
  @Column(name = "BROKEN_STATUS", precision = 3, scale = 0)
  var brokenStatus: java.lang.Short = _
  @Column(name = "CASE_SOURCE", length = 2)
  var caseSource: java.lang.String = _
  @Column(name = "CREATE_UNIT_CODE", length = 12)
  var createUnitCode: java.lang.String = _
  @Column(name = "ASSIST_LEVEL", length = 1)
  var assistLevel: java.lang.String = _
  @Column(name = "IS_CHECKED", length = 1)
  var isChecked: java.lang.String = _
  @Column(name = "SID")
  var sid: java.lang.Long = _
  @Column(name = "ASSIST_BONUS", length = 7)
  var assistBonus: java.lang.String = _
  @Column(name = "ASSIST_DEPT_CODE", length = 12)
  var assistDeptCode: java.lang.String = _
  @Column(name = "ASSIST_DEPT_NAME", length = 70)
  var assistDeptName: java.lang.String = _
  @Column(name = "ASSIST_DATE", length = 8)
  var assistDate: java.lang.String = _
  @Column(name = "ASSIST_SIGN", length = 1)
  var assistSign: java.lang.String = _
  @Column(name = "ASSIST_REVOKE_SIGN", length = 1)
  var assistRevokeSign: java.lang.String = _
  @Column(name = "CS_NO", length = 23)
  var csNo: java.lang.String = _
  @Column(name = "PSIS_NO", length = 23)
  var psisNo: java.lang.String = _
  @Column(name = "THAN_STATE_TL", length = 1)
  var thanStateTl: java.lang.String = _
  @Column(name = "THAN_STATE_LT", length = 1)
  var thanStateLt: java.lang.String = _
  @Column(name = "THAN_STATE_LL", length = 1)
  var thanStateLl: java.lang.String = _
  @Column(name = "SEQ", scale = 0)
  var seq: java.lang.Long = _
  @Column(name = "REMARK")
  var remark: java.lang.String = _
  @Column(name = "CASE_CLASS_CODE2", length = 6)
  var caseClassCode2: java.lang.String = _
  @Column(name = "CASE_CLASS_CODE3", length = 6)
  var caseClassCode3: java.lang.String = _
  @Column(name = "SUSPICIOUS_AREA_CODE2", length = 6)
  var suspiciousAreaCode2: java.lang.String = _
  @Column(name = "SUSPICIOUS_AREA_CODE3", length = 6)
  var suspiciousAreaCode3: java.lang.String = _
  @Column(name="INPUT_USERNAME", length=60)
  var inputUsername:java.lang.String =  _
  @Column(name="MODIFY_USERNAME", length=60)
  var modifyUsername:java.lang.String =  _
  @Column(name="MODIFY_UNIT_CODE", length=12)
  var modifyUnitCode:java.lang.String =  _
  @Column(name="DATA_STATUS", length=18)
  var dataStatus:java.lang.String =  _
  @Temporal(TemporalType.DATE)
  @Column(name="REPORT_TIME", length=8)
  var reportTime:java.util.Date =  _


  def this(caseId: java.lang.String) {
    this()
    this.caseId = caseId
  }

  def this(caseId: java.lang.String, cardId: java.lang.String, caseClassCode: java.lang.String, caseOccurDate: java.util.Date, caseOccurPlaceCode: java.lang.String, caseOccurPlaceDetail: java.lang.String, caseBriefDetail: java.lang.String, isMurder: java.lang.String, amount: java.lang.String, extractUnitCode: java.lang.String, extractUnitName: java.lang.String, extractDate: java.util.Date, extractor: java.lang.String, suspiciousAreaCode: java.lang.String, caseState: java.lang.String, inputpsn: java.lang.String, inputtime: java.util.Date, modifiedpsn: java.lang.String, modifiedtime: java.util.Date, deletag: java.lang.String, brokenStatus: java.lang.Short, caseSource: java.lang.String, createUnitCode: java.lang.String, assistLevel: java.lang.String, isChecked: java.lang.String, sid: java.lang.Long, assistBonus: java.lang.String, assistDeptCode: java.lang.String, assistDeptName: java.lang.String, assistDate: java.lang.String, assistSign: java.lang.String, assistRevokeSign: java.lang.String, csNo: java.lang.String, psisNo: java.lang.String, thanStateTl: java.lang.String, thanStateLt: java.lang.String, thanStateLl: java.lang.String, seq: java.lang.Long, remark: java.lang.String, caseClassCode2: java.lang.String, caseClassCode3: java.lang.String, suspiciousAreaCode2: java.lang.String, suspiciousAreaCode3: java.lang.String, inputUsername:java.lang.String,modifyUsername:java.lang.String,modifyUnitCode:java.lang.String,dataStatus:java.lang.String,reportTime:java.util.Date) {
    this()
    this.caseId = caseId
    this.cardId = cardId
    this.caseClassCode = caseClassCode
    this.caseOccurDate = caseOccurDate
    this.caseOccurPlaceCode = caseOccurPlaceCode
    this.caseOccurPlaceDetail = caseOccurPlaceDetail
    this.caseBriefDetail = caseBriefDetail
    this.isMurder = isMurder
    this.amount = amount
    this.extractUnitCode = extractUnitCode
    this.extractUnitName = extractUnitName
    this.extractDate = extractDate
    this.extractor = extractor
    this.suspiciousAreaCode = suspiciousAreaCode
    this.caseState = caseState
    this.inputpsn = inputpsn
    this.inputtime = inputtime
    this.modifiedpsn = modifiedpsn
    this.modifiedtime = modifiedtime
    this.deletag = deletag
    this.brokenStatus = brokenStatus
    this.caseSource = caseSource
    this.createUnitCode = createUnitCode
    this.assistLevel = assistLevel
    this.isChecked = isChecked
    this.sid = sid
    this.assistBonus = assistBonus
    this.assistDeptCode = assistDeptCode
    this.assistDeptName = assistDeptName
    this.assistDate = assistDate
    this.assistSign = assistSign
    this.assistRevokeSign = assistRevokeSign
    this.csNo = csNo
    this.psisNo = psisNo
    this.thanStateTl = thanStateTl
    this.thanStateLt = thanStateLt
    this.thanStateLl = thanStateLl
    this.seq = seq
    this.remark = remark
    this.caseClassCode2 = caseClassCode2
    this.caseClassCode3 = caseClassCode3
    this.suspiciousAreaCode2 = suspiciousAreaCode2
    this.suspiciousAreaCode3 = suspiciousAreaCode3
    this.inputUsername = inputUsername
    this.modifyUsername = modifyUsername
    this.modifyUnitCode = modifyUnitCode
    this.dataStatus = dataStatus
    this.reportTime = reportTime
  }


}


