package nirvana.hall.v70.internal.adapter.nj.jpa

// Generated 2017-10-23 11:12:54 by Stark Activerecord generator 4.3.1.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import stark.activerecord.services.ActiveRecord;
import stark.activerecord.services.ActiveRecordInstance;

/**
  * GafisLogicDbCase generated by stark activerecord generator
  */
object GafisLogicDbCase extends ActiveRecordInstance[GafisLogicDbCase]

@Entity
@Table(name = "GAFIS_LOGIC_DB_CASE"
)
class GafisLogicDbCase extends ActiveRecord {


  @Id
  @Column(name = "PK_ID", unique = true, nullable = false, length = 32)
  var pkId: java.lang.String = _
  @Column(name = "LOGIC_DB_PKID", length = 32)
  var logicDbPkid: java.lang.String = _
  @Column(name = "CASE_PKID", length = 32)
  var casePkid: java.lang.String = _


  def this(pkId: java.lang.String) {
    this()
    this.pkId = pkId
  }

  def this(pkId: java.lang.String, logicDbPkid: java.lang.String, casePkid: java.lang.String) {
    this()
    this.pkId = pkId
    this.logicDbPkid = logicDbPkid
    this.casePkid = casePkid
  }


}


