/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nirvana_hall_extractor_jni_NativeExtractor */

#ifndef _Included_nirvana_hall_extractor_jni_NativeExtractor
#define _Included_nirvana_hall_extractor_jni_NativeExtractor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nirvana_hall_extractor_jni_NativeExtractor
 * Method:    ExtractMNT_All
 * Signature: ([B[B[BBBB)V
 */
JNIEXPORT void JNICALL Java_nirvana_hall_extractor_jni_NativeExtractor_ExtractMNT_1All
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jbyte, jbyte, jbyte);

/*
 * Class:     nirvana_hall_extractor_jni_NativeExtractor
 * Method:    ExtractMNT_AllWithNewFeature
 * Signature: ([B[B[BBBB)V
 */
JNIEXPORT void JNICALL Java_nirvana_hall_extractor_jni_NativeExtractor_ExtractMNT_1AllWithNewFeature
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jbyte, jbyte, jbyte);

/*
 * Class:     nirvana_hall_extractor_jni_NativeExtractor
 * Method:    ConvertFPTLatentMNT2Std
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_nirvana_hall_extractor_jni_NativeExtractor_ConvertFPTLatentMNT2Std
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     nirvana_hall_extractor_jni_NativeExtractor
 * Method:    GAFIS_MntDispToMntStd
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_nirvana_hall_extractor_jni_NativeExtractor_GAFIS_1MntDispToMntStd
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     nirvana_hall_extractor_jni_NativeExtractor
 * Method:    GAFIS_MntStdToMntDisp
 * Signature: ([B[BI)V
 */
JNIEXPORT void JNICALL Java_nirvana_hall_extractor_jni_NativeExtractor_GAFIS_1MntStdToMntDisp
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint);

/*
 * Class:     nirvana_hall_extractor_jni_NativeExtractor
 * Method:    ConvertMntOldToNew
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_nirvana_hall_extractor_jni_NativeExtractor_ConvertMntOldToNew
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
