/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nirvana_hall_extractor_jni_NativeExtractor */

#ifndef _Included_nirvana_hall_extractor_jni_NativeExtractor
#define _Included_nirvana_hall_extractor_jni_NativeExtractor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nirvana_hall_extractor_jni_NativeExtractor
 * Method:    ExtractMNT_All
 * Signature: ([B[BBB)V
 */
JNIEXPORT void JNICALL Java_nirvana_hall_extractor_jni_NativeExtractor_ExtractMNT_1All
  (JNIEnv *, jclass, jbyteArray, jbyteArray,jbyte, jbyte, jbyte);

#ifdef __cplusplus
}
#endif
#endif
