package nirvana.hall.api.jpa.njtxserver

// Generated Feb 27, 2019 5:23:16 PM by Stark Activerecord generator 4.3.1.Final


import javax.persistence._

import stark.activerecord.services.ActiveRecord
import stark.activerecord.services.ActiveRecordInstance;

/**
  * TaskLog generated by stark activerecord generator
  */
object TaskLog extends ActiveRecordInstance[TaskLog]

@Entity
@Table(name = "TASK_LOG")
class TaskLog extends ActiveRecord {

  @Id
  @Column(name = "id", nullable = false, length = 32)
  var id: java.lang.String = _
  @Column(name = "cardid", length = 22)
  var cardid: java.lang.String = _
  @Column(name = "station_code", length = 12)
  var stationCode: java.lang.String = _
  @Column(name = "task_no_six")
  var taskNoSix: java.lang.Integer = _
  @Column(name = "task_no_seven")
  var taskNoSeven: java.lang.Integer = _
  @Column(name = "task_type")
  var taskType: java.lang.Integer = _
  @Column(name = "is_feedback")
  var isFeedback: java.lang.Integer = _
  @Column(name = "init_time", length = 10)
  var initTime: java.util.Date = _


  def this(id: java.lang.String) {
    this()
    this.id = id
  }

  def this(id: java.lang.String, cardid: java.lang.String, stationCode: java.lang.String, taskNoSix: java.lang.Integer, taskNoSeven: java.lang.Integer, taskType: java.lang.Integer, isFeedback: java.lang.Integer, initTime: java.util.Date) {
    this()
    this.id = id
    this.cardid = cardid
    this.stationCode = stationCode
    this.taskNoSix = taskNoSix
    this.taskNoSeven = taskNoSeven
    this.taskType = taskType
    this.isFeedback = isFeedback
    this.initTime = initTime
  }
}


