package nirvana.hall.v70.ln.jpa

// Generated 2017-10-23 12:04:36 by Stark Activerecord generator 4.3.1.Final


import javax.persistence._

import stark.activerecord.services.{ActiveRecord, ActiveRecordInstance};

/**
  * GafisCheckinInfo generated by stark activerecord generator
  */
object GafisCheckinInfo extends ActiveRecordInstance[GafisCheckinInfo]

@Entity
@Table(name = "GAFIS_CHECKIN_INFO"
)
class GafisCheckinInfo extends ActiveRecord {


  @Id
  @Column(name = "PK_ID", unique = true, nullable = false, length = 32)
  var pkId: java.lang.String = _
  @Column(name = "CODE", length = 25)
  var code: java.lang.String = _
  @Column(name = "TCODE", length = 25)
  var tcode: java.lang.String = _
  @Column(name = "QUERYTYPE")
  var querytype: java.lang.String = _
  @Temporal(TemporalType.DATE)
  @Column(name = "REGISTER_TIME", length = 8)
  var registerTime: java.util.Date = _
  @Column(name = "REGISTER_USER", length = 32)
  var registerUser: java.lang.String = _
  @Column(name = "REGISTER_ORG", length = 32)
  var registerOrg: java.lang.String = _
  @Column(name = "HITPOSSIBILITY", precision = 3, scale = 0)
  var hitpossibility: java.lang.Short = _
  @Column(name = "PRIORITY", precision = 3, scale = 0)
  var priority: java.lang.Short = _
  @Column(name = "REVIEW_STATUS", precision = 2, scale = 0)
  var reviewStatus: java.lang.Byte = _
  @Column(name = "REVIEW_BOUT", precision = 1, scale = 0)
  var reviewBout: java.lang.Boolean = _
  @Column(name = "APPEAL_STATUS", precision = 1, scale = 0)
  var appealStatus: java.lang.Boolean = _
  @Column(name = "CONFIRM_STATUS", precision = 3, scale = 0)
  var confirmStatus: java.lang.Short = _
  @Column(name = "CONFIRM_USER", length = 32)
  var confirmUser: java.lang.String = _
  @Temporal(TemporalType.DATE)
  @Column(name = "CONFIRM_TIME", length = 8)
  var confirmTime: java.util.Date = _
  @Column(name = "QUERY_UUID", length = 32)
  var queryUuid: java.lang.String = _
  @Column(name = "REVIEW_ORG", length = 32)
  var reviewOrg: java.lang.String = _
  @Column(name = "RANK", precision = 6, scale = 0)
  var rank: java.lang.Integer = _
  @Column(name = "FRACTION", precision = 6, scale = 0)
  var fraction: java.lang.Integer = _
  @Column(name = "FGP", length = 20)
  var fgp: java.lang.String = _
  @Column(name = "CONFIRM_OPINION", length = 200)
  var confirmOpinion: java.lang.String = _
  @Column(name = "CARD_TYPE1")
  var cardType1: java.lang.Long = _
  @Column(name = "CARD_TYPE2")
  var cardType2: java.lang.Long = _
  @Temporal(TemporalType.DATE)
  @Column(name = "LAST_HANDLE_DATE", length = 8)
  var lastHandleDate: java.util.Date = _
  @Column(name = "OPERATETYPE")
  var operatetype: java.lang.Long = _
  @Column(name = "CK_SOURCE", length = 1)
  var ckSource: java.lang.String = _
  @Column(name = "PASS_STATUS", precision = 1, scale = 0)
  var passStatus: java.lang.Boolean = _
  @Column(name = "PERSON_CONTR_DELTAG", length = 1)
  var personContrDeltag: java.lang.String = _
  @Column(name = "REMOVEDELTAG", length = 1)
  var removedeltag: java.lang.String = _


  def this(pkId: java.lang.String) {
    this()
    this.pkId = pkId
  }

  def this(pkId: java.lang.String, code: java.lang.String, tcode: java.lang.String, querytype: java.lang.String, registerTime: java.util.Date, registerUser: java.lang.String, registerOrg: java.lang.String, hitpossibility: java.lang.Short, priority: java.lang.Short, reviewStatus: java.lang.Byte, reviewBout: java.lang.Boolean, appealStatus: java.lang.Boolean, confirmStatus: java.lang.Short, confirmUser: java.lang.String, confirmTime: java.util.Date, queryUuid: java.lang.String, reviewOrg: java.lang.String, rank: java.lang.Integer, fraction: java.lang.Integer, fgp: java.lang.String, confirmOpinion: java.lang.String, cardType1: java.lang.Long, cardType2: java.lang.Long, lastHandleDate: java.util.Date, operatetype: java.lang.Long, ckSource: java.lang.String, passStatus: java.lang.Boolean, personContrDeltag: java.lang.String, removedeltag: java.lang.String) {
    this()
    this.pkId = pkId
    this.code = code
    this.tcode = tcode
    this.querytype = querytype
    this.registerTime = registerTime
    this.registerUser = registerUser
    this.registerOrg = registerOrg
    this.hitpossibility = hitpossibility
    this.priority = priority
    this.reviewStatus = reviewStatus
    this.reviewBout = reviewBout
    this.appealStatus = appealStatus
    this.confirmStatus = confirmStatus
    this.confirmUser = confirmUser
    this.confirmTime = confirmTime
    this.queryUuid = queryUuid
    this.reviewOrg = reviewOrg
    this.rank = rank
    this.fraction = fraction
    this.fgp = fgp
    this.confirmOpinion = confirmOpinion
    this.cardType1 = cardType1
    this.cardType2 = cardType2
    this.lastHandleDate = lastHandleDate
    this.operatetype = operatetype
    this.ckSource = ckSource
    this.passStatus = passStatus
    this.personContrDeltag = personContrDeltag
    this.removedeltag = removedeltag
  }


}


