package nirvana.hall.webservice.internal.greathand.jpa

// Generated 2019-5-13 10:24:09 by Stark Activerecord generator 4.3.1.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import stark.activerecord.services.ActiveRecord;
import stark.activerecord.services.ActiveRecordInstance;

/**
  * Tpcardimgmnt generated by stark activerecord generator
  */
object Tpcardimgmnt extends ActiveRecordInstance[Tpcardimgmnt]

@Entity
@Table(name = "TPCARDIMGMNT"
)
class Tpcardimgmnt extends ActiveRecord {


  @Id
  @Column(name = "id", unique = true, nullable = false, length = 32)
  var id: java.lang.String = _
  @Column(name = "personid", length = 32)
  var personid: java.lang.String = _
  @Column(name = "imgdata")
  var imgData: Array[Byte] = _
  @Column(name = "flag")
  var flag: java.lang.Integer = _
  @Column(name = "createtime", length = 10)
  var createtime: java.util.Date = _
  @Column(name = "updatetime", length = 10)
  var updatetime: java.util.Date = _


  def this(personid: java.lang.String) {
    this()
    this.personid = personid
  }

  def this(id: java.lang.String,personid: java.lang.String, imgData: Array[Byte], flag: java.lang.Integer, createtime: java.util.Date, updatetime: java.util.Date) {
    this()
    this.id = id
    this.personid = personid
    this.imgData = imgData
    this.flag = flag
    this.createtime = createtime
    this.updatetime = updatetime
  }


}


