package nirvana.hall.api.jpa

;
// Generated Jan 6, 2016 6:08:10 PM by hall orm generator 4.3.1.Final


import javax.persistence.{Column, Entity, Id, Table, Temporal, TemporalType}

import nirvana.hall.orm.services.{ActiveRecord, ActiveRecordInstance};

/**
 * GafisNormalqueryQueryque generated by hall orm 
 */
object GafisNormalqueryQueryque extends ActiveRecordInstance[GafisNormalqueryQueryque]

@Entity
@Table(name = "GAFIS_NORMALQUERY_QUERYQUE"
)
class GafisNormalqueryQueryque extends ActiveRecord {


  @Id
  @Column(name = "PK_ID", unique = true, nullable = false, length = 32)
  var pkId: java.lang.String = _
  @Column(name = "ORA_SID")
  var oraSid: java.lang.Long = _
  @Column(name = "KEYID", length = 25)
  var keyid: java.lang.String = _
  @Column(name = "QUERYTYPE")
  var querytype: java.lang.Short = _
  @Column(name = "STATUS")
  var status: java.lang.Short = _
  @Column(name = "PRIORITY")
  var priority: java.lang.Short = _
  @Column(name = "HITPOSSIBILITY")
  var hitpossibility: java.lang.Short = _
  @Column(name = "VERIFYRESULT")
  var verifyresult: java.lang.Short = _
  @Column(name = "FLAG")
  var flag: java.lang.Short = _
  @Column(name = "FLAGC")
  var flagc: java.lang.Short = _
  @Column(name = "FLAGD")
  var flagd: java.lang.Short = _
  @Column(name = "FLAGE")
  var flage: java.lang.Short = _
  @Column(name = "FLAGG")
  var flagg: java.lang.Short = _
  @Column(name = "QRYCONDITION")
  var qrycondition: java.sql.Blob = _
  @Column(name = "MIC")
  var mic: java.sql.Blob = _
  @Column(name = "TEXTSQL")
  var textsql: java.sql.Clob = _
  @Column(name = "CANDHEAD")
  var candhead: java.sql.Blob = _
  @Column(name = "CANDLIST")
  var candlist: java.sql.Blob = _
  @Column(name = "TIMEUSED")
  var timeused: java.lang.Integer = _
  @Column(name = "MAXCANDNUM")
  var maxcandnum: java.lang.Integer = _
  @Column(name = "CURCANDNUM")
  var curcandnum: java.lang.Integer = _
  @Column(name = "MINSCORE")
  var minscore: java.lang.Integer = _
  @Column(name = "STARTKEY1", length = 32)
  var startkey1: java.lang.String = _
  @Column(name = "ENDKEY1", length = 32)
  var endkey1: java.lang.String = _
  @Column(name = "STARTKEY2", length = 32)
  var startkey2: java.lang.String = _
  @Column(name = "ENDKEY2", length = 32)
  var endkey2: java.lang.String = _
  @Column(name = "USERNAME", length = 32)
  var username: java.lang.String = _
  @Column(name = "USERUNITCODE", length = 12)
  var userunitcode: java.lang.String = _
  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "FINISHTIME", length = 23)
  var finishtime: java.util.Date = _
  @Column(name = "COMPUTERIP", length = 32)
  var computerip: java.lang.String = _
  @Column(name = "COMPUTERNAME", length = 32)
  var computername: java.lang.String = _
  @Column(name = "ORACOMMENT")
  var oracomment: java.sql.Clob = _
  @Column(name = "MAXSCORE")
  var maxscore: java.lang.Long = _
  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "CREATETIME", length = 23)
  var createtime: java.util.Date = _
  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "BEGINTIME", length = 23)
  var begintime: java.util.Date = _
  @Column(name = "DELETAG", length = 1)
  var deletag: java.lang.String = _
  @Column(name = "USERID", length = 32)
  var userid: java.lang.String = _
  @Column(name = "SUBMITTSYSTEM", length = 32)
  var submittsystem: java.lang.String = _
  @Column(name = "PRIORITYNEW")
  var prioritynew: java.lang.Short = _
  @Column(name = "HANDLERESULT")
  var handleresult: java.lang.Short = _
  @Column(name = "QRYCONDITION_NOSQL_ID", length = 10)
  var qryconditionNosqlId: java.lang.String = _
  @Column(name = "MIC_NOSQL_ID", length = 10)
  var micNosqlId: java.lang.String = _
  @Column(name = "CANDHEAD_NOSQL_ID", length = 10)
  var candheadNosqlId: java.lang.String = _
  @Column(name = "CANDLIST_NOSQL_ID", length = 10)
  var candlistNosqlId: java.lang.String = _
  @Column(name = "TIME_ELAPSED")
  var timeElapsed: java.lang.Long = _
  @Column(name = "RECORD_NUM_MATCHED")
  var recordNumMatched: java.lang.Long = _
  @Column(name = "MATCH_PROGRESS")
  var matchProgress: java.lang.Short = _
  @Column(name = "MESSAGETAG")
  var messagetag: java.lang.Short = _
  @Column(name = "OVERTIMETAG")
  var overtimetag: java.lang.Short = _
  @Column(name = "SYNC_TARGET_SID", length = 20)
  var syncTargetSid: java.lang.String = _


  def this(pkId: java.lang.String) {
    this()
    this.pkId = pkId
  }

  def this(pkId: java.lang.String, oraSid: java.lang.Long, keyid: java.lang.String, querytype: java.lang.Short, status: java.lang.Short, priority: java.lang.Short, hitpossibility: java.lang.Short, verifyresult: java.lang.Short, flag: java.lang.Short, flagc: java.lang.Short, flagd: java.lang.Short, flage: java.lang.Short, flagg: java.lang.Short, qrycondition: java.sql.Blob, mic: java.sql.Blob, textsql: java.sql.Clob, candhead: java.sql.Blob, candlist: java.sql.Blob, timeused: java.lang.Integer, maxcandnum: java.lang.Integer, curcandnum: java.lang.Integer, minscore: java.lang.Integer, startkey1: java.lang.String, endkey1: java.lang.String, startkey2: java.lang.String, endkey2: java.lang.String, username: java.lang.String, userunitcode: java.lang.String, finishtime: java.util.Date, computerip: java.lang.String, computername: java.lang.String, oracomment: java.sql.Clob, maxscore: java.lang.Long, createtime: java.util.Date, begintime: java.util.Date, deletag: java.lang.String, userid: java.lang.String, submittsystem: java.lang.String, prioritynew: java.lang.Short, handleresult: java.lang.Short, qryconditionNosqlId: java.lang.String, micNosqlId: java.lang.String, candheadNosqlId: java.lang.String, candlistNosqlId: java.lang.String, timeElapsed: java.lang.Long, recordNumMatched: java.lang.Long, matchProgress: java.lang.Short, messagetag: java.lang.Short, overtimetag: java.lang.Short, syncTargetSid: java.lang.String) {
    this()
    this.pkId = pkId
    this.oraSid = oraSid
    this.keyid = keyid
    this.querytype = querytype
    this.status = status
    this.priority = priority
    this.hitpossibility = hitpossibility
    this.verifyresult = verifyresult
    this.flag = flag
    this.flagc = flagc
    this.flagd = flagd
    this.flage = flage
    this.flagg = flagg
    this.qrycondition = qrycondition
    this.mic = mic
    this.textsql = textsql
    this.candhead = candhead
    this.candlist = candlist
    this.timeused = timeused
    this.maxcandnum = maxcandnum
    this.curcandnum = curcandnum
    this.minscore = minscore
    this.startkey1 = startkey1
    this.endkey1 = endkey1
    this.startkey2 = startkey2
    this.endkey2 = endkey2
    this.username = username
    this.userunitcode = userunitcode
    this.finishtime = finishtime
    this.computerip = computerip
    this.computername = computername
    this.oracomment = oracomment
    this.maxscore = maxscore
    this.createtime = createtime
    this.begintime = begintime
    this.deletag = deletag
    this.userid = userid
    this.submittsystem = submittsystem
    this.prioritynew = prioritynew
    this.handleresult = handleresult
    this.qryconditionNosqlId = qryconditionNosqlId
    this.micNosqlId = micNosqlId
    this.candheadNosqlId = candheadNosqlId
    this.candlistNosqlId = candlistNosqlId
    this.timeElapsed = timeElapsed
    this.recordNumMatched = recordNumMatched
    this.matchProgress = matchProgress
    this.messagetag = messagetag
    this.overtimetag = overtimetag
    this.syncTargetSid = syncTargetSid
  }


}


