package nirvana.hall.api.jpa

;
// Generated Jan 6, 2016 6:08:10 PM by hall orm generator 4.3.1.Final


import javax.persistence.{Column, Entity, Id, Table, Temporal, TemporalType}

import nirvana.hall.orm.services.{ActiveRecord, ActiveRecordInstance};

/**
 * GafisControrcapturePerson generated by hall orm 
 */
object GafisControrcapturePerson extends ActiveRecordInstance[GafisControrcapturePerson]

@Entity
@Table(name = "GAFIS_CONTRORCAPTURE_PERSON"
)
class GafisControrcapturePerson extends ActiveRecord {


  @Id
  @Column(name = "PKID", unique = true, nullable = false, length = 32)
  var pkid: java.lang.String = _
  @Column(name = "PERSONID", length = 32)
  var personid: java.lang.String = _
  @Column(name = "APPROVAL_TYPE", length = 1)
  var approvalType: java.lang.String = _
  @Column(name = "APPROVAL_PERSON", length = 32)
  var approvalPerson: java.lang.String = _
  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "APPROVAL_DATE", length = 23)
  var approvalDate: java.util.Date = _
  @Column(name = "APPROVAL_REMARK", length = 512)
  var approvalRemark: java.lang.String = _
  @Column(name = "APPROVAL_RESULT", length = 1)
  var approvalResult: java.lang.String = _


  def this(pkid: java.lang.String) {
    this()
    this.pkid = pkid
  }

  def this(pkid: java.lang.String, personid: java.lang.String, approvalType: java.lang.String, approvalPerson: java.lang.String, approvalDate: java.util.Date, approvalRemark: java.lang.String, approvalResult: java.lang.String) {
    this()
    this.pkid = pkid
    this.personid = personid
    this.approvalType = approvalType
    this.approvalPerson = approvalPerson
    this.approvalDate = approvalDate
    this.approvalRemark = approvalRemark
    this.approvalResult = approvalResult
  }


}


