package nirvana.hall.api.jpa

;
// Generated Jan 6, 2016 6:08:10 PM by hall orm generator 4.3.1.Final


import javax.persistence.{Column, Entity, Id, Table}

import nirvana.hall.orm.services.{ActiveRecord, ActiveRecordInstance};

/**
 * GafisGatherTypeNode generated by hall orm 
 */
object GafisGatherTypeNode extends ActiveRecordInstance[GafisGatherTypeNode]

@Entity
@Table(name = "GAFIS_GATHER_TYPE_NODE"
)
class GafisGatherTypeNode extends ActiveRecord {


  @Id
  @Column(name = "PK_ID", unique = true, nullable = false, length = 32)
  var pkId: java.lang.String = _
  @Column(name = "TYPE_ID", nullable = false, length = 32)
  var typeId: java.lang.String = _
  @Column(name = "NODE_ID", length = 32)
  var nodeId: java.lang.String = _
  @Column(name = "NODE_ORD")
  var nodeOrd: java.lang.Long = _
  @Column(name = "IS_SKIP")
  var isSkip: java.lang.Short = _
  @Column(name = "DEPART_ID", length = 32)
  var departId: java.lang.String = _


  def this(pkId: java.lang.String, typeId: java.lang.String) {
    this()
    this.pkId = pkId
    this.typeId = typeId
  }

  def this(pkId: java.lang.String, typeId: java.lang.String, nodeId: java.lang.String, nodeOrd: java.lang.Long, isSkip: java.lang.Short, departId: java.lang.String) {
    this()
    this.pkId = pkId
    this.typeId = typeId
    this.nodeId = nodeId
    this.nodeOrd = nodeOrd
    this.isSkip = isSkip
    this.departId = departId
  }


}


