package nirvana.hall.api.jpa;
// Generated Jan 6, 2016 6:08:10 PM by hall orm generator 4.3.1.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import nirvana.hall.orm.services.ActiveRecord;
import nirvana.hall.orm.services.ActiveRecordInstance;

/**
 * GafisQuery7to6 generated by hall orm 
 */
object GafisQuery7to6 extends ActiveRecordInstance[GafisQuery7to6]

@Entity
@Table(name="GAFIS_QUERY_7TO6"
)
class GafisQuery7to6 extends ActiveRecord {


      @Id 
         @Column(name="ORA_SID", unique=true, nullable=false)
     var oraSid:long =  _
          @Column(name="QUERY_ID", nullable=false)
     var queryId:long =  _


    def this(oraSid:long, queryId:long) {
       this()
       this.oraSid = oraSid
       this.queryId = queryId
    }
   




}


