package nirvana.hall.api.jpa

;
// Generated Jan 6, 2016 6:08:10 PM by hall orm generator 4.3.1.Final


import javax.persistence.{Column, Entity, Id, Table, Temporal, TemporalType}

import nirvana.hall.orm.services.{ActiveRecord, ActiveRecordInstance};

/**
 * GafisGatherIdcard generated by hall orm 
 */
object GafisGatherIdcard extends ActiveRecordInstance[GafisGatherIdcard]

@Entity
@Table(name = "GAFIS_GATHER_IDCARD"
)
class GafisGatherIdcard extends ActiveRecord {


  @Id
  @Column(name = "PK_ID", unique = true, nullable = false, length = 32)
  var pkId: java.lang.String = _
  @Column(name = "PERSONID", length = 23)
  var personid: java.lang.String = _
  @Column(name = "FGP_CODE", length = 20)
  var fgpCode: java.lang.String = _
  @Column(name = "GATHER_DATA")
  var gatherData: java.sql.Blob = _
  @Column(name = "INPUTPSN", length = 32)
  var inputpsn: java.lang.String = _
  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "INPUTTIME", length = 23)
  var inputtime: java.util.Date = _
  @Column(name = "MODIFIEDPSN", length = 32)
  var modifiedpsn: java.lang.String = _
  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "MODIFIEDTIME", length = 23)
  var modifiedtime: java.util.Date = _
  @Column(name = "DELETAG", length = 1)
  var deletag: java.lang.String = _
  @Column(name = "GATHERDATANOSQLID", length = 10)
  var gatherdatanosqlid: java.lang.String = _


  def this(pkId: java.lang.String) {
    this()
    this.pkId = pkId
  }

  def this(pkId: java.lang.String, personid: java.lang.String, fgpCode: java.lang.String, gatherData: java.sql.Blob, inputpsn: java.lang.String, inputtime: java.util.Date, modifiedpsn: java.lang.String, modifiedtime: java.util.Date, deletag: java.lang.String, gatherdatanosqlid: java.lang.String) {
    this()
    this.pkId = pkId
    this.personid = personid
    this.fgpCode = fgpCode
    this.gatherData = gatherData
    this.inputpsn = inputpsn
    this.inputtime = inputtime
    this.modifiedpsn = modifiedpsn
    this.modifiedtime = modifiedtime
    this.deletag = deletag
    this.gatherdatanosqlid = gatherdatanosqlid
  }


}


