package nirvana.hall.api.jpa;
// Generated Jan 6, 2016 6:08:10 PM by hall orm generator 4.3.1.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import nirvana.hall.orm.services.ActiveRecord;
import nirvana.hall.orm.services.ActiveRecordInstance;

/**
 * GafisGatherSpecialty generated by hall orm 
 */
object GafisGatherSpecialty extends ActiveRecordInstance[GafisGatherSpecialty]

@Entity
@Table(name="GAFIS_GATHER_SPECIALTY"
)
class GafisGatherSpecialty extends ActiveRecord {


      @Id 
         @Column(name="PK_ID", unique=true, nullable=false, length=32)
     var pkId:java.lang.String =  _
          @Column(name="PERSONID", length=23)
     var personid:java.lang.String =  _
          @Column(name="SPECIALTY_CODE", length=2)
     var specialtyCode:java.lang.String =  _
          @Column(name="INPUTPSN", length=32)
     var inputpsn:java.lang.String =  _
     @Temporal(TemporalType.TIMESTAMP)     @Column(name="INPUTTIME", length=23)
     var inputtime:java.util.Date =  _
          @Column(name="MODIFIEDPSN", length=32)
     var modifiedpsn:java.lang.String =  _
     @Temporal(TemporalType.TIMESTAMP)     @Column(name="MODIFIEDTIME", length=23)
     var modifiedtime:java.util.Date =  _
          @Column(name="DELETAG", length=1)
     var deletag:java.lang.String =  _


	
    def this(pkId:java.lang.String) {
        this()
        this.pkId = pkId
    }
    def this(pkId:java.lang.String, personid:java.lang.String, specialtyCode:java.lang.String, inputpsn:java.lang.String, inputtime:java.util.Date, modifiedpsn:java.lang.String, modifiedtime:java.util.Date, deletag:java.lang.String) {
       this()
       this.pkId = pkId
       this.personid = personid
       this.specialtyCode = specialtyCode
       this.inputpsn = inputpsn
       this.inputtime = inputtime
       this.modifiedpsn = modifiedpsn
       this.modifiedtime = modifiedtime
       this.deletag = deletag
    }
   




}


