package nirvana.hall.api.jpa;
// Generated Jan 6, 2016 6:08:10 PM by hall orm generator 4.3.1.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import nirvana.hall.orm.services.ActiveRecord;
import nirvana.hall.orm.services.ActiveRecordInstance;

/**
 * GafisFingerTextLog generated by hall orm 
 */
object GafisFingerTextLog extends ActiveRecordInstance[GafisFingerTextLog]

@Entity
@Table(name="GAFIS_FINGER_TEXT_LOG"
)
class GafisFingerTextLog extends ActiveRecord {


      @Id 
         @Column(name="PK_ID", unique=true, nullable=false, length=32)
     var pkId:java.lang.String =  _
          @Column(name="USER_ID", length=32)
     var userId:java.lang.String =  _
          @Column(name="USER_NAME", length=90)
     var userName:java.lang.String =  _
          @Column(name="UNIT_CODE", length=12)
     var unitCode:java.lang.String =  _
          @Column(name="UNIT_NAME", length=90)
     var unitName:java.lang.String =  _
          @Column(name="IP", length=15)
     var ip:java.lang.String =  _
          @Column(name="OBJECT_ID", length=32)
     var objectId:java.lang.String =  _
          @Column(name="TABLE_NAME", length=30)
     var tableName:java.lang.String =  _
          @Column(name="OLD_INFO", length=3000)
     var oldInfo:java.lang.String =  _
          @Column(name="NEW_INFO", length=3000)
     var newInfo:java.lang.String =  _
     @Temporal(TemporalType.TIMESTAMP)     @Column(name="CREATE_DATETIME", length=23)
     var createDatetime:java.util.Date =  _


	
    def this(pkId:java.lang.String) {
        this()
        this.pkId = pkId
    }
    def this(pkId:java.lang.String, userId:java.lang.String, userName:java.lang.String, unitCode:java.lang.String, unitName:java.lang.String, ip:java.lang.String, objectId:java.lang.String, tableName:java.lang.String, oldInfo:java.lang.String, newInfo:java.lang.String, createDatetime:java.util.Date) {
       this()
       this.pkId = pkId
       this.userId = userId
       this.userName = userName
       this.unitCode = unitCode
       this.unitName = unitName
       this.ip = ip
       this.objectId = objectId
       this.tableName = tableName
       this.oldInfo = oldInfo
       this.newInfo = newInfo
       this.createDatetime = createDatetime
    }
   




}


