package nirvana.hall.api.jpa;
// Generated Jan 6, 2016 6:08:10 PM by hall orm generator 4.3.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import nirvana.hall.orm.services.ActiveRecord;
import nirvana.hall.orm.services.ActiveRecordInstance;

/**
 * OnlineUser generated by hall orm 
 */
object OnlineUser extends ActiveRecordInstance[OnlineUser]

@Entity
@Table(name="ONLINE_USER"
    , uniqueConstraints = {@UniqueConstraint(columnNames="LOGIN"), @UniqueConstraint(columnNames="TOKEN")} 
)
class OnlineUser extends ActiveRecord {


      @EmbeddedId
         @AttributeOverrides( {
        @AttributeOverride(name="login", column=@Column(name="LOGIN", unique=true, nullable=false, length=50) ), 
        @AttributeOverride(name="loginTime", column=@Column(name="LOGIN_TIME", nullable=false) ), 
        @AttributeOverride(name="latestTime", column=@Column(name="LATEST_TIME", nullable=false) ), 
        @AttributeOverride(name="token", column=@Column(name="TOKEN", unique=true, nullable=false, length=50) ) } )
     var id:nirvana.hall.api.jpa.OnlineUserId =  _


    def this(id:nirvana.hall.api.jpa.OnlineUserId) {
       this()
       this.id = id
    }
   




}


