package nirvana.hall.api.jpa;
// Generated Jan 6, 2016 6:08:10 PM by hall orm generator 4.3.1.Final


import javax.persistence.{Id, Column, Entity, Table}

import nirvana.hall.orm.services.{ActiveRecord, ActiveRecordInstance};

/**
 * OnlineUserId generated by hall orm 
 */
object OnlineUser extends ActiveRecordInstance[OnlineUser]

@Entity
@Table(name="ONLINE_USER")
class OnlineUser extends ActiveRecord {

  @Id
  @Column(name="LOGIN", unique=true, nullable=false, length=50)
  var login:java.lang.String =  _
  @Column(name="LOGIN_TIME", nullable=false)
  var loginTime:Int =  _
  @Column(name="LATEST_TIME", nullable=false)
  var latestTime:Int =  _
  @Column(name="TOKEN", unique=true, nullable=false, length=50)
  var token:java.lang.String =  _


  def this(login:java.lang.String, loginTime:Int, latestTime:Int, token:java.lang.String) {
    this()
    this.login = login
    this.loginTime = loginTime
    this.latestTime = latestTime
    this.token = token
  }

}


