package nirvana.hall.api.jpa;
// Generated Jan 6, 2016 6:08:10 PM by hall orm generator 4.3.1.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import nirvana.hall.orm.services.ActiveRecord;
import nirvana.hall.orm.services.ActiveRecordInstance;

/**
 * SchemaMigrations generated by hall orm 
 */
object SchemaMigrations extends ActiveRecordInstance[SchemaMigrations]

@Entity
@Table(name="SCHEMA_MIGRATIONS"
    , uniqueConstraints = @UniqueConstraint(columnNames="VERSION") 
)
class SchemaMigrations extends ActiveRecord {


      @Id 
         @Column(name="VERSION", unique=true, nullable=false, length=32)
     var version:java.lang.String =  _


    def this(version:java.lang.String) {
       this()
       this.version = version
    }
   




}


