package nirvana.hall.api.jpa

;
// Generated Jan 6, 2016 6:08:10 PM by hall orm generator 4.3.1.Final


import javax.persistence.{Column, Entity, Id, Table}

import nirvana.hall.orm.services.{ActiveRecord, ActiveRecordInstance};

/**
 * SyncStrategy generated by hall orm 
 */
object SyncStrategy extends ActiveRecordInstance[SyncStrategy]

@Entity
@Table(name = "SYNC_STRATEGY"
)
class SyncStrategy extends ActiveRecord {


  @Id
  @Column(name = "PK_ID", unique = true, nullable = false, length = 32)
  var pkId: java.lang.String = _
  @Column(name = "STRATEGY_NAME", length = 20)
  var strategyName: java.lang.String = _
  @Column(name = "STRATEGY_QUERY", length = 500)
  var strategyQuery: java.lang.String = _
  @Column(name = "TYPE", length = 2)
  var typeCol: java.lang.String = _
  @Column(name = "TARGETS", length = 500)
  var targets: java.lang.String = _
  @Column(name = "DELTAG", length = 2)
  var deltag: java.lang.String = _
  @Column(name = "FLAG", length = 2)
  var flag: java.lang.String = _
  @Column(name = "HAS_PALM", length = 2)
  var hasPalm: java.lang.String = _


  def this(pkId: java.lang.String) {
    this()
    this.pkId = pkId
  }

  def this(pkId: java.lang.String, strategyName: java.lang.String, strategyQuery: java.lang.String,

  typeCol: java.lang.String, targets: java.lang.String, deltag: java.lang.String, flag: java.lang.String, hasPalm: java.lang.String)
  {
    this()
    this.pkId = pkId
    this.strategyName = strategyName
    this.strategyQuery = strategyQuery
    this.typeCol = typeCol
    this.targets = targets
    this.deltag = deltag
    this.flag = flag
    this.hasPalm = hasPalm
  }


}


