package nirvana.hall.api.jpa

;
// Generated Jan 6, 2016 6:08:10 PM by hall orm generator 4.3.1.Final


import javax.persistence.{Column, Entity, Id, Table}

import nirvana.hall.orm.services.{ActiveRecord, ActiveRecordInstance};

/**
 * SyncTarget generated by hall orm 
 */
object SyncTarget extends ActiveRecordInstance[SyncTarget]

@Entity
@Table(name = "SYNC_TARGET"
)
class SyncTarget extends ActiveRecord {


  @Id
  @Column(name = "PK_ID", unique = true, nullable = false, length = 32)
  var pkId: java.lang.String = _
  @Column(name = "TARGET_SID", length = 10)
  var targetSid: java.lang.String = _
  @Column(name = "TARGET_NAME", length = 20)
  var targetName: java.lang.String = _
  @Column(name = "TARGET_IP", length = 20)
  var targetIp: java.lang.String = _
  @Column(name = "TARGET_PORT", length = 10)
  var targetPort: java.lang.String = _
  @Column(name = "TARGET_USERNAME", length = 20)
  var targetUsername: java.lang.String = _
  @Column(name = "DELTAG", length = 2)
  var deltag: java.lang.String = _


  def this(pkId: java.lang.String) {
    this()
    this.pkId = pkId
  }

  def this(pkId: java.lang.String, targetSid: java.lang.String, targetName: java.lang.String, targetIp: java.lang.String, targetPort: java.lang.String, targetUsername: java.lang.String, deltag: java.lang.String) {
    this()
    this.pkId = pkId
    this.targetSid = targetSid
    this.targetName = targetName
    this.targetIp = targetIp
    this.targetPort = targetPort
    this.targetUsername = targetUsername
    this.deltag = deltag
  }


}


