package nirvana.hall.api.jpa

;
// Generated Jan 6, 2016 6:08:10 PM by hall orm generator 4.3.1.Final


import javax.persistence.{Column, Entity, Id, Table, Temporal, TemporalType}

import nirvana.hall.orm.services.{ActiveRecord, ActiveRecordInstance};

/**
 * SyncQueue generated by hall orm 
 */
object SyncQueue extends ActiveRecordInstance[SyncQueue]

@Entity
@Table(name = "SYNC_QUEUE"
)
class SyncQueue extends ActiveRecord {


  @Id
  @Column(name = "PK_ID", unique = true, nullable = false, length = 32)
  var pkId: java.lang.String = _
  @Column(name = "UPLOAD_KEYID", length = 32)
  var uploadKeyid: java.lang.String = _
  @Column(name = "UPLOAD_FLAG", length = 2)
  var uploadFlag: java.lang.String = _
  @Column(name = "UPLOAD_TYPE", length = 2)
  var uploadType: java.lang.String = _
  @Column(name = "UPLOAD_STATUS", length = 10)
  var uploadStatus: java.lang.String = _
  @Column(name = "UPLAOD_TIMES")
  var uplaodTimes: java.lang.Short = _
  @Column(name = "HAS_PALM", length = 2)
  var hasPalm: java.lang.String = _
  @Column(name = "TARGET_IP", length = 20)
  var targetIp: java.lang.String = _
  @Column(name = "TARGET_PORT", length = 10)
  var targetPort: java.lang.String = _
  @Column(name = "TARGET_USERNAME", length = 20)
  var targetUsername: java.lang.String = _
  @Column(name = "TARGET_SID", length = 10)
  var targetSid: java.lang.String = _
  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "CREATEDATE", length = 23)
  var createdate: java.util.Date = _
  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "FINISHDATE", length = 23)
  var finishdate: java.util.Date = _
  @Column(name = "OPRATION", length = 10)
  var opration: java.lang.String = _
  @Column(name = "REMARK", length = 500)
  var remark: java.lang.String = _


  def this(pkId: java.lang.String) {
    this()
    this.pkId = pkId
  }

  def this(pkId: java.lang.String, uploadKeyid: java.lang.String, uploadFlag: java.lang.String, uploadType: java.lang.String, uploadStatus: java.lang.String, uplaodTimes: java.lang.Short, hasPalm: java.lang.String, targetIp: java.lang.String, targetPort: java.lang.String, targetUsername: java.lang.String, targetSid: java.lang.String, createdate: java.util.Date, finishdate: java.util.Date, opration: java.lang.String, remark: java.lang.String) {
    this()
    this.pkId = pkId
    this.uploadKeyid = uploadKeyid
    this.uploadFlag = uploadFlag
    this.uploadType = uploadType
    this.uploadStatus = uploadStatus
    this.uplaodTimes = uplaodTimes
    this.hasPalm = hasPalm
    this.targetIp = targetIp
    this.targetPort = targetPort
    this.targetUsername = targetUsername
    this.targetSid = targetSid
    this.createdate = createdate
    this.finishdate = finishdate
    this.opration = opration
    this.remark = remark
  }


}


