package nirvana.hall.api.jpa;
// Generated Jan 6, 2016 6:08:10 PM by hall orm generator 4.3.1.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import nirvana.hall.orm.services.ActiveRecord;
import nirvana.hall.orm.services.ActiveRecordInstance;

/**
 * SysControlLog generated by hall orm 
 */
object SysControlLog extends ActiveRecordInstance[SysControlLog]

@Entity
@Table(name="SYS_CONTROL_LOG"
)
class SysControlLog extends ActiveRecord {


      @Id 
         @Column(name="PK_ID", unique=true, nullable=false, length=32)
     var pkId:java.lang.String =  _
     @Version     @Column(name="VERSION", length=10)
     var version:java.lang.String =  _
          @Column(name="IP", length=15)
     var ip:java.lang.String =  _
          @Column(name="MAC", length=50)
     var mac:java.lang.String =  _
          @Column(name="SYS_TYPE", length=1)
     var sysType:java.lang.String =  _
     @Temporal(TemporalType.TIMESTAMP)     @Column(name="UPDATE_TIME", length=23)
     var updateTime:java.util.Date =  _
          @Column(name="STATE", length=1)
     var state:java.lang.String =  _


	
    def this(pkId:java.lang.String) {
        this()
        this.pkId = pkId
    }
    def this(pkId:java.lang.String, ip:java.lang.String, mac:java.lang.String, sysType:java.lang.String, updateTime:java.util.Date, state:java.lang.String) {
       this()
       this.pkId = pkId
       this.ip = ip
       this.mac = mac
       this.sysType = sysType
       this.updateTime = updateTime
       this.state = state
    }
   




}


