package nirvana.hall.api.jpa

;
// Generated Jan 6, 2016 6:08:10 PM by hall orm generator 4.3.1.Final


import javax.persistence.{Column, Entity, Id, Table}

import nirvana.hall.orm.services.{ActiveRecord, ActiveRecordInstance};

/**
 * SysFunction generated by hall orm 
 */
object SysFunction extends ActiveRecordInstance[SysFunction]

@Entity
@Table(name = "SYS_FUNCTION"
)
class SysFunction extends ActiveRecord {


  @Id
  @Column(name = "FUNCTION_ID", unique = true, nullable = false, length = 32)
  var functionId: java.lang.String = _
  @Column(name = "NAME", length = 90)
  var name: java.lang.String = _
  @Column(name = "REMARK", length = 300)
  var remark: java.lang.String = _


  def this(functionId: java.lang.String) {
    this()
    this.functionId = functionId
  }

  def this(functionId: java.lang.String, name: java.lang.String, remark: java.lang.String) {
    this()
    this.functionId = functionId
    this.name = name
    this.remark = remark
  }


}


