package nirvana.hall.api.jpa

;
// Generated Jan 6, 2016 6:08:10 PM by hall orm generator 4.3.1.Final


import javax.persistence.{Column, Entity, Id, Table, Temporal, TemporalType}

import nirvana.hall.orm.services.{ActiveRecord, ActiveRecordInstance};

/**
 * SysMeg generated by hall orm 
 */
object SysMeg extends ActiveRecordInstance[SysMeg]

@Entity
@Table(name = "SYS_MEG"
)
class SysMeg extends ActiveRecord {


  @Id
  @Column(name = "PK_ID", unique = true, nullable = false, length = 32)
  var pkId: java.lang.String = _
  @Column(name = "PERSON_ID", nullable = false, length = 32)
  var personId: java.lang.String = _
  @Column(name = "PERSON_NAME", length = 60)
  var personName: java.lang.String = _
  @Column(name = "GATHER_USER_ID", length = 32)
  var gatherUserId: java.lang.String = _
  @Column(name = "MEG_TYPE")
  var megType: java.lang.Long = _
  @Column(name = "MESSAGE", length = 200)
  var message: java.lang.String = _
  @Column(name = "LOOK_STATUS")
  var lookStatus: java.lang.Long = _
  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "INPUTTIME", length = 23)
  var inputtime: java.util.Date = _
  @Column(name = "GATHER_DEPART_CODE", length = 12)
  var gatherDepartCode: java.lang.String = _


  def this(pkId: java.lang.String, personId: java.lang.String) {
    this()
    this.pkId = pkId
    this.personId = personId
  }

  def this(pkId: java.lang.String, personId: java.lang.String, personName: java.lang.String, gatherUserId: java.lang.String, megType: java.lang.Long, message: java.lang.String, lookStatus: java.lang.Long, inputtime: java.util.Date, gatherDepartCode: java.lang.String) {
    this()
    this.pkId = pkId
    this.personId = personId
    this.personName = personName
    this.gatherUserId = gatherUserId
    this.megType = megType
    this.message = message
    this.lookStatus = lookStatus
    this.inputtime = inputtime
    this.gatherDepartCode = gatherDepartCode
  }


}


