package nirvana.hall.api.jpa

;
// Generated Jan 6, 2016 6:08:10 PM by hall orm generator 4.3.1.Final


import javax.persistence.{Column, Entity, Id, Table, Temporal, TemporalType}

import nirvana.hall.orm.services.{ActiveRecord, ActiveRecordInstance};

/**
 * SysUserLogintimeControl generated by hall orm 
 */
object SysUserLogintimeControl extends ActiveRecordInstance[SysUserLogintimeControl]

@Entity
@Table(name = "SYS_USER_LOGINTIME_CONTROL"
)
class SysUserLogintimeControl extends ActiveRecord {


  @Id
  @Column(name = "PK_ID", unique = true, nullable = false, length = 32)
  var pkId: java.lang.String = _
  @Column(name = "USER_ID", length = 32)
  var userId: java.lang.String = _
  @Column(name = "CONTROL_ID", length = 32)
  var controlId: java.lang.String = _
  @Column(name = "CREATE_USER", length = 32)
  var createUser: java.lang.String = _
  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "CREATE_TIME", length = 23)
  var createTime: java.util.Date = _


  def this(pkId: java.lang.String) {
    this()
    this.pkId = pkId
  }

  def this(pkId: java.lang.String, userId: java.lang.String, controlId: java.lang.String, createUser: java.lang.String, createTime: java.util.Date) {
    this()
    this.pkId = pkId
    this.userId = userId
    this.controlId = controlId
    this.createUser = createUser
    this.createTime = createTime
  }


}


