package nirvana.hall.v70.jpa

;
// Generated Jan 6, 2016 6:08:10 PM by hall orm generator 4.3.1.Final


import javax.persistence.{Column, Entity, Id, Table}

import nirvana.hall.orm.services.{ActiveRecord, ActiveRecordInstance};

/**
 * GafisPersonAtt generated by hall orm 
 */
object GafisPersonAtt extends ActiveRecordInstance[GafisPersonAtt]

@Entity
@Table(name = "GAFIS_PERSON_ATT"
)
class GafisPersonAtt extends ActiveRecord {


  @Id
  @Column(name = "PK_ID", unique = true, nullable = false, length = 32)
  var pkId: java.lang.String = _
  @Column(name = "IMG")
  var img: java.sql.Blob = _
  @Column(name = "TYPE", length = 2)
  var typeCol: java.lang.String = _
  @Column(name = "PERSONID", length = 23)
  var personid: java.lang.String = _
  @Column(name = "GATHERDATANOSQLID", length = 10)
  var gatherdatanosqlid: java.lang.String = _


  def this(pkId: java.lang.String) {
    this()
    this.pkId = pkId
  }

  def this(pkId: java.lang.String, img: java.sql.Blob,

  typeCol: java.lang.String, personid: java.lang.String, gatherdatanosqlid: java.lang.String)
  {
    this()
    this.pkId = pkId
    this.img = img
    this.typeCol = typeCol
    this.personid = personid
    this.gatherdatanosqlid = gatherdatanosqlid
  }


}


