package nirvana.hall.v70.jpa

;
// Generated Jan 6, 2016 6:08:10 PM by hall orm generator 4.3.1.Final


import javax.persistence.{Column, Entity, Id, Table, Temporal, TemporalType}

import stark.activerecord.services.{ActiveRecord, ActiveRecordInstance}

/**
 * GafisGatherPersonPhoto generated by hall orm 
 */
object GafisGatherPersonPhoto extends ActiveRecordInstance[GafisGatherPersonPhoto]

@Entity
@Table(name = "GAFIS_GATHER_PERSON_PHOTO"
)
class GafisGatherPersonPhoto extends ActiveRecord {


  @Id
  @Column(name = "PK_ID", unique = true, nullable = false, length = 32)
  var pkId: java.lang.String = _
  @Column(name = "PERSONID", length = 32)
  var personid: java.lang.String = _
  @Column(name = "PHOTO_CODE", nullable = false, length = 10)
  var photoCode: java.lang.String = _
  @Column(name = "PHOTO_DATA", nullable = false)
  var photoData: java.sql.Blob = _
  @Column(name = "PHOTO_ORG")
  var photoOrg: java.lang.Long = _
  @Column(name = "INPUTPSN", length = 32)
  var inputpsn: java.lang.String = _
  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "INPUTTIME", nullable = false, length = 23)
  var inputtime: java.util.Date = _
  @Column(name = "MODIFIEDPSN", length = 32)
  var modifiedpsn: java.lang.String = _
  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "MODIFIEDTIME", length = 23)
  var modifiedtime: java.util.Date = _
  @Column(name = "COMMENTS", length = 1000)
  var comments: java.lang.String = _


  def this(pkId: java.lang.String, photoCode: java.lang.String, photoData: java.sql.Blob, inputtime: java.util.Date) {
    this()
    this.pkId = pkId
    this.photoCode = photoCode
    this.photoData = photoData
    this.inputtime = inputtime
  }

  def this(pkId: java.lang.String, personid: java.lang.String, photoCode: java.lang.String, photoData: java.sql.Blob, photoOrg: java.lang.Long, inputpsn: java.lang.String, inputtime: java.util.Date, modifiedpsn: java.lang.String, modifiedtime: java.util.Date, comments: java.lang.String) {
    this()
    this.pkId = pkId
    this.personid = personid
    this.photoCode = photoCode
    this.photoData = photoData
    this.photoOrg = photoOrg
    this.inputpsn = inputpsn
    this.inputtime = inputtime
    this.modifiedpsn = modifiedpsn
    this.modifiedtime = modifiedtime
    this.comments = comments
  }


}


