package nirvana.hall.v70.jpa

;
// Generated Jan 6, 2016 6:08:10 PM by hall orm generator 4.3.1.Final


import javax.persistence.{Column, Entity, Id, Table, Temporal, TemporalType}

import nirvana.hall.orm.services.{ActiveRecord, ActiveRecordInstance};

/**
 * GafisGatherDataLog generated by hall orm 
 */
object GafisGatherDataLog extends ActiveRecordInstance[GafisGatherDataLog]

@Entity
@Table(name = "GAFIS_GATHER_DATA_LOG"
)
class GafisGatherDataLog extends ActiveRecord {


  @Id
  @Column(name = "PK_ID", unique = true, nullable = false, length = 32)
  var pkId: java.lang.String = _
  @Column(name = "USER_ID", length = 32)
  var userId: java.lang.String = _
  @Column(name = "USER_NAME", length = 90)
  var userName: java.lang.String = _
  @Column(name = "UNIT_CODE", length = 12)
  var unitCode: java.lang.String = _
  @Column(name = "UNIT_NAME", length = 90)
  var unitName: java.lang.String = _
  @Column(name = "IP", length = 15)
  var ip: java.lang.String = _
  @Column(name = "OBJECT_ID", length = 32)
  var objectId: java.lang.String = _
  @Column(name = "TABLE_NAME", length = 30)
  var tableName: java.lang.String = _
  @Column(name = "FGP", length = 2)
  var fgp: java.lang.String = _
  @Column(name = "OLD_DATA")
  var oldData: java.sql.Blob = _
  @Column(name = "NEW_DATA")
  var newData: java.sql.Blob = _
  @Column(name = "LOBTYPE")
  var lobtype: java.lang.Short = _
  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "CREATE_DATETIME", length = 23)
  var createDatetime: java.util.Date = _


  def this(pkId: java.lang.String) {
    this()
    this.pkId = pkId
  }

  def this(pkId: java.lang.String, userId: java.lang.String, userName: java.lang.String, unitCode: java.lang.String, unitName: java.lang.String, ip: java.lang.String, objectId: java.lang.String, tableName: java.lang.String, fgp: java.lang.String, oldData: java.sql.Blob, newData: java.sql.Blob, lobtype: java.lang.Short, createDatetime: java.util.Date) {
    this()
    this.pkId = pkId
    this.userId = userId
    this.userName = userName
    this.unitCode = unitCode
    this.unitName = unitName
    this.ip = ip
    this.objectId = objectId
    this.tableName = tableName
    this.fgp = fgp
    this.oldData = oldData
    this.newData = newData
    this.lobtype = lobtype
    this.createDatetime = createDatetime
  }


}


