package nirvana.hall.v70.jpa

/**
  * Created by Administrator on 2017/5/27.
  */

import javax.persistence.{Column, Entity, Id, Table}

import stark.activerecord.services.{ActiveRecord, ActiveRecordInstance}

/**
  * GafisLogicDbFingerprint generated by hall orm
  */
object GafisLogicDbFingerprintBak extends ActiveRecordInstance[GafisLogicDbFingerprintBak]

@Entity
@Table(name = "GAFIS_LOGIC_DB_FINGERPRINT_BAK"
)
class GafisLogicDbFingerprintBak extends ActiveRecord {


  @Id
  @Column(name = "PK_ID", unique = true, nullable = false, length = 32)
  var pkId: java.lang.String = _
  @Column(name = "LOGIC_DB_PKID", length = 32)
  var logicDbPkid: java.lang.String = _
  @Column(name = "FINGERPRINT_PKID", length = 32)
  var fingerprintPkid: java.lang.String = _


  def this(pkId: java.lang.String) {
    this()
    this.pkId = pkId
  }

  def this(pkId: java.lang.String, logicDbPkid: java.lang.String, fingerprintPkid: java.lang.String) {
    this()
    this.pkId = pkId
    this.logicDbPkid = logicDbPkid
    this.fingerprintPkid = fingerprintPkid
  }

  def this(gafisLogicDbFingerprint:GafisLogicDbFingerprint) {
    this()
    this.pkId = gafisLogicDbFingerprint.pkId
    this.logicDbPkid = gafisLogicDbFingerprint.logicDbPkid
    this.fingerprintPkid = gafisLogicDbFingerprint.fingerprintPkid
  }
}


