package nirvana.hall.v70.jpa

;
// Generated Jan 6, 2016 6:08:10 PM by hall orm generator 4.3.1.Final


import javax.persistence.{Column, Entity, Id, Table}

import stark.activerecord.services.{ActiveRecord, ActiveRecordInstance}

/**
 * SyncGafis6 generated by hall orm 
 */
object SyncGafis6Config extends ActiveRecordInstance[SyncGafis6Config]

@Entity
@Table(name = "SYNC_GAFIS6_CONFIG")
class SyncGafis6Config extends ActiveRecord {

  @Id
  @Column(name = "PK_ID", unique = true, nullable = false, length = 1)
  var pkId: java.lang.String = _
  @Column(name = "IP", length = 20)
  var ip: java.lang.String = _
  @Column(name = "PORT", length = 10)
  var port: java.lang.String = _
  @Column(name = "TPCARD_TIMESTAMP")
  var tpcardTimestamp: java.lang.Long = _
  @Column(name = "LPCARD_TIMESTAMP")
  var lpcardTimestamp: java.lang.Long = _
  @Column(name = "CASE_TIMESTAMP")
  var caseTimestamp: java.lang.Long = _

  def this(pkId: java.lang.String) {
    this()
    this.pkId = pkId
  }

  def this(pkId: java.lang.String, ip: java.lang.String, port: java.lang.String, tpcardTimestamp: java.lang.Long, lpcardTimestamp: java.lang.Long,caseTimestamp: java.lang.Long) {
    this()
    this.pkId = pkId
    this.ip = ip
    this.port = port
    this.tpcardTimestamp = tpcardTimestamp
    this.lpcardTimestamp = lpcardTimestamp
    this.caseTimestamp = caseTimestamp
  }
}


