package nirvana.hall.v70.jpa

;
// Generated Jan 6, 2016 6:08:10 PM by hall orm generator 4.3.1.Final


import javax.persistence.{Column, Entity, Id, Table}

import stark.activerecord.services.{ActiveRecord, ActiveRecordInstance}

/**
 * SyncGafis6 generated by hall orm 
 */
object SyncConfig extends ActiveRecordInstance[SyncConfig]

@Entity
@Table(name = "SYNC_CONFIG")
class SyncConfig extends ActiveRecord {

  @Id
  @Column(name = "PK_ID", unique = true, nullable = false, length = 32)
  var pkId: java.lang.String = _
  @Column(name = "URL", length = 20)
  var url: java.lang.String = _
  @Column(name = "TPCARD_TIMESTAMP")
  var tpcardTimestamp: java.lang.Long = _
  @Column(name = "CASE_TIMESTAMP")
  var caseTimestamp: java.lang.Long = _
  @Column(name = "LPCARD_TIMESTAMP")
  var lpcardTimestamp: java.lang.Long = _

  def this(pkId: java.lang.String) {
    this()
    this.pkId = pkId
  }

  def this(pkId: java.lang.String, url: java.lang.String, tpcardTimestamp: java.lang.Long, lpcardTimestamp: java.lang.Long,caseTimestamp: java.lang.Long) {
    this()
    this.pkId = pkId
    this.url = url
    this.tpcardTimestamp = tpcardTimestamp
    this.lpcardTimestamp = lpcardTimestamp
    this.caseTimestamp = caseTimestamp
  }
}


