package nirvana.hall.v70.jpa

;
// Generated Jan 6, 2016 6:08:10 PM by hall orm generator 4.3.1.Final


import javax.persistence.{Column, Entity, Id, Table}

import stark.activerecord.services.{ActiveRecord, ActiveRecordInstance}

/**
 * SysArea generated by hall orm 
 */
object SysArea extends ActiveRecordInstance[SysArea]

@Entity
@Table(name = "SYS_AREA"
)
class SysArea extends ActiveRecord {


  @Id
  @Column(name = "AREA_CODE", unique = true, nullable = false, length = 10)
  var areaCode: java.lang.String = _
  @Column(name = "AREA_NAME", length = 90)
  var areaName: java.lang.String = _
  @Column(name = "AREA_ALIAS", length = 90)
  var areaAlias: java.lang.String = _
  @Column(name = "PARENT_ID", length = 10)
  var parentId: java.lang.String = _
  @Column(name = "DELETE_FLAG", length = 1)
  var deleteFlag: java.lang.String = _
  @Column(name = "REMARK", length = 90)
  var remark: java.lang.String = _
  @Column(name = "IS_LEAF", length = 1)
  var isLeaf: java.lang.String = _
  @Column(name = "AREANUMBER", length = 10)
  var areanumber: java.lang.String = _
  @Column(name = "AREA_FIRST_LETTER", length = 30)
  var areaFirstLetter: java.lang.String = _


  def this(areaCode: java.lang.String) {
    this()
    this.areaCode = areaCode
  }

  def this(areaCode: java.lang.String, areaName: java.lang.String, areaAlias: java.lang.String, parentId: java.lang.String, deleteFlag: java.lang.String, remark: java.lang.String, isLeaf: java.lang.String, areanumber: java.lang.String, areaFirstLetter: java.lang.String) {
    this()
    this.areaCode = areaCode
    this.areaName = areaName
    this.areaAlias = areaAlias
    this.parentId = parentId
    this.deleteFlag = deleteFlag
    this.remark = remark
    this.isLeaf = isLeaf
    this.areanumber = areanumber
    this.areaFirstLetter = areaFirstLetter
  }


}


