package nirvana.hall.v70.jpa

;
// Generated Jan 6, 2016 6:08:10 PM by hall orm generator 4.3.1.Final


import javax.persistence.{Column, Entity, Id, Table, Temporal, TemporalType}

import stark.activerecord.services.{ActiveRecord, ActiveRecordInstance}

/**
 * SysControl generated by hall orm 
 */
object SysControl extends ActiveRecordInstance[SysControl]

@Entity
@Table(name = "SYS_CONTROL"
)
class SysControl extends ActiveRecord {


  @Id
  @Column(name = "PK_ID", unique = true, nullable = false, length = 32)
  var pkId: java.lang.String = _
  @Column(name = "VERSION", length = 10)
  var version: java.lang.String = _
  @Column(name = "UPLOAD_PERSON", length = 32)
  var uploadPerson: java.lang.String = _
  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "UPLOAD_TIME", length = 23)
  var uploadTime: java.util.Date = _
  @Column(name = "CLIENT_TYPE", length = 1)
  var clientType: java.lang.String = _
  @Column(name = "FILE_PATH", length = 200)
  var filePath: java.lang.String = _
  @Column(name = "ENABLE_FLAG", length = 1)
  var enableFlag: java.lang.String = _
  @Column(name = "SYS_TYPE", length = 1)
  var sysType: java.lang.String = _


  def this(pkId: java.lang.String) {
    this()
    this.pkId = pkId
  }

  def this(pkId: java.lang.String, uploadPerson: java.lang.String, uploadTime: java.util.Date, clientType: java.lang.String, filePath: java.lang.String, enableFlag: java.lang.String, sysType: java.lang.String) {
    this()
    this.pkId = pkId
    this.uploadPerson = uploadPerson
    this.uploadTime = uploadTime
    this.clientType = clientType
    this.filePath = filePath
    this.enableFlag = enableFlag
    this.sysType = sysType
  }


}


