package nirvana.hall.v70.jpa

;
// Generated Jan 6, 2016 6:08:10 PM by hall orm generator 4.3.1.Final


import javax.persistence.{Column, Entity, Id, Table, Temporal, TemporalType}

import stark.activerecord.services.{ActiveRecord, ActiveRecordInstance}

/**
 * SysRoleFunction generated by hall orm 
 */
object SysRoleFunction extends ActiveRecordInstance[SysRoleFunction]

@Entity
@Table(name = "SYS_ROLE_FUNCTION"
)
class SysRoleFunction extends ActiveRecord {


  @Id
  @Column(name = "PK_ID", unique = true, nullable = false, length = 32)
  var pkId: java.lang.String = _
  @Column(name = "ROLE_ID", length = 32)
  var roleId: java.lang.String = _
  @Column(name = "FUNCTION_ID", length = 32)
  var functionId: java.lang.String = _
  @Column(name = "CREATE_USER_ID", length = 32)
  var createUserId: java.lang.String = _
  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "CREATE_DATETIME", length = 23)
  var createDatetime: java.util.Date = _


  def this(pkId: java.lang.String) {
    this()
    this.pkId = pkId
  }

  def this(pkId: java.lang.String, roleId: java.lang.String, functionId: java.lang.String, createUserId: java.lang.String, createDatetime: java.util.Date) {
    this()
    this.pkId = pkId
    this.roleId = roleId
    this.functionId = functionId
    this.createUserId = createUserId
    this.createDatetime = createDatetime
  }


}


