package nirvana.hall.v70.jpa

;
// Generated Jan 6, 2016 6:08:10 PM by hall orm generator 4.3.1.Final


import javax.persistence.{Column, Entity, Id, Table, Temporal, TemporalType}

import nirvana.hall.orm.services.{ActiveRecord, ActiveRecordInstance};

/**
 * SysRole generated by hall orm 
 */
object SysRole extends ActiveRecordInstance[SysRole]

@Entity
@Table(name = "SYS_ROLE"
)
class SysRole extends ActiveRecord {


  @Id
  @Column(name = "PK_ID", unique = true, nullable = false, length = 32)
  var pkId: java.lang.String = _
  @Column(name = "ROLE_NAME", nullable = false, length = 60)
  var roleName: java.lang.String = _
  @Column(name = "ROLE_DESCRIPTION", length = 90)
  var roleDescription: java.lang.String = _
  @Column(name = "DELETE_FLAG", length = 1)
  var deleteFlag: java.lang.String = _
  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "CREATE_DATETIME", nullable = false, length = 23)
  var createDatetime: java.util.Date = _
  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "UPDATE_DATETIME", length = 23)
  var updateDatetime: java.util.Date = _
  @Column(name = "CREATE_USER_ID", length = 32)
  var createUserId: java.lang.String = _
  @Column(name = "UPDATE_USER_ID", length = 32)
  var updateUserId: java.lang.String = _
  @Column(name = "ROLE_LEVEL", length = 1)
  var roleLevel: java.lang.String = _
  @Column(name = "SYS_CODE", length = 2)
  var sysCode: java.lang.String = _
  @Column(name = "ROLE_SIGN", length = 20)
  var roleSign: java.lang.String = _


  def this(pkId: java.lang.String, roleName: java.lang.String, createDatetime: java.util.Date) {
    this()
    this.pkId = pkId
    this.roleName = roleName
    this.createDatetime = createDatetime
  }

  def this(pkId: java.lang.String, roleName: java.lang.String, roleDescription: java.lang.String, deleteFlag: java.lang.String, createDatetime: java.util.Date, updateDatetime: java.util.Date, createUserId: java.lang.String, updateUserId: java.lang.String, roleLevel: java.lang.String, sysCode: java.lang.String, roleSign: java.lang.String) {
    this()
    this.pkId = pkId
    this.roleName = roleName
    this.roleDescription = roleDescription
    this.deleteFlag = deleteFlag
    this.createDatetime = createDatetime
    this.updateDatetime = updateDatetime
    this.createUserId = createUserId
    this.updateUserId = updateUserId
    this.roleLevel = roleLevel
    this.sysCode = sysCode
    this.roleSign = roleSign
  }


}


