package nirvana.hall.v70.internal.adapter.ln.jpa

// Generated 2017-10-23 11:12:54 by Stark Activerecord generator 4.3.1.Final


import javax.persistence._

import stark.activerecord.services.{ActiveRecord, ActiveRecordInstance};

/**
  * GafisNormalqueryQueryque generated by stark activerecord generator
  */
object GafisNormalqueryQueryque extends ActiveRecordInstance[GafisNormalqueryQueryque]

@Entity
@Table(name = "GAFIS_NORMALQUERY_QUERYQUE"
)
class GafisNormalqueryQueryque extends ActiveRecord {


  @Id
  @Column(name = "PK_ID", unique = true, nullable = false, length = 32)
  var pkId: java.lang.String = _
  @Column(name = "ORA_SID", precision = 15, scale = 0)
  var oraSid: java.lang.Long = _
  @Column(name = "KEYID", length = 25)
  var keyid: java.lang.String = _
  @Column(name = "QUERYTYPE", precision = 3, scale = 0)
  var querytype: java.lang.Short = _
  @Column(name = "STATUS", precision = 3, scale = 0)
  var status: java.lang.Short = _
  @Column(name = "PRIORITY", precision = 3, scale = 0)
  var priority: java.lang.Short = _
  @Column(name = "HITPOSSIBILITY", precision = 3, scale = 0)
  var hitpossibility: java.lang.Short = _
  @Column(name = "VERIFYRESULT", precision = 3, scale = 0)
  var verifyresult: java.lang.Short = _
  @Column(name = "FLAG", precision = 3, scale = 0)
  var flag: java.lang.Short = _
  @Column(name = "FLAGC", precision = 3, scale = 0)
  var flagc: java.lang.Short = _
  @Column(name = "FLAGD", precision = 3, scale = 0)
  var flagd: java.lang.Short = _
  @Column(name = "FLAGE", precision = 3, scale = 0)
  var flage: java.lang.Short = _
  @Column(name = "FLAGG", precision = 3, scale = 0)
  var flagg: java.lang.Short = _
  @Lob
  @Column(name = "QRYCONDITION")
  var qrycondition: Array[Byte] = _
  @Lob
  @Column(name = "MIC")
  var mic: Array[Byte] = _
  @Column(name = "TEXTSQL")
  var textsql: java.lang.String = _
  @Lob
  @Column(name = "CANDHEAD")
  var candhead: Array[Byte] = _
  @Lob
  @Column(name = "CANDLIST")
  var candlist: Array[Byte] = _
  @Column(name = "TIMEUSED", precision = 10, scale = 0)
  var timeused: java.lang.Long = _
  @Column(name = "MAXCANDNUM", precision = 10, scale = 0)
  var maxcandnum: java.lang.Long = _
  @Column(name = "CURCANDNUM", precision = 10, scale = 0)
  var curcandnum: java.lang.Long = _
  @Column(name = "MINSCORE", precision = 10, scale = 0)
  var minscore: java.lang.Long = _
  @Column(name = "STARTKEY1", length = 32)
  var startkey1: java.lang.String = _
  @Column(name = "ENDKEY1", length = 32)
  var endkey1: java.lang.String = _
  @Column(name = "STARTKEY2", length = 32)
  var startkey2: java.lang.String = _
  @Column(name = "ENDKEY2", length = 32)
  var endkey2: java.lang.String = _
  @Column(name = "USERNAME", length = 32)
  var username: java.lang.String = _
  @Column(name = "USERUNITCODE", length = 12)
  var userunitcode: java.lang.String = _
  @Temporal(TemporalType.DATE)
  @Column(name = "FINISHTIME", length = 8)
  var finishtime: java.util.Date = _
  @Column(name = "COMPUTERIP", length = 32)
  var computerip: java.lang.String = _
  @Column(name = "COMPUTERNAME", length = 32)
  var computername: java.lang.String = _
  @Column(name = "ORACOMMENT")
  var oracomment: java.lang.String = _
  @Column(name = "MAXSCORE")
  var maxscore: java.lang.Long = _
  @Temporal(TemporalType.DATE)
  @Column(name = "CREATETIME", length = 8)
  var createtime: java.util.Date = _
  @Temporal(TemporalType.DATE)
  @Column(name = "BEGINTIME", length = 8)
  var begintime: java.util.Date = _
  @Column(name = "DELETAG", length = 1)
  var deletag: java.lang.String = _
  @Column(name = "USERID", length = 32)
  var userid: java.lang.String = _
  @Column(name = "SUBMITTSYSTEM", length = 32)
  var submittsystem: java.lang.String = _
  @Column(name = "PRIORITYNEW", precision = 3, scale = 0)
  var prioritynew: java.lang.Short = _
  @Column(name = "HANDLERESULT", precision = 3, scale = 0)
  var handleresult: java.lang.Short = _
  @Column(name = "QRYCONDITION_NOSQL_ID", length = 10)
  var qryconditionNosqlId: java.lang.String = _
  @Column(name = "MIC_NOSQL_ID", length = 10)
  var micNosqlId: java.lang.String = _
  @Column(name = "CANDHEAD_NOSQL_ID", length = 10)
  var candheadNosqlId: java.lang.String = _
  @Column(name = "CANDLIST_NOSQL_ID", length = 10)
  var candlistNosqlId: java.lang.String = _
  @Column(name = "TIME_ELAPSED")
  var timeElapsed: java.lang.Long = _
  @Column(name = "RECORD_NUM_MATCHED")
  var recordNumMatched: java.lang.Long = _
  @Column(name = "MATCH_PROGRESS", precision = 3, scale = 0)
  var matchProgress: java.lang.Short = _
  @Column(name = "MESSAGETAG", precision = 1, scale = 0)
  var messagetag: java.lang.Boolean = _
  @Column(name = "OVERTIMETAG", precision = 1, scale = 0)
  var overtimetag: java.lang.Boolean = _
  @Column(name = "SYNC_TARGET_SID", length = 10)
  var syncTargetSid: java.lang.String = _
  @Column(name = "DATA_LOCK", length = 60)
  var dataLock: java.lang.String = _
  @Column(name = "GZZLBH", length = 32)
  var gzzlbh: java.lang.String = _
  @Column(name = "QUERYID", scale = 0)
  var queryid: java.lang.Long = _
  @Column(name = "IS_REPORT", length = 1)
  var isReport: java.lang.String = _
  @Column(name = "KEYLIST")
  var keylist: java.lang.String = _
  @Temporal(TemporalType.DATE)
  @Column(name = "HANDLE_TIME", length = 8)
  var handleTime: java.util.Date = _
  @Column(name = "IF_LIVING_GATHER", length = 2)
  var ifLivingGather: java.lang.String = _


  def this(pkId: java.lang.String) {
    this()
    this.pkId = pkId
  }

  def this(pkId: java.lang.String, oraSid: java.lang.Long, keyid: java.lang.String, querytype: java.lang.Short, status: java.lang.Short, priority: java.lang.Short, hitpossibility: java.lang.Short, verifyresult: java.lang.Short, flag: java.lang.Short, flagc: java.lang.Short, flagd: java.lang.Short, flage: java.lang.Short, flagg: java.lang.Short, qrycondition: Array[Byte], mic: Array[Byte], textsql: java.lang.String, candhead: Array[Byte], candlist: Array[Byte], timeused: java.lang.Long, maxcandnum: java.lang.Long, curcandnum: java.lang.Long, minscore: java.lang.Long, startkey1: java.lang.String, endkey1: java.lang.String, startkey2: java.lang.String, endkey2: java.lang.String, username: java.lang.String, userunitcode: java.lang.String, finishtime: java.util.Date, computerip: java.lang.String, computername: java.lang.String, oracomment: java.lang.String, maxscore: java.lang.Long, createtime: java.util.Date, begintime: java.util.Date, deletag: java.lang.String, userid: java.lang.String, submittsystem: java.lang.String, prioritynew: java.lang.Short, handleresult: java.lang.Short, qryconditionNosqlId: java.lang.String, micNosqlId: java.lang.String, candheadNosqlId: java.lang.String, candlistNosqlId: java.lang.String, timeElapsed: java.lang.Long, recordNumMatched: java.lang.Long, matchProgress: java.lang.Short, messagetag: java.lang.Boolean, overtimetag: java.lang.Boolean, syncTargetSid: java.lang.String, dataLock: java.lang.String, gzzlbh: java.lang.String, queryid: java.lang.Long, isReport: java.lang.String, keylist: java.lang.String, handleTime: java.util.Date, ifLivingGather: java.lang.String) {
    this()
    this.pkId = pkId
    this.oraSid = oraSid
    this.keyid = keyid
    this.querytype = querytype
    this.status = status
    this.priority = priority
    this.hitpossibility = hitpossibility
    this.verifyresult = verifyresult
    this.flag = flag
    this.flagc = flagc
    this.flagd = flagd
    this.flage = flage
    this.flagg = flagg
    this.qrycondition = qrycondition
    this.mic = mic
    this.textsql = textsql
    this.candhead = candhead
    this.candlist = candlist
    this.timeused = timeused
    this.maxcandnum = maxcandnum
    this.curcandnum = curcandnum
    this.minscore = minscore
    this.startkey1 = startkey1
    this.endkey1 = endkey1
    this.startkey2 = startkey2
    this.endkey2 = endkey2
    this.username = username
    this.userunitcode = userunitcode
    this.finishtime = finishtime
    this.computerip = computerip
    this.computername = computername
    this.oracomment = oracomment
    this.maxscore = maxscore
    this.createtime = createtime
    this.begintime = begintime
    this.deletag = deletag
    this.userid = userid
    this.submittsystem = submittsystem
    this.prioritynew = prioritynew
    this.handleresult = handleresult
    this.qryconditionNosqlId = qryconditionNosqlId
    this.micNosqlId = micNosqlId
    this.candheadNosqlId = candheadNosqlId
    this.candlistNosqlId = candlistNosqlId
    this.timeElapsed = timeElapsed
    this.recordNumMatched = recordNumMatched
    this.matchProgress = matchProgress
    this.messagetag = messagetag
    this.overtimetag = overtimetag
    this.syncTargetSid = syncTargetSid
    this.dataLock = dataLock
    this.gzzlbh = gzzlbh
    this.queryid = queryid
    this.isReport = isReport
    this.keylist = keylist
    this.handleTime = handleTime
    this.ifLivingGather = ifLivingGather
  }


}


