package nirvana.hall.v70.gz.jpa;


import javax.persistence.{Column, Entity, Id, Table}

import stark.activerecord.services.{ActiveRecord, ActiveRecordInstance}

/**
 * HallCaptureRecord generated by hall orm
 * Created by ssj on 2017/10/13.
 */
object HallCaptureRecord extends ActiveRecordInstance[HallCaptureRecord]

@Entity
@Table(name = "Hall_Capture_Record")
class HallCaptureRecord extends ActiveRecord {


  @Id
  @Column(name = "UUID", unique = true, nullable = false, length = 32)
  var uuid: java.lang.String = _
  @Column(name = "PERSONID", length = 23)
  var personid: java.lang.String = _
  @Column(name = "INSERTDATE", length = 23)
  var insertdate: java.util.Date = _
  @Column(name = "STATUS", length = 1)
  var status: java.lang.String = _
  @Column(name = "OPERA_TYPE", length = 1)
  var operatype: java.lang.String = _
  @Column(name = "IS_SEND_QUERY", length = 1)
  var issendquery: java.lang.String = _

  def this(uuid: java.lang.String) {
    this()
    this.uuid = uuid
  }

  def this(uuid: java.lang.String, personid: java.lang.String, insertdate: java.util.Date, status: java.lang.String, operatype: java.lang.String, issendquery: java.lang.String) {
    this()
    this.uuid = uuid
    this.personid = personid
    this.insertdate = insertdate
    this.status = status
    this.operatype = operatype
    this.issendquery = issendquery
  }


}


