package nirvana.hall.v70.internal.txserver.jpa

// Generated Feb 27, 2019 5:23:16 PM by Stark Activerecord generator 4.3.1.Final


import javax.persistence._

import stark.activerecord.services.{ActiveRecord, ActiveRecordInstance};

/**
  * CardLogSix generated by stark activerecord generator
  */
object CardLogSix extends ActiveRecordInstance[CardLogSix]

@Entity
@Table(name = "CARD_LOG_SIX")
class CardLogSix extends ActiveRecord {

  @Id
  @Column(name = "id", nullable = false, length = 32)
  var id: java.lang.String = _
  @Column(name = "cardid", length = 22)
  var cardid: java.lang.String = _
  @Column(name = "station_code", length = 12)
  var stationCode: java.lang.String = _
  @Column(name = "input_time", length = 10)
  var inputTime: java.util.Date = _


  def this(id: java.lang.String) {
    this()
    this.id = id
  }

  def this(id: java.lang.String, cardid: java.lang.String, stationCode: java.lang.String, inputTime: java.util.Date) {
    this()
    this.id = id
    this.cardid = cardid
    this.stationCode = stationCode
    this.inputTime = inputTime
  }
}


