package nirvana.hall.v70.internal.txserver.jpa

// Generated 2018-7-24 14:53:35 by Stark Activerecord generator 4.3.1.Final


import javax.persistence.{Column, Entity, Id, Table}

import stark.activerecord.services.{ActiveRecord, ActiveRecordInstance};

/**
  * LogEditrecord generated by stark activerecord generator
  */
object TaskRelation extends ActiveRecordInstance[TaskRelation]

@Entity
@Table(name = "TASK_RELATION")
class TaskRelation extends ActiveRecord {

  @Id
  @Column(name = "ID", unique = true, nullable = false, length = 32)
  var pkId: java.lang.String = _
  @Column(name = "TASK_NO_SIX", length = 18)
  var taskNoSix: java.lang.Long = _
  @Column(name = "TASK_NO_SEVEN", length = 18)
  var taskNoSeven: java.lang.Long = _
  @Column(name = "IS_FEEDBACK", length = 1)
  var isFeedback: java.lang.Integer = _
  @Column(name = "INIT_TIME")
  var initTime: java.util.Date = _


  def this(pkId: java.lang.String) {
    this()
    this.pkId = pkId
  }

  def this(pkId: java.lang.String, taskNoSix: java.lang.Long, taskNoSeven: java.lang.Long, isFeedback: java.lang.Integer, initTime: java.util.Date) {
    this()
    this.pkId = pkId
    this.taskNoSix = taskNoSix
    this.taskNoSeven = taskNoSeven
    this.isFeedback = isFeedback
    this.initTime = initTime
  }
}


